### PR TITLE
Progress on compiling F* with for OCaml 4.05.0

### PR DESCRIPTION
**Pull request by beurdouche**
Do not merge. This fails with:
```File "src/extraction/ml/FStar_Extraction_ML_PrintML.ml", line 98, characters 2-284:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
(MLC_Unit|MLC_Bool _)
File "src/extraction/ml/FStar_Extraction_ML_PrintML.ml", line 262, characters 54-58:
Error: This expression has type string list
       but an expression was expected of type string Asttypes.loc list
       Type string is not compatible with type
         string Asttypes.loc = string Location.loc 
Command exited with code 2.
Compilation unsuccessful after building 215 targets (0 cached) in 00:00:10.
make: *** [fstar.exe] Error 10
```

### CODE REVIEW

**Comment by beurdouche** [comment]
@kyoDralliam Would you mind have a look at this ? :) Thanks

**Comment by kyoDralliam** [comment]
This particular bug seems to be related to the changes from #1072 
The internal representation seems to have changed in the ocaml AST.
I will try to have a deeper look later unless @mtzguido have an idea on this...

**Comment by beurdouche** [comment]
Thanks :) Feel free to push directly in that branch if you want...

**Comment by mtzguido** [comment]
Indeed the internal AST type changed, just pushed a fix.

**Comment by beurdouche** [comment]
@mtzguido @kyoDralliam Thanks a lot !! :) Works on my machine, I'll merge that in master when I get the green from the CI.

**Comment by tchajed** [comment]
Oops, I have all of this locally but it's not quite enough so I didn't push it.

Did you do a full bootstrap? Running `make -C src ocaml-fstar-ocaml` doesn't work for me on my branch because the generated code no longer annotates let bindings, instead putting type ascriptions on the right-hand expressions. These should be about the same, except that explicit quantification over type variables (eg, `'a . 'a list`) is allowed when annotating a `let` binding but not elsewhere. I haven't gotten to the bottom of why this changed.

**Comment by beurdouche** [comment]
@tchajed Yes, this fully boostraps on my machine. And I have a CI green:
https://msresearch-ext.visualstudio.com/Everest/_build/index?buildId=11783&_a=summary

**Comment by mtzguido** [comment]
Yikes, that's weird, I'm running into the exact situation Tej describes.

It does seem we're putting the annotation on the RHS, (I imagine OCaml was previously checking for this and now it's not) but I don't see a way, from the Parsetree structures, to put it on the LHS. I'm taking a better look later.

**Comment by beurdouche** [comment]
Aha ! Yes indeed I can't bootstrap after a `git clean -xffd`...
```
cd ../../ && ocamlbuild -cflag '-g' -I src/ocaml-output -I src/basic/ml -I src/parser/ml -I src/fstar/ml -I src/extraction/ml -j 24 -build-dir src/ocaml-output/_build -I src/prettyprint/ml -I src/tactics/ml -I ulib/ml -I ulib/ml/compiler -use-ocamlfind main.native
+ ocamlfind ocamldep -package compiler-libs -package compiler-libs.common -package dynlink -package pprint -package yojson -package batteries -package zarith -modules src/ocaml-output/FStar_Main.ml > src/ocaml-output/FStar_Main.ml.depends
File "src/ocaml-output/FStar_Main.ml", line 258, characters 3-4:
Error: Syntax error
Command exited with code 2.
```

**Comment by cpitclaudel** [comment]
> I haven't gotten to the bottom of why this changed.

Could it be the recent fix on the F* side that turned some `let` type-annotations into ascriptions? (cc @kyoDralliam)

**Comment by mtzguido** [comment]
That should do it.

**Comment by tchajed** [comment]
@beurdouche could you also update CHANGES.md and `src/extraction/ml/README`?

**Comment by beurdouche** [comment]
Will do.

**Pull request merged**
