### PR TITLE
Darrenge f star nightly run make files

### PR DESCRIPTION
**Pull request by darrenge**
Everything is passing on Linux CI and Windows CI runs. The Linux Nightly is not passing through the agents because the docker containers for the agents have not been updated to the blessed docker scripts yet. However, I got the Nightly Running on FStar5 which was created by the blessed docker container.  This change was in 3 MakeFiles. ulib and the main make file (in src) straight forward and no issues. The Makefile in examples/low-level/crypto had more issues due to the split line calls in the VERIFY= section. I was trying to remove tests for Linux only run (run them on Windows run though). Reading up on GNU split lines, you will run into troubles using ifeq in the middle of the split lines. I literally spent day(s) on trying to get it to work for Windows only but after weighing time spent and value, decided to just comment out those hand full of tests. When these tests get fixed or updated, then they can be added into the mix. The important part of this check in is to get the builds all green and go from there.

### CODE REVIEW

**Comment by sishtiaq** [comment]
Hi Darren, If you are commenting-out calls to tests, can you file Issues to bring them back? Then we'll remember to do the work!

**Comment by darrenge** [comment]
Good call Samin ... filed as #832.

**Comment by msprotz** [comment]
Hi Darren, thanks for looking into this and identifying the failing tests!

Can you elaborate why the tests are failing, i.e. what is the exact error?
- if this is a ENOMEM error, as I think we observed before, we ought to run make -j 8 instead of make -j 24, because having 24 F* verification jobs in parallel exhausts the docker container's memory -- it may be as simple as this
- if this is something else, then I'd like to understand what exactly is different between the two environments. It used to work before, when we had the old container, so perhaps this is fixable.

Thanks!

Jonathan

**Comment by darrenge** [comment]
Good point regarding getting more error information to help with fixing these and getting them into the build. If possible, I would like to get these make file changes integrated and we can follow up getting them fixed by having #832 as the tracking issue. Working with the Nightly run is time consuming and I would like to prioritize that accordingly.

**Comment by msprotz** [comment]
Understood. The point of the Linux nightly run is to regenerate hints, and to verify all the files that the windows build doesn't verify because they take too long -- if we disable them, then the diminishes the value of the nightly run.

Can you point me to a log with the failures, and/or give me instructions on how to try this out myself? It may be that the errors we're encountering can be easily remedied.

Thanks,

Jonathan

**Comment by darrenge** [comment]
Totally agree - the end goal is to do all of that. We talked in the meeting last Wed that we wanted to get the build into a green state and then build up from that known state. I will work on it today and either get you the log files or update issue #832.  As an FYI ... we still have CI issue #35 open where the agent is not set up with the new docker (Irina is continuing that work there).

**Comment by msprotz** [comment]
Sure -- I'm happy to merge this, it just seemed like a good sanity check to at least know the error message before blindly disabling tests :).

**Comment by darrenge** [comment]
Thanks for the sanity check. My first pass of this task was to get the build green by looking at "what" was failing. For me to go through the FStar tests and figure out "why" is a different pass.

**Pull request merged**
