### PR TITLE
Add a verified UInt128 library

### PR DESCRIPTION
**Pull request by tchajed**
Replaces UInt128.fst generated from UIntN.fst, whose implementation was provided by kremlin.

Only applies to platforms without a `uint128_t` type (notably MSVC and CompCert).

(replacement for #1098 from `FStar/tchajed_uint128` rather than a fork)

### CODE REVIEW

**Comment by msprotz** [comment]
The status of this pull request is as follows:
- I performed the required changes in KreMLin and hacl_star, on the `using_tejs_uint128` branches. The hacl-star branch is based off of `migrating_sts_bis`.
- The trio master/master/migrating_sts_bis for F*/KreMLin/HACL* was extracting before. It still extracts with tchajed_uint128/using_tejs_uint128/using_tejs_uint128 so we should merge each of these branches into their respective base branch.
- We should do this once we get a green on F* verification.

**Comment by msprotz** [comment]
Note: since `make extract-c` no longer compiles anything in `code` (and since `secure_api` never worked with MSVC), I don't have any simple way of testing that the resulting code compiles...

**Comment by msprotz** [comment]
Thanks Tej!

**Comment by prosecco** [comment]
Looks good. Can someone (Jonathan? JK?) rerun the performance tests?

**Comment by msprotz** [comment]
This would have to be for CompCert, right? I don't think we ran performance benchmarks for MSVC, and all other targets (clang, gcc) use natively-implemented uint128's.

**Pull request merged**
