### PR TITLE
Tentative fix #1803 (Incorrect handling of machine signed integers)

### LINKED ISSUE #1803: Incorrect handling of machine signed integers
We never really used signed machine integers before. Now HACL* is adding support for them, and here comes a new bug report from Paul Zimmermann.

```
Hi,

with Félix Breton (in cc) we get the following behaviour:

   module Bug

   open FStar.HyperStack.IO

   module I32 = FStar.Int32

   let main () =
       if (I32.((-1l) <^ 0l)) then print_string "correct\n" else print_string "wrong\n";
       0

This prints "wrong", and was compiled with:

bug-ocaml: out Bug.fst
        $(FSTAR) $(FSTAR_DEFAULT_ARGS) --lax --odir out --codegen OCaml Bug.fst
        echo "let _ = main ()" >> out/Bug.ml
        $(OCAMLOPT) -I $(FSTAR_HOME)/ulib/ml -I out out/Bug.ml -o out/Bug
        out/Bug

It seems the number -1l is converted to 2^32-1 = 4294967295, and not to -1 as
expected.

We use the following version:

$ /localdisk/zimmerma/FStar/bin/fstar.exe --version
F* 0.9.7.0-alpha1
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=<not set>
commit=745b7a747ac2724484452e06669e738dd86fc02a (dirty)

(This probably worked in an earlier version of Fstar.)

Félix and Paul
```

Probably worth doing another pass over the normalizer, and our usage of bigintegers via zarith.

### PR DESCRIPTION
**Pull request by catalin-hritcu**
This is a patch for #1803 received via Karthik from Paul Zimmermann.

### CODE REVIEW

**Comment by catalin-hritcu** [comment]
Added a regression test to make sure this doesn't reappear. If the fst file was able to exit with an error code it would be better though, since then we could just add this to `SHOULD_EXTRACT_CLOSED` and not need a special make target. @victor-dumitrescu Any ideas how to do this?

**Comment by mtzguido** [comment]
I still see some weirdness even with this patch, see the following two examples and comments:
```fstar
module Bug

open FStar.HyperStack.IO

module I32 = FStar.Int32
open FStar.Int32

let main () =
    let pow31 = (I32.shift_left 1l 31ul) +^ 1l in
    print_string (I32.to_string pow31 ^ "\n"); (* prints "-2147483647" *)
    if (0l <^ pow31) then print_string "wrong\n" else print_string "correct\n"; (* prints "wrong" *)
    0
```
^ Printed number was negative, but comparison says it's positive.
```fstar
module Bug

open FStar.HyperStack.IO

module I32 = FStar.Int32
open FStar.Int32

let main () =
    let pow31 = (I32.shift_left 1l 31ul) +^ (I32.shift_left 1l 31ul) in
    print_string (I32.to_string pow31 ^ "\n"); (* prints "0" *)
    if (0l <^ pow31) then print_string "wrong\n" else print_string "correct\n"; (* prints "wrong" *)
    0
```
^ Printed 0, correctly because of wrapping (which is the intended behaviour, yes?), but comparison says it's positive. I guess this can be fixed by adding more `cmod` calls, but in any case:

Why is this defining `type int32 = int`, which are OCaml ints? Wouldn't this fail badly on a 32-bit machines where OCaml ints are effectively 31 bits? I'm not familiar with this code at all, so perhaps I'm saying something stupid (please tell me if so).

And why is it not simply using the Int32 module that OCaml provides?

**Comment by msprotz** [comment]
`type int32 = int` is a historical choice that no longer needs to be; if I recall correctly, JK needed fast int32s without boxing, in order to enable decently fast arithmetic when he extracted the precursor of HACL* to OCaml, back when there wasn't a C backend

this has caused repeated problems in the past, including having to maintain a different set of implementations in `ulib/ml/32bit` -- this seems to indicate that we ought to switch *all* the machine integers in OCaml to the `stdint` package, for widths that are not offered natively by OCaml

**Comment by catalin-hritcu** [comment]
Since Paul's patch doesn't seem enough to fix this library, I think it would be best if someone else takes this on, since it's too much for me. Guido maybe?

**Comment by mtzguido** [comment]
Thanks Jonathan, this is making sense now :). Perhaps we could chat about it in the call today? I played before with using the Int32 from OCaml's stdlib and it seemed to work, and it should be easy to use `stdint` instead. Perhaps even automatically generating them.

Though what about Int63 and UInt128? The former does not appear in `stdint`, and the latter doesn't seem to have an ML implementation?

**Comment by msprotz** [comment]
I think moving all the machine integers to stdint would be a great fix, especially since Catalin recently again struggled with a 32-bit build which requires some manual tweaks.

Please note that what I'm suggesting is slightly more ambitious.
- For UInt32: use `stdint`, on the basis that `int` in OCaml is sometimes too small to hold uint32
- For UInt64: no-op (already uses stdint)
- For Int32/Int64: use Int32 / Int64 from OCaml stdlib, or stdint for uniformity (easier?)
- For {U,}Int{8,16}: no strong opinion, I would argue to use stdint for uniformity, too

Now regarding the remaining ones:
- Int63 / Int31 : I think these are antediluvian artifacts from when JK was extractly his crypto library to OCaml; let's remove them; if they're used somewhere, let's fix it
- UInt128: the .fst is extracted for it (it implements uint128 as a pair of uint64), both in C and ML (in C, we occasionally discard this .fst in favor of built-in compiler types)
- we'll need Int128 too because @s-zanella is adding it; no sure how it plays out with the changes proposed in this pull request.

Maybe int128 should be, just like uint128, implemented in F* with kremlin support for bypassing the extracted code and using `__int128` for compilers that support this type.

**Comment by mtzguido** [comment]
That sounds good Jonathan, thanks a lot. I can take a stab at all this early next week (unless this is more urgent, @catalin-hritcu? If so I can try to get it done this week).

**Comment by msprotz** [comment]
Note that since all the modules share an identical interface save for their type, it might be possible to write FStar_UIntX.ml once as a functor, and instantiate it in each module.

**Comment by mtzguido** [comment]
Oh, nice idea, thanks, I was thinking of generating the ML files via some script, but that sounds better if it can work.

**Comment by catalin-hritcu** [comment]
Nothing urgent from my side

**Comment by s-zanella** [comment]
Can we agree on a plan to fix this? It seems we converged towards:

- Remove `FStar.{U}Int31` and `FStar.{U}Int63`.
- Implement all other signed and unsigned machine sizes except `UInt128` and `Int128` using [ocaml-stdint](https://github.com/andrenth/ocaml-stdint). 
- Extract the verified implementations of `FStar.Int128` and `FStar.UInt128` from F*.

Let's do this as a first step. Alternatively, we could provide ocaml-stdint implementations of `FStar.Int128` and `FStar.UInt128`. The only caveat is that this might not work properly on 32-bit platforms (although support seems to have improved and the ocaml-stdint README might be just outdated). On 64-bit platforms ocaml-stdint uses a C backend and `___int128` and `___uint128` when available, same as KreMLin with `--fbuiltin-uint128`.

**Comment by mtzguido** [comment]
I'm quite close to finishing this, it's taking a while since some realized ML files need a lot of rewriting (e.g. `FStar_Bytes` which is assuming that `u32 = int` in many places). Will make a PR soon, sorry for the delay.

**Comment by mtzguido** [comment]
See #1850, closing this one in favor of discussing there.

**Pull request closed without merging**
