### PR TITLE
tutorial: Clean up whitespace

### PR DESCRIPTION
**Pull request by tchajed**
Standardized on unix-style line endings (LF) and removed all trailing
whitespace.

I don't know if this is a good idea, and it's probably especially bad for me to
commit this since it messes with git blame. However, the mixed line endings are
really hard to work with.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
I'm not sure this is worth the damage to `git blame` — what problems do you run into when editing this file?

**Comment by msprotz** [comment]
`git blame -w` ignores whitespace, just like `git diff`... I'm in favor of the cleanup.

**Comment by msprotz** [comment]
We decided a while ago to switch all of our text files to LF, except for the visual studio project .sln file. The Madoko tutorial should follow the same policy, for consistency.

**Comment by msprotz** [comment]
Pushed. Thanks for pointing this out.

**Pull request closed without merging**
