### PR TITLE
Fixing typeclass arguments (and ~~removing~~ keeping syntax for array literals)

### PR DESCRIPTION
**Pull request by mtzguido**
This makes typeclass arguments work more uniformly. They were previously only parsed in patterns for letbidings (so `let f #a [| deq a |]`, etc) but not in arrow types nor `val` declarations.

This PR makes them work more uniformly, but requires removing the syntax for array literals, which conflicts with this one (`[| a1; ...; an |]`). We can of course change either syntax instead of just removing the array one, but since FStar.Array is in ulib/legacy, maybe we could just deprecate its syntax?

No strong opinion though, I would be fine with changing the syntax for tc args.

cc @msprotz @denismerigoux

### CODE REVIEW

**Comment by msprotz** [comment]
I am fine with deprecating the array literal syntax, especially since this is no longer considered a prime module and no longer lives in ulib.

**Comment by denismerigoux** [comment]
Thanks @mtzguido ! I didn't know you could use the OCaml-like syntax in F* to write arrays, I've never used them.

**Comment by mtzguido** [comment]
So we chatted today about this in the meeting. Arrays are indeed deprecated, but we were worried about closing the door on some possible future implementation-- it would be nice to use OCaml syntax too if we had them in the future.

How about we change typeclass arguments from `[| ... |]` to `{| ... |}`?

cc @nikswamy @aseemr

**Comment by mtzguido** [comment]
I've updated this PR to use braces for tcargs.

**Pull request merged**
