### PR TITLE
Js_of_OCaml support

### PR DESCRIPTION
**Pull request by cpitclaudel**
Hi there,

This PR has most of the changes needed to run F* on the web.

To understand the performance notes below, it helps to keep the following in mind: F*'s run time is split between 3 things: dependency loading, lax type-checking, and calls to the SMT solver.  Depending on the example, any of these three can dominate. Additionally, JS performance is fairly different from native: the JS code is compiled from bytecode, and string operations and exceptions are much costlier (and, in certain cases, a change is beneficial in JS but detrimental in native; I haven't included these here).

The commits fall into multiple categories:

* Compatibility: commits that reimplement some features using primitives that work in js_of_ocaml (jsoo).  This means replacing some uses of regexps, using Sys.getcwd and Sys.readdir instead of Unix.readdir, using open_out instead of BatFile.with_file_out, etc.

* Refactorings: commits that isolate entry points for the JS code (for example, splitting main into a workhorse and a wrapper that calls Sys.exit)

* Performance: commits that make the JS code faster, without adversely affecting native code.  This is the result of plenty of benchmarking to find hotspots on the JS side, and confirming the improvement on the native side.
    - Getting rid of many exceptions used for control flow in libraries makes the code usable (at first I rewrote some of the batteries functions, but @gasche was very helpful and actually removed many exceptions upstream, allowing me to revert some of the changes).
    - Making sure that all SMT captions fit on line to save time on splitlines speeds up SMT encoding by ~12%.
    - Caching dependency graphs speeds up dependency loading by ~1-5%.
    - Rewriting `replace_char` speeds it up 10-fold, speeding up SMT encoding by 13%.
    - Improving lookup_binding speeds up dependency loading by 8%.
    - Using `Z.of_int` for small constants instead of `Z.of_string` saves about 2% (int to bigint conversions are roughly 5 times faster than string to bigint ones in OCaml).

  In JS, with `--cache_checked_modules`, the sum of all these changes yields a fairly consistent 10% to 30% overall speedup depending on the example.

  On the native side, with `--cache_checked_modules`, `open FStar.Tactics` goes down from 2.4s to 1.8s (-21%) and `fstar stlc.fst` doesn't change much (~3% improvement).

* Other changes: these are small fixes.

Here's the detailed breakdown:

Compatibility
85b0027 * jsoo: Rewrite a simple use of Str.regexp in parse_string
e146b73 * jsoo: Use open_{in,out} instead of BatFile.with_{in,out}put_file

Refactorings
cdb32b0 * jsoo: Make it possible to override the options passed to Z3
c04552c * jsoo: Refactor Main to make it easier to call the relevant parts from JS
0984a65 * jsoo: Move hook assignments to a function that fstar.js can call
d8ebb9f * smtencoding: Simplify the Z3 interface
7505ffc * jsoo: Add an Exit exception in FStar.Main

Performance
a1e3830 * util: Remove a few more uses of Not_Found
adac540 * util, smtencoding: Speed up psmap_find_map and its caller
74f8c36 * smtencoding: Speed up lookup_binding
885013f * parser: Let F*.js supply a cache of precomputed dependencies
81c6225 * smtencoding: Make sure that all captions fit on one line
46683cd * util: Make replace_char faster
9b82450 * jsoo: Revert tryFind, find, etc (BatList 2.8 doesn't use exceptions)
7edacbb * jsoo: Rewrite tryFind, find, and try_find to not use exceptions

Other
bb98719 * tests: Make it easier to run interactive tests with a different F*
4e5400e * build: Add 'PKG ulex' to .merlin
1c62a8b * typechecker: Remove a dead function
ce66a8d * ide: Add a query ID to messages
b3f6d78 * dmff: Fix an incorrect use of format ("%b" instead of "%s")
9f2316d * jsoo: improve the error message in js_repl_init_opts
61c6976 * jsoo: Fix implementation of js_repl_init_opts
2cb1888 * jsoo: Further adjustments to FStar.Interactive.js
1675253 * jsoo: Refactor FStar.Interactive
fed9e82 * Small cleanup in FStar_GetOpt.ml and getopt.fs

### CODE REVIEW

**Comment by nikswamy** [comment]
Hi Clement, 

Thanks for all of this work!

About this part: "plus one significant tweak: reading checked modules is now on by default"

From this morning's meeting my understanding was that this results in build breakages and would not be included in this round of patches. Did I misunderstand?

-Nik

**Comment by nikswamy** [comment]
Also, this link seems to be broken now:

https://github.com/FStarLang/FStar/pull/1434/files/12135706d0b8a04e1fe401422abbaf23615250d2

**Comment by cpitclaudel** [comment]
Yes, rebasing broke the links. I'll update them.
I've already taken out the checked files patch.

**Comment by cpitclaudel** [comment]
Done, I've updated the links

**Pull request merged**
