### PR TITLE
Fix binary packages, push them to GitHub Releases

### PR DESCRIPTION
**Pull request by tahina-pro**
# Motivation
Since #2267 , CI has failed to build (Linux) binary packages for F*:
* The `.checked` files for the standard library are not part of the binary package, so some tests have to rebuild it. There, some modules such as `FStar.Math.Lemmas` fail to verify because they need to be verified with different (Z3) parameters than the rest of the library. So, the standard library needs to be reverified before testing.
* A straightforward solution would be to include the `*.checked` files for the standard library into the binary package. However, this would make it grow beyond 200 MB, which is too much to upload to GitHub FStarLang/binaries. ~So, we need to ask the user to verify the standard library themselves.~ We will finally use GitHub releases, cf. https://github.com/FStarLang/FStar/pull/2275#issuecomment-850041902
* However, with the `*.cm*` files for the standard library (packages `fstarlib` , `fstar-tactics-lib` and `fstar-compiler-lib`) not part of the binary package, trying to verify the Steel standard library makes F* segfault. (Cf. #2209.) Thus, we need to compile those packages and include them in the binary package.

# This solution
To solve these two issues, this PR:
* Builds and includes the OCaml `*.cm*` files for the `fstarlib`, `fstar-tactics-lib` and `fstar-compiler-lib` into the binary package.
* Reverifies `ulib` and includes their .checked files into the binary package.
* Proposes a new Dockerfile, `.docker/package.Dockerfile`, to test the binary package on Linux with guaranteed isolation, in the sense that the Dockerfile contains the following several disjoint subimages:
  + an image with all opam dependencies and build-only dependencies and the F* sources to build the binary package
  + an image with only the freshly built F* binary package and the opam dependencies of `fstarlib`, `fstar-tactics-lib` and `fstar-compiler-lib` to test the binary package for compilation of OCaml code generated by F*
  + another such image, but disjoint to test rebuilding `fstarlib` and `fstar-tactics-lib`
  + a no-OCaml image to test the freshly built binary package without OCaml

  Although not used by CI yet, I claim that this Dockerfile may be a viable alternative to `.scripts/process_build.sh` on Linux.
* Accordingly updates `INSTALL.md` with new usage instructions for the binary package: we now no longer ask the user to verify ulib themselves or recompile `fstarlib` or `fstar-tactics-lib`. (`fstar-compiler-lib` cannot be rebuilt with the binary package alone, since it needs the F* sources.)
* ~Bumps the F* version number to 0.9.8.0-dev to account for those new instructions in a "before/after" fashion.~ The version number for packages will now use the YYYY.MM.DD format

With this PR, I successfully produced, tested and uploaded a F* binary package for Linux: https://github.com/FStarLang/binaries/blob/master/weekly/fstar_202104220032_13e688dda1_Linux_x86_64.tar.gz

### CODE REVIEW

**Comment by tahina-pro** [comment]
Based on this PR, I also managed to build, test and upload a [Windows binary package](https://github.com/FStarLang/binaries/blob/master/weekly/fstar_202104211915_13e688dda1_Windows_x64.zip) (using the existing `.scripts/process_build.sh`, given Docker Windows images with Cygwin have no longer been working since moby/moby#41058)

**Comment by mateuszbujalski** [comment]
Would it make sense to produce an F* nuget package from a binary package now that the windows build works again? I've been doing this for my own purposes and it makes it really easy to start using F* as part of a bigger F# project (you just reference a nuget and add fst(i) files to your project). 

I have some powershell scripts for this but I would be happy to rework them so that they fit into your CI pipeline if you think it's worth doing.

**Comment by tahina-pro** [comment]
Thank you @mateuszbujalski for your proposal. At this point I would suggest to open a separate pull request (or issue) to discuss the specific topic of releasing a NuGet package for F*. Since I believe none of us among F* developers is really familiar with NuGet packages, we would welcome more detailed explanations there. Thank you in advance!

**Comment by mateuszbujalski** [comment]
@tahina-pro Sure, I didn't mean doing it as part of this PR obviously :) I'll open an issue and describe my proposal in more detail there. 
Thanks a lot for fixing the weekly binary packages for windows! :)

**Comment by tahina-pro** [comment]
After discussions with @nikswamy , @aseemr and others, we finally decided to include the .checked files of the standard library into the binary packages, so that they are ready to use with no further installation step for the user.

This will solve #2068: ulib will no longer be reverified as part of tests/ or examples/.

As a consequence, due to size issues, we can no longer push F* binary packages to FStarLang/binaries. We will use GitHub Releases instead. I changed `.scripts/process_build.sh` accordingly and I successfully tested it on Windows; I also added a Dockerized test via `.scripts/process_build_linux_docker.sh` for Linux, which I also successfully tested. With both of those scripts, I managed to automatically [push a release on my F* fork](https://github.com/tahina-pro/FStar/releases/tag/v2021.05.27).   So I plan to adapt CI to run those two scripts automatically very soon.

The automated release process is based on [Satsuki](https://pypi.org/project/satsuki/), which is a Python library to use the GitHub API via command line. To avoid installation/CI issues, I Dockerized that step with a platform-independent Dockerfile at `.docker/release.Dockerfile`. This is the same approach as the one I chose for EverParse releases.

**Comment by tahina-pro** [comment]
Since we are going to push weekly packages to GitHub Releases, we will finally switch F* version numbers to YYYY.MM.DD instead of 0.x.y.z. However, I have not reflected that in the version.txt file. In practice, when building a binary package, I automatically generate a tag (if not already there) and temporarily overwrite the contents of version.txt with that version number, which is then picked up by `make package`. However, I do not push that modified version.txt to master, for two reasons mainly related to CI:
* `master` is protected against direct writes, so I would need to go through a separate CI branch through several steps just to merge that single file
* GitHub personal authentication tokens are enough to push releases via Satsuki, but if I were to push a change to version.txt, then I would need another authentication method, such as a SSH key.

**Comment by tahina-pro** [comment]
I finally managed to [automatically push a GitHub release](https://github.com/FStarLang/FStar/releases/tag/v2021.05.28) with both Linux and Windows binary packages, all through a CI task.

**Comment by tahina-pro** [comment]
At this point, none of those binary packages have any html documentation included, since I am no longer running madoko to generate them.

**Comment by nikswamy** [comment]
that's great ... Thanks Tahina!

Did you do the Linux package from an Azure VM finally?

**Comment by tahina-pro** [comment]
I tried, but I failed because such an Azure VM did not have enough memory. Instead, I pushed change 38d014d19696306328daba02f023bc9c35065185 to accommodate older versions of `git` such as the one on our current CI machine.

**Comment by tahina-pro** [comment]
Finally, from now on, the version number will be updated every night at the same time as hints and the snapshot, and a release is pushed with the version number recorded in version.txt.

**Pull request merged**
