### PR TITLE
hash table library

### PR DESCRIPTION
**Pull request by meganfrisella**
also added SizeT.safe_add, which checks for overflow

### CODE REVIEW

**Comment by meganfrisella** [comment]
@mtzguido @R1kM Here's a small addition to SizeT: `SizeT.Util.safe_add`, which checks for overflow before adding. Any thoughts on a more efficient way to do this?

**Comment by mtzguido** [comment]
Hi Megan, this looks fine to me. Just two things:
- In `if x <^ size_t_max && y <^ size_t_max -^ x` I think you can use `<=^` in both places?
- It may be good to define variants which depend on `fits_u32` and `fits_u64` but allow for a higher bound. I think just adding `fits_u32` to the requires and changing the max for `2^32-1` would do it.

As for improving it, I think ideally the check that `x <=^ max` would not be there, since it must be morally true as `x` is of type `SizeT`, but of course it may be that it's greater than `0xffff`. But I see that `v` guarantees that the result `fits`. Maybe if this module exposed a `size_t_max` we could just check that `y <=^ size_t_max - x`?

(Also watching a talk yesterday I was reminded that `Tomb` may be a better name than `Zombie` :) )

**Comment by mtzguido** [comment]
This is more or less what I had in mind:
```diff
From c651a5a3e75d2dd120e2e20dcb11ac08840df499 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Guido=20Mart=C3=ADnez?= <mtzguido@gmail.com>
Date: Sun, 6 Aug 2023 11:19:23 -0700
Subject: [PATCH] SizeT: introduce an explicit size_t_max instead of the ghost
 bound

And simplify FStar.SizeT.Util.safe_add
---
 ulib/FStar.SizeT.Util.fst |  3 +--
 ulib/FStar.SizeT.fst      | 25 ++++++++++++++-----------
 ulib/FStar.SizeT.fsti     |  4 ++++
 3 files changed, 19 insertions(+), 13 deletions(-)

diff --git a/ulib/FStar.SizeT.Util.fst b/ulib/FStar.SizeT.Util.fst
index 378b06cc9b..87f6c016f3 100644
--- a/ulib/FStar.SizeT.Util.fst
+++ b/ulib/FStar.SizeT.Util.fst
@@ -2,9 +2,8 @@ module FStar.SizeT.Util
 
 open FStar.SizeT
 
-let size_t_max = 0xffffsz //This is a safe platform-independent upper bound for size_t
-
 let safe_add (x y:t) : o:option t { Some? o ==> v (Some?.v o) == v x + v y } =
-  if x <^ size_t_max && y <^ size_t_max -^ x
+  if y <=^ size_t_max -^ x
   then Some (x +^ y)
   else None
\ No newline at end of file
diff --git a/ulib/FStar.SizeT.fst b/ulib/FStar.SizeT.fst
index 7cb7ba1b66..e59c0a1855 100644
--- a/ulib/FStar.SizeT.fst
+++ b/ulib/FStar.SizeT.fst
@@ -5,34 +5,37 @@ module I64 = FStar.Int64
 (* This is only intended as a model, but will be extracted natively by Krml
    with the correct C semantics *)
 
-(* We assume the existence of some lower bound on the size,
-   where the bound is at least 2^16 *)
+(* __max represents the largest posible size_t value, as a U64. This
+corresponds to SIZE_MAX in C, defined in limits.h. We do assume that a
+size_t can hold any U16 (see comment on fsti), however, so we add the
+refinement that __max >= 2^16 - 1. *)
 assume
-val bound : x:erased nat { x >= pow2 16 }
+val __max : x:U64.t{U64.v x >= pow2 16 - 1}
 
-let t = x:U64.t { U64.v x < bound }
+(* size_t is modeled as a U64 below the max *)
+let t = x:U64.t { U64.v x <= U64.v __max }
 
-let fits x =
-  FStar.UInt.fits x U64.n == true /\
-  x < bound
+let size_t_max = __max
+
+let fits x = x <= U64.v __max
 
 let fits_at_least_16 _ = ()
 
 let v x =
   U64.v x
 
+let fits_iff_under_max x = ()
+
 let uint_to_t x =
   U64.uint_to_t x
 
 let size_v_inj (x: t) = ()
 let size_uint_to_t_inj (x: nat) = ()
 
-
-/// These two predicates are only used for modeling purposes, and their definitions must
 /// remain abstract to ensure they can only be introduced through a static assert.
 /// We simply define them as True here
-let fits_u32 = (reveal bound >= pow2 32) == true
-let fits_u64 = (reveal bound == pow2 64)
+let fits_u32 = (U64.v __max + 1 >= pow2 32)
+let fits_u64 = (U64.v __max + 1 >= pow2 64)
 
 let fits_u64_implies_fits_32 ()
   : Lemma
diff --git a/ulib/FStar.SizeT.fsti b/ulib/FStar.SizeT.fsti
index 6dfb81a44b..2413456fa1 100644
--- a/ulib/FStar.SizeT.fsti
+++ b/ulib/FStar.SizeT.fsti
@@ -8,6 +8,8 @@ module U64 = FStar.UInt64
 
 val t : eqtype
 
+val size_t_max : t
+
 val fits (x: nat) : Tot prop
 
 /// According to the C standard, "the bit width of t is not less than 16 since c99"
@@ -24,6 +26,8 @@ val v (x: t) : Pure nat
   (requires True)
   (ensures (fun y -> fits y))
 
+val fits_iff_under_max : x:nat -> Lemma (fits x <==> x <= v size_t_max) [SMTPat (fits x)]
+
 /// We therefore offer two functions to create a t value.
 /// Any value that fits in a uint_16 can be cast directly to t
 /// Any value that might not fit in a uint_16 needs to satisfy the `fits_u32`
-- 
2.41.0.338.g4cba96e0cc

```
It gets rid of the ghost bound in SizeT and introduces an explicit size_t_max (which should be extracted to `SIZE_MAX` in C) instead which can be used for comparison. This seems fine to me, but not sure whether I'm breaking some design decision. Maybe @R1kM or @msprotz know?

**Comment by nikswamy** [comment]
We ended up mering this into Pulse, rather than here. Thanks @meganfrisella

**Pull request closed without merging**
