### PR TITLE
Canonize arrow by default when packing a term

### LINKED ISSUE #2596: SMTPats in currified Lemmas are not encoded to SMT
Consider the following minimal code snippet (done with @W95Psp  and @TWal)
```fstar
assume val p: int -> int -> prop

assume val test: x:int -> y:int -> Lemma (p x y) [SMTPat (p x y)]
assume val test2: x:int -> Tot (y:int -> Lemma (p x y) [SMTPat (p x y)])
```

While these two functions should conceptually be the same, they lead to different behaviours when trying to use them. In particular, we observed that when only having `test2` in the context, the SMTPat was not triggered, not allowing the automatic verification of `p x y`, while the behaviour with `test` was the expected one.

When looking at the SMT encodings of both these functions, the encoding of `test` is very concise (41 lines of smt2) and intuitive and includes the pattern annotation for `SMTPat (p x y)`, while the encoding for `test2` is much longer (299 lines), includes a lot of extra information and patterns (my possibly incorrect understanding is that it is used to show that the partial application is well-typed), and does not seem to have the pattern annotation corresponding to `SMTPat (p x y)`.

Should the SMT encodings of both these functions be similar, maybe through some canonicalization of the F* term before being encoded to SMT?

This situation occured when trying to generate this lemma using F*'s reflection facilities. The currently exposed term API `Tv_Arrow` (in FStar.Reflection.Data) does not allow to have multi-binder arrows, while the underlying term representation  `Tm_arrow` does. It thus currently does not seem possible to generate lemmas with SMTPats and multiple arguments using reflection in F*.

### PR DESCRIPTION
**Pull request by R1kM**
This PR changes the behaviour of `FStar.Tactics.pack` to canonize arrows by default instead of leaving them in a fully currified form. This solves the issues mentioned in the latter part of #2596, by allowing lemmas with SMTPats generated by reflection to be encoded as fully applied functions to Z3, thus encoding their pattern correctly.

This change is potentially breaking for modules using reflection, so this PR also adds a function `pack_currified` which does not perform canonization, thus retrieving the previous behaviour.

Fixes #2596

### CODE REVIEW

**Comment by aseemr** [comment]
Thanks @R1kM! The PR looks good to me. But I am thinking again the design choice of canonizing arrows by-default. There are some other design choices:

* Make the arrows in reflection syntax take multiple binders (as we do in FStar.Syntax.Syntax), we then don't need two APIs.
* Instead of changing the behavior of `pack`, have a `canonize:term -> term` reflection API. This would be slightly different from what is in the PR, e.g. `mk_arr` in the PR takes one binder at a time, and then canonize for every binder, instead, the flow would then be to build curried arrow all the way, and then canonize once on-demand.
* What about abstractions? Should they be canonized by default too? FStar.Syntax.Syntax keeps them flattened as well.

(If we do (1), (2) can then be implemented.)

The first point in my mind is some disconnect, if we think canonization always is the way to go, then why are we exposing curried form in the syntax.

I know we discussed some of it previously, but can we please discuss it again, this coming week perhaps? Thanks!

**Comment by R1kM** [comment]
Thanks @aseemr for the review! I think we discussed the first two points in the past.
If I remember correctly, the argument for avoiding the list of arguments was to avoid breaking changes.
For `canonize`, the conclusion was that, not wanting to canonize seemed to be the exception rather than the norm, hence we decided that the default behavior should be to canonize, while there would be an additional helper for the rare expert uses where it is needed.

I don't think we discussed 3) at all, I'm not sure what the differences in SMT encoding between the two would be, happy to discuss it further during the next meeting.

**Comment by nikswamy** [comment]
> If I remember correctly, the argument for avoiding the list of arguments was to avoid breaking changes.

Actually, I don't think this is the reason. 

I think the unary representation of abstractions and arrows in the reflection syntax is much easier to manipulate, particularly when doing proofs over the syntax of terms. Dealing with variadic representations everywhere is a really cumbersome.

**Comment by R1kM** [comment]
Good catch, thanks, I got confused with the French names for curried functions.

**Pull request merged**
