### PR TITLE
Fast-path for Syntax.Subst compress

### PR DESCRIPTION
**Pull request by ctk21**
This PR splits `compress` in Syntax.Subst into a fast-path and slow-path. The fast-path checks if the term is a `Tm_uvar` or `Tm_delayed` if it is not, then we know there is no further work and return immediately. The cost to this is that it makes the code a bit more brittle in that you need to update the fast-path if functions called by `compress` change to use more terms than `Tm_uvar` or `Tm_delayed`.

Several files in ulib are showing compress being a significantly hot function. I get the following benchmark results from the change. 
```
                  Old                               New
                  n       total   user    system    n       total   user    system
micro-benchmarks  61      59.99   55.96   3.809     61      57.71   53.56   3.858.
ocaml_extract     38      120.8   116.4   4.422     38      119.9   115.5   4.318.
ulib              208     399.9   379.3   19.94     208     357.7   337.2   19.82.
```

### CODE REVIEW

**Comment by aseemr** [comment]
Thanls @ctk21! The changes look fine to me. Similar warning comments on `try_read_memo`, `force_uvar`, and their auxiliary functions would be nice.

@nikswamy and @mtzguido should have a look too, as substitution code is a core functionality.

**Comment by msprotz** [comment]
I looked at this change and it seems fine by me. I suspect that the performance improvements would be even more noticeable on files like Vale.AESGCM which are notoriously substitution-heavy.

Nik and Guido are both at a summer school this week. Hopefully we can ping one of them to give a quick look at this, if you think @aseemr that it needs another pair of eyes.

**Comment by ctk21** [comment]
> Thanks @ctk21! The changes look fine to me. Similar warning comments on `try_read_memo`, `force_uvar`, and their auxiliary functions would be nice.

Thanks for the suggestion. I've added additional warnings around `try_read_memo` and `force_uvar`.

**Comment by mtzguido** [comment]
Also looks good to me! Doesn't seem to be a functional change and the improvements seem pretty good. Thanks!

**Comment by nikswamy** [comment]
That's an impressive speedup for a small, well-scoped change! Nice work!

Any explanations for why we think this causes such gains? The non-recursive fast path is eligible for inlining?

**Comment by ctk21** [comment]
Thanks, glad it's useful!

The gain doesn't look like it is from inlining; I don't see any entry point into `compress_slow` in the binary produced with 4.07.1 except from `compress`. I did try using flambda (an alternative more advanced OCaml inliner) on F* a couple of weeks ago and got a 1-2% improvement; it's possible this change may give flambda more opportunities.

The binary for `compress` with the fastpath becomes simple:
```
  c23e80:      mov    (%rax),%rbx
  c23e83:      test   $0x1,%bl
  c23e86:      jne    c23e9c <camlFStar_Syntax_Subst__compress_2969+0x1c>
  c23e88:      movzbq -0x8(%rbx),%rbx
  c23e8d:      add    $0xfffffffffffffff3,%rbx
  c23e91:      cmp    $0x1,%rbx
  c23e95:      ja     c23e9c <camlFStar_Syntax_Subst__compress_2969+0x1c>
  c23e97:      jmpq   c23df0 <camlFStar_Syntax_Subst__compress_slow_2959>
  c23e9c:      retq
```
However the `compress_slow` path (which is the old code) contains several function calls and checks.

The change is leading to gains because the function is very hot (called from a great deal of places) and when called there are a lot of instances where it is quick to determine that we don't need to do any work.

**Pull request merged**
