### PR TITLE
Steel effect: Assume requires clause when typechecking ensures

### LINKED ISSUE #2435: Steel with selectors: requires precondition not included in ensures postcondition block
Hello,
I noticed the following bug while using Steel with selectors, that can be demonstrated with the following minimal example, which contains a simple workaround.
```fstar
module Reqens

open Steel.Memory
open Steel.Effect.Atomic
open Steel.Effect
open Steel.Reference

[@@expect_failure]
let test (x: nat)
  : Steel nat
  emp (fun _ -> emp)
  (requires (fun _ -> x > 0))
  (ensures (fun _ r _ -> r = 1 / x))
  =
  return (1 / x)

let test (x: nat)
  : Steel nat
  emp (fun _ -> emp)
  (requires (fun _ -> x > 0))
  (ensures (fun _ r _ -> x > 0 /\ r = 1 / x))
  =
  return (1 / x)
```
Fixing this quite small bug would lead to even more concise specs. Thanks in advance!

### PR DESCRIPTION
**Pull request by R1kM**
Consider the following toy example, as reported by @cmovcc:
```fstar
let test (x: nat)
  : Steel nat
  emp (fun _ -> emp)
  (requires (fun _ -> x > 0))
  (ensures (fun _ r _ -> r = 1 / x))
  =
  return (1 / x)
  ```
While the requires clause is in the logical context when typechecking (and verifying) the body of the function, it is not when typechecking the ensures clause itself. Hence, 
```fstar
val test (x: nat)
  : Steel nat
  emp (fun _ -> emp)
  (requires (fun _ -> x > 0))
  (ensures (fun _ r _ -> r = 1 / x))
```
currently fails to typecheck, because the prover cannot determine that x <> 0 in the ensures clause.

This PR addresses this issue by adopting a similar technique as other existing pure and stateful effects: the type of the ensures clause (`Steel.Effect.Common.ens_t`) now assumes the validity of the requires clause on the initial state.

Most of the PR consists of propagating this change to the different Steel effect combinators.
There is also a minor tweak to the tactic in charge of rewriting frame equalities:
Because of the new refinement on the type of the initial `rmem` state, a refinement subtyping SMT goal is generated during the call to `rewrite_with_tactic`. Unfortunately, `rewrite_with_tactic` fails when goals are remaining instead of passing them to SMT. This should probably be fixed, but in the meantime, the generated SMT goal is taken care of in the `frame_vc_norm` tactic.

Fixes #2435

### CODE REVIEW

**Comment by R1kM** [comment]
This fix unfortunately comes with a memory blowup leading to examples/steel/Queue failing for instance with an OOM error on the CI machine

**Comment by mtzguido** [comment]
Steel is no longer in this repo (https://github.com/FStarLang/steel)

**Comment by mtzguido** [comment]
Sorry.. I was thinking these changes would have already been incorporated to the Steel repo, but it doesn't look like it? Should we "move" this PR to that repo?

**Comment by cmovcc** [comment]
Hi, thank you for your attention regarding the reopening.
I think we should not, this seems to be rather hard to fix. However, perhaps it would be nice to document it somewhere.
The workaround is to propagate manually the needed precondition so that the postcondition typechecks.
```fstar
let test (x: nat)
  : Steel nat
  emp (fun _ -> emp)
  (requires fun _ -> x > 0)
  (ensures fun _ r _ ->
    x > 0 /\
    r = 1 / x
  )
  =
  return (1 / x)
```

**Comment by R1kM** [comment]
I think it's safe to close this PR. The feature would have been useful, but the memory blowup was too big to justify it, especially on bigger projects where requires clauses could be quite complex.
As @cmovcc mentioned, duplicating the small parts of the requires that are needed to typecheck the ensures clause works, has been used extensively in other projects (e.g., StarMalloc).

**Pull request closed without merging**
