### PR TITLE
Add some lemmas to FStar.Math.Lemmas

### PR DESCRIPTION
**Pull request by Kachoc**
Those lemmas are necessary for the [Hacl blake incremental PR](https://github.com/project-everest/hacl-star/pull/332)

### CODE REVIEW

**Comment by Kachoc** [comment]
Please do not merge yet: I'm about to add another lemma

**Comment by mtzguido** [comment]
Thanks Son! May I suggest to prove `modulo_sub_lemma` in this way?
```fstar
let modulo_sub_lemma a b c =
  calc (==) {
    b;
    == { modulo_lemma b c }
    b % c;
    == { lemma_mod_twice b c }
    (b%c) % c;
    == { (* hyp *) }
    (b%c  + (a-b)%c) % c;
    == { modulo_distributivity b (a-b) c }
    (b+(a-b)) % c;
    == {}
    a % c;
  }
```
Also curious about the lemmas for addition and multiplication. Did you need them, or are you adding them for completeness? I think it's fine to have them, but I always found the SMT to automatically prove that even within very complex proofs, so I'd be interested in seeing an example where it doesn't.

**Comment by Kachoc** [comment]
Yes, if you come up with cleaner proofs, I'm fine with replacing my proofs with yours.
I actually happened to need the lemmas for addition and multiplication in the `son_blake` branch of HACL: for some reason, there are proofs which seemed to loop if I didn't call those lemmas (I have no idea what happened there).

**Comment by Kachoc** [comment]
Here, if you remove the call to `add_zero_right_is_same`, the proof loops: https://github.com/project-everest/hacl-star/blob/df6a4ddcba934454afbd0c5ae103018389537c3a/specs/lemmas/Spec.Hash.Incremental.fst#L271

**Comment by mtzguido** [comment]
Interesting! Maybe you somehow avoid a matching loop by explicitly invoking the lemma. The PR looks good to me; feel free to replace that proof or I can also do it later after merging. Thanks again!

**Comment by Kachoc** [comment]
@mtzguido  I updated the `modulo_sub_lemma` proof. As you said you are ok with the PR, can I merge it myself once the checks are completed?

**Comment by mtzguido** [comment]
Sure, go for it!

**Pull request merged**
