### PR TITLE
Implement queries discussed in 2017-04-17 chat

### PR DESCRIPTION
**Pull request by cpitclaudel**
This leverages the new JSON protocol (thanks @nikswamy for merging!) to implement a bunch of extra queries.

In order:

* `compute` reduces a term using the normalizer.  It requires exposing the `tc_decls` function from `Typechecker.Tc.fs` in `Typechecker.Tc.fsi`.  To parse the term passed by the user, it typechecks a declaration `let __dummy__ = <user input>`.  **Requested feedback:** Is this an acceptable way to parse and grab a term? And is the code below the right way to save and restore an environment? I expect it should, since it doesn't add definitions to the environment. **Future work**: Support more primitives in the reduction engine.

    ```
    let run_and_rewind st task =
      let env_mark = mark st.repl_env in
      let results = task st in
      let env = reset_mark env_mark in
      let st' = { st with repl_env = env } in
      (results, Inl st')
    ```

* `search` goes through the environment and find definitions that contain certain identifiers in their body, or certain strings in their names. **Requested feedback:** Is enumerating free variables acceptable to find symbols in a term's body? This sounded like an easy and pretty lightweight approach. **Future work:** pretty-print results with the document printer; support pattern-based searches (using the tactic engine to mactch); restrict searches to specific modules (easy: just allow wildcards in string keywords so people can write `FStar.*.append`).

* `lookup` is extended to allow clients to request a definition.

* `peek` is like `push`, but it automatically pops, even if pushing succeeds.  This makes Flycheck support possible.

* `describe-repl` gives info about the current REPL state (currently, only the list of module that the current buffer depends on).

None of these touch the type-checker.  The only change in ToSyntax.Env is the addition of the `syntax-only` flag for syntax checks.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Rebased and updated.

**Comment by nikswamy** [comment]
What's the intention behind "syntax only" pushes?

**Comment by cpitclaudel** [comment]
They make sense for `peek`s: you might want to only check syntax instead of doing lax checks in Flycheck, should lax checks be too slow.

**Comment by cpitclaudel** [comment]
Yay! Thanks for merging :)

**Pull request merged**
