### PR TITLE
Fix syntax-error column offsets (they were incorrectly 1-based)

### PR DESCRIPTION
**Pull request by cpitclaudel**

### CODE REVIEW

**Comment by msprotz** [comment]
I'm manually kicking off a build on my branch that contains, among others, this pull request. If everything is green, I'll merge everything at once.

**Comment by msprotz** [comment]
Clément, your pull request does not compile... 

```
File "src/parser/ml/FStar_Parser_ParseIt.ml", line 83, characters 44-45:
Error: Unbound value p
```

**Comment by cpitclaudel** [comment]
Sorry about this, my stash pop went wrong apparently :/ Can you try again?

**Comment by msprotz** [comment]
I merged your branch again but I got a conflict (I assume you rewrote the history and force-pushed). I manually fixed the conflict, since it was simple enough... let's see what CI says. Thanks!

**Comment by cpitclaudel** [comment]
> I assume you rewrote the history and force-pushed

Yup, I do that all the time for WIP branches.  Let me know if this is frowned upon in F* land :)

**Comment by msprotz** [comment]
I have a WIP branch where I'm trying to get a green on all the pending pull requests at once. If you rewrite history, I need to throw it away then re-merge everything. No big deal, but as far as I know, no one demands rebases.

**Comment by cpitclaudel** [comment]
Ok, got it :) I'll try to use merges.

**Comment by cpitclaudel** [comment]
Closing this; I'll work directly from a branch in the F* repo for simplicity :)

**Pull request closed without merging**
