### PR TITLE
WIP: Use SMT for reasoning about strings

### PR DESCRIPTION
**Pull request by A-Manning**
As it stands, F* cannot reason about string literals at all. The following lemmas will all fail:

```
let hello = "hello"
let world = "world"
let helloworld = strcat "hello" "world"

val length_hello: unit -> Lemma (strlen hello = 5)
let length_hello () = ()

val helloworld_literal: unit -> Lemma (helloworld = "helloworld")
let helloworld_literal () = ()
```
It is possible to reason about strings through Z3, which now includes [Z3Str3](https://sites.google.com/site/z3strsolver/). 
However, Z3's model of strings applies only to strings of ASCII characters.
Ideally, F*'s model of strings would correspond to F# / OCaml strings.

This PR, as-is, allows F* to reason about strings of ASCII characters through Z3. The primitive operations `strlen`, `at` and `strcat` are implemented. Other Z3Str3 primitives could potentially be added.

This PR will eventually be revised to include an SMT theory of strings that corresponds to F#/OCaml strings.
Any input regarding modelling strings in F* is welcome.

This PR means that F* can now prove things like
```
open FStar.String

let hello = "hello"
let world = "world"
let helloworld = strcat hello world

val test : unit -> Lemma ( helloworld == "helloworld" 
                           /\ strlen helloworld == 10 
                           /\ helloworld `at` 5 = "w"  )
let test () = ()
```

### CODE REVIEW

**Comment by catalin-hritcu** [comment]
@wintersteiger would you like to have a look at this?

**Comment by nikswamy** [comment]
This seems very useful! Thanks @A-Manning. Sorry for the extremely slow response. Do you have any updates in the meantime?

I need to do a more careful review, but a few high-level remarks:

1. Is it compatible with `Z3 version 4.5.1 - 64 bit - build hashcode 1f29cebd4df6`?

2. I would prefer to have a way to opt-in to this SMT encoding of strings, so as not to disturb existing code that may rely on strings being modeled abstractly in SMT.

**Comment by A-Manning** [comment]
@nikswamy Regarding your questions:

>Is it compatible with Z3 version 4.5.1 - 64 bit - build hashcode 1f29cebd4df6

Yes

> I would prefer to have a way to opt-in to this SMT encoding of strings, so as not to disturb existing code that may rely on strings being modeled abstractly in SMT.

Agreed, I can work on adding a switch for this. There's no rush though, I made the PR mostly for review - at some point I intend to revise this to use a custom z3 theory for strings that models F#/OCaml strings a bit better, or better yet to just model strings as char arrays if we can get a reasonable encoding for arrays working.

**Comment by nikswamy** [comment]
This seems quite old and not on our current queue of mergeable PRs. I am closing it for now ... if anyone wants to revive it, please re-open.

**Pull request closed without merging**
