### PR TITLE
Light syntax

### PR DESCRIPTION
**Pull request by auduchinok**
Considering this [example](http://prosecco.gforge.inria.fr/personal/hritcu/talks/fstar-sb-2015/03/slides03.html#sec-syntactic-pitfalls--nested-patterns) we believe that the F# light syntax can be helpful in situations like nested `match` expressions and can make code look prettier by removing redundant `in` or `;`. 
In F# this is done by implementing [LexFilter](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/LexFilter.fs) which modifies token stream by inserting new tokens and adding more grammar rules to distinguish situations where tokens were inserted. 

The LexFilter was copied from F# and modified to be compatible with F\*. This PR contains both F# and OCaml variants of LexFilter. I tried to make it bootstrapping from F# and extracting \*.ml files from \*.fst, but F\* couldn't parse some nested pattern-matching ([example](https://github.com/YaccConstructor/FStar/blob/light-syntax/src/parser/lexfilter.fs#L538)) so I decided to open this PR prior to fixing F\* parser there and eliminating duplication of LexFilter here.

Light syntax is used in a file only when `#light "on"` pragma is found so this PR doesn't break existing F\* code. However, LexFilter still should be modified for a better F* compatibility due to grammar/lexer differences from F#, so this PR is a kind of prototype that's supposed to be tested better and fixed where needed.

### CODE REVIEW

**Comment by nikswamy** [comment]
Very much in favor of light syntax if we can make it work well. Thanks!

**Comment by auduchinok** [comment]
Right now there're already working examples in [examples/light-syntax](https://github.com/YaccConstructor/FStar/tree/d06127b041b412ceae6a5c857a6b5f5c62027298/examples/light-syntax).

**Comment by msprotz** [comment]
This is nice and a pretty substantial pull request. Congrats on mastering the bootstrapping process and the intricacies of parsing w.r.t the F* weird bootstrap! In case you hit something complex, feel free to amend `src/parse/README`.

Side note: at this stage, and if we integrate this, I think we would _really_ need a pretty-printer and formatter to beautify F* source code ASAP. The source code of F* itself is a mess: there is no consistent indentation policy, a mix of tabs and spaces, sometimes indentation is at 3 characters, sometimes 5, and there's a massive abuse of `<|`. Adding new syntax features like this is certainly convenient, but I'm afraid the effects on the F* source code are going to be disastrous.

**Comment by auduchinok** [comment]
The light syntax is not enabled by default now, so there's enough time to decide how indentation should be done for F* and its standard libs.
A separate issue about indentation can be opened as well. In F# (at least for the light syntax) indentation using tabs is not allowed and 4 spaces are usually used (as a default for Visual Studio), so I would suggest picking it up.

**Comment by nikswamy** [comment]
@protz: Can you say more about what you consider to be an abuse of `<|`

Also, as @auduchinok says, if this is not the default, then migration should not be too painful, right?

**Comment by msprotz** [comment]
Mostly, the many occurrences of `e <| (...)` where the `<|` brings nothing, since the expression after it is already parenthesized.

One example is in `tc/rel.fs:2574` (I know the code is meant to be deleted one day, but it highlights several points in just a couple lines):

```
   then begin
    Util.print1 "Trying to solve carried problems: begin\n%s\nend\n"
   <| (g.deferred.carry |> List.map (fun (msg, x) -> Util.format4 "(At %s) %s\n%s\nguard is %s\n"
        (Range.string_of_range <| p_loc x) msg (prob_to_string env x) (Normalize.formula_norm_to_string env (p_guard x |> fst))) |> String.concat "\n")
```

- first occurrence of `<|` is superfluous (see `extraction/term.fs:672,676,531,838`, `parser/tosyntax.fs:758,1086`, `smtencoding/encode.fs:1423`, `smtencoding/errorReporting.fs:181`, `extraction/extractexp.fs:133,268,290,294,372`, and many more throughout the code) -- this may seem innocuous, but when I read that sort of code, I'm always double-checking because I think "there must be a reason why this operator is here"
- in general, there exist many occurrences of the right pipe operator that are useful (running something through `List.map`, then `List.split`, then something else), but in the example above, I see two issues:
  * the alternating of `<|` and `|>` completely breaks the flow of reading, and requires a larger mental effort to figure out what's going on -- I need to jump left-and-right: first, read `p_guard x`, then remember the precedence level of `|>` and run it through `fst`, then jump left to re-read the application node that starts at `Normalize.formula`, then all the way to the right with the outer series of `|>` that ends with `String.concat`, before jumping back to the very beginning of the code block to remember that this was fed to `print1` (a similar mental gymnastic is required if you read outside-in)
  * one has to know the associativity and precedence of `|>` and `<|` in order to understand what the code does; granted, this isn't much (the both left-associate are have a loose precedence), but that's one more bit of knowledge that the reader has to have.

I know parentheses are boring and require you to jump at the end of line to add the closing one, then move the cursor back to where you were, but anyone can figure out what's going on without knowing the intricacies of the F* parser, and any editor highlights matching parentheses -- not the case for `<|`. Custom operators make "groking" a piece of code a little bit harder, and light syntax will make the entry barrier even higher because now one will have to know the rules for light vs non-light.

Just to reiterate, I'm not against the light syntax; it's just that supporting two syntaxes is burning a lot of the complexity budget for the language, and if I had to choose, I'd vote in favor of a single syntax (even the light one, if there's a consensus that it's better -- I'm ready to admit that I'm biased due to my prior OCaml familiarity).

**Comment by nikswamy** [comment]
The use of `<|` and `|>` is very common in F# and is actually recommended style for F# in many cases since (especially `|>`) can provide better type inference results for F#.

I agree that the extra parenthesis sometimes makes this redundant, as in the case you point out above.

**Comment by auduchinok** [comment]
The branch was fixed and rebased onto the master. It's safe to merge it now.
There're a few syntax features that are not available yet but can be done in separate PRs, which is easier than rebasing onto all the changes in the master. The example below illustrates one of such features where F# allows operators to be placed before the block start column.
```fsharp
let x = 2
      + 1
```

**Comment by auduchinok** [comment]
Any news on this one?

**Comment by nikswamy** [comment]
@auduchinok 

We discussed the issue of whether or not to move to light syntax
at great length at a recent meeting---~20 of us discussing for
about 45 minutes.

Despite many in favor of light syntax, the conclusion was that we
should not move to light syntax now. The main concern was that adding
an alternate opt-in light syntax would only result in greater
non-uniformity of our code. We would prefer to have a single official
syntax.

Nevertheless, we are also aware that the current syntax has many
ambiguities that are pitfalls especially for new users as well as for
those more accustomed to F*. In particular, nested pattern matching
and if/then/else ending with semicolons are both routine sources of
confusion. To address this, we were all generally in favor of a
stricter, white-space sensitive variant of our existing syntax.

For example, the following would be considered syntax errors:

```
    if e
    then e1
    else e2; e3
```

```
    if e
    then e1
    else e2;
    	 e3
```

Since this suggests that e3 is part of the else branch. Instead, one
would have to write:

```
    if e
    then e1
    else e2;
    e3
```

Making clear that e3 is outside the control of the conditional expression.

Likewise,

```
	match e1 with
	| P1 -> e1
	  match e2 with
	  | Q1 -> e2
	| P2 -> e3
```

would be a syntax error, since it suggests that the branch `P2 -> e3`
is part of the outer match, when in fact it is part of the inner
one. As such, one would have to write:

```
	match e1 with
	| P1 -> e1
	  match e2 with
	  | Q1 -> e2
	  | P2 -> e3
```
	  
I suspect that your pull request could be adapted to enforce these
spacing conventions. Do you think it is feasible? Would it be
something we could interest you in pursuing? If so, I'd be happy to
work with you to specify the desired syntax precisely and to ensure
that any pull request you provide addressing this issue is promptly
and seriously considered for adoption into the master branch.

Many thanks for you patience and for all the work you've done
already. It is much appreciated.

**Comment by auduchinok** [comment]
> I suspect that your pull request could be adapted to enforce these spacing conventions. 
> Would it be something we could interest you in pursuing?

Well, the whole idea was to make it more compatible with modern F#, at least using an optional directive. One of the motivating reasons was folks in [YaccConstructor](https://github.com/YaccConstructor/YaccConstructor) wanted to rewrite parts of their F# codebase in F* and coming with another incompatible syntax was not something we wanted to achieve here.
I'm sorry for not closing the PR earlier, but at this point I think it'd be better to say explicitly I'm not going to continue this work. I would be happy If anyone works on eliminating perceived ambiguities that newcomers may face, although, looking at current conflicts, a rewrite could probably be an easier approach than adapting this PR.

**Pull request closed without merging**
