### PR TITLE
Fixing `elim_delayed_subst`

### PR DESCRIPTION
**Pull request by mtzguido**
From the commit message:

    tc: norm: elim_delayed_subst: descend into lbnames
    
    And bv sorts, and universes, and take care for memoized free variables.
    
    The problem was posted in #2086, and I minimized it to something like:
    
      let b_hd = sub b 0ul 1ul in
      let b_tl = offset b 1ul in
      admit ()
    
    What was happening was that a meta implicit for sub was being created
    and substituted into the continuation (correctly) and hence into the
    sort of `b_tl`, also correctly. This meta implicit is later solved to
    `false`, and `elim_delayed_subst` is meant to replace the uvar node
    with the solution so we can ditch the UF graph and write the term to
    a file, but it was not descending into the sort of `b_tl`, hence the
    node stayed. The node contains an `env` in the uvar, and it cannot be
    serialized since it contains closures, hence the blowup.
    
    I think only the lbname part will fix the issue, but the rest is going
    to blow up in our face eventually. I also expanded some matches with
    default cases into fully spelling out the cases (e.g. cflags) so when
    something changes we are forced to revisit the logic instead of silently
    defaulting.

### CODE REVIEW

**Comment by mtzguido** [comment]
Also, a question. See this bit in `elim_delayed_subst_term`:
```fstar
    | Tm_uvar(u,s) ->
      mk (Tm_uvar(u,s)) //explicitly don't descend into (bs,t) to not break sharing there
```
I don't understand it, since afaik this function is only called on typechecked top-levels which should always have all of its uvars resolved. A CI run with a `failwith` in this position came back OK.

**Comment by mtzguido** [comment]
I've updated the PR, I've made it not descend into BV sorts now (since they are not substituted), and moved `elim_delayed_subst` from the normalizer into `Subst.deep_compress`, which I think is a better place and name for it. The real diff can be seen in this commit https://github.com/FStarLang/FStar/pull/2091/commits/f4c8d26032847e8f05350fd5cd668bd83f5cd409.

**Comment by mtzguido** [comment]
Come to think of it, `deep_compress` (aka `elim_delayed_subst`) needs to mimic pretty much exactly what `push_subst` does, so maybe we could make them into a single function (taking a `deep:bool` flag) to reduce duplication.

**Comment by nikswamy** [comment]
Thanks @mtzguido!

This looks good to me. I was actually happy to see it as a separate function rather than folded in to push_subst and controlled with a flag. At least that made it way easier to review and not worry as much about its potential interaction with compress which is used so widely.

There's also the bit you mentioned once about trying to remove sorts from Tm_bvar/Tm_name altogether. Would be nice to see that at some point, but I get that it is a separate thing.

**Comment by mtzguido** [comment]
Thanks for reviewing Nik!

> This looks good to me. I was actually happy to see it as a separate function rather than folded in to push_subst and controlled with a flag. At least that made it way easier to review and not worry as much about its potential interaction with compress which is used so widely.

Ack! Any opinion on making it fail when there are unresolved uvars? I remember running with a `failwith` in the term uvar case and passing CI, but not sure about universe uvars (in any case I think that should raise an error, but not 100% sure it doesn't happen now).

> There's also the bit you mentioned once about trying to remove sorts from Tm_bvar/Tm_name altogether. Would be nice to see that at some point, but I get that it is a separate thing.

I tried it... the immediate blocker was the "cheat" uvar solutions during generalization, which do not typecheck (actually crash) when `use_bv_sorts` is off. I tried to have a localized `Allow_untyped` to make progress but no luck, looks like the problem cascades into many uvars. So I think we need a rework of generalization before going for this.

**Pull request merged**
