### PR TITLE
Fix code highlighting in tutorial

### PR DESCRIPTION
**Pull request by DenisGorbachev**
Trivial fix - but the docs will look better)

### CODE REVIEW

**Comment by nikswamy** [comment]
thanks!

**Comment by mpdehnel** [comment]
Ha, I came here literally to add this same fix — glad I checked before submitting a PR! :-)

**Comment by aseemr** [comment]
The source repo has been deleted, so I am unable to merge it. Closing.

**Comment by mpdehnel** [comment]
This was a one line fix — I'd be really grateful if you could update this in the main repo.

Screenshot 2022-04-30 at 19 26 40

**Pull request closed without merging**
