### PR TITLE
Improve OCaml constant int extraction through use of int_of, zero, one

### PR DESCRIPTION
**Pull request by ctk21**
This PR alters OCaml extraction of integer constants. It uses fixed `Z.zero` and `Z.one` for 0 and 1, it also uses OCaml integer literals and `Z.of_int` for a configurable range. Larger integer constants use the existing `Z.of_string` which involves string parsing. 

I benchmarked this change and see the following improvements:
```
                  Old                               New
                  n       total   user    system    n       total   user    system
micro-benchmarks  61      55.68   51.61   3.839     61      54.55   50.34   3.977
ocaml_extract     38      117.7   113.5   4.146     38      117.1   112.7   4.325
ulib              208     380     359.8   19.5      208     364.7   343.8   20.07

```
which is worth about 4% across ulib. Some ulib files show not a great deal of change but others can be 5-10% (e.g. LowStar.RVector).

### CODE REVIEW

**Comment by msprotz** [comment]
This one looks great and non-controversial, I'll merge it as soon as it's green.

Just to make sure I understand: in order to benchmark this change, you did a round of bootstrapping then proceeded to measure the performance of the resulting F* compiler?

**Comment by ctk21** [comment]
> Just to make sure I understand: in order to benchmark this change, you did a round of bootstrapping then proceeded to measure the performance of the resulting F* compiler?

Yes, I rebuilt the compiler with `make -C src ocaml-fstar-ocaml` on a clean tree prior to running the performance of the resulting F* compiler. This is how all the benchmark numbers are made with  `examples/benchmarking/make_bench_results.sh`.

**Comment by msprotz** [comment]
But for this change you would need two rounds of bootstrapping, right? One to get a compiler that is capable of extracting `0` as `Z.zero`, but which was compiled from sources that still use `Prims.parse_int "0"`; then another round to obtain a compiler whose sources feature `Z.zero`... or am I betraying that I haven't had my morning coffee yet? :)

**Comment by ctk21** [comment]
The first compiler that gets built (has sources with `Prims.parse_int "0"`) will actually be able to extract `0` as `Z.zero`, but because the OCaml extraction code when compiling from OCaml lives in `src/extraction/ml/FStar_Extraction_ML_PrintML.ml` and so is not extracted from F*. This means that when the compiler extracts itself, it will output `Z.zero` making one `ocaml-fstar-ocaml` work ok. 
If the extraction code was written in FStar then I think you are correct that you would need to run a second time.

**Pull request merged**
