### PR TITLE
Fix (#1121)

### PR DESCRIPTION
**Pull request by A-Manning**

### CODE REVIEW

**Comment by mtzguido** [comment]
Hi! The fix for #1121 looks good to me, but this PR also has some F# fixes and a bunch of merges. (which are also part of some PR, I think?)

I'll wait until someone reviews the F# part, or the other PR is merged, but I'm in favour of the fix.

**Comment by A-Manning** [comment]
>this PR also has some F# fixes and a bunch of merges. (which are also part of some PR, I think?)

I'm not sure what you mean here, as far as I can see this PR only has one changed file.

>I merged master into this to try and get CI to run; didn't happen

Is there a CI log I can look at to see where it failed?

**Comment by mtzguido** [comment]
> I'm not sure what you mean here, as far as I can see this PR only has one changed file.
Ah, true! I was confused since it shows 11 commits.

> Is there a CI log I can look at to see where it failed?
There's a log but this one didn't kick in. I think we don't do CI for pull requests, but unsure.

I'll take care of merging this then. Thanks a lot!

**Comment by mtzguido** [comment]
Sigh, it's merged now, but github didn't pick it up... trying to trigger it so this appears as "merged" instead of "closed"

**Comment by mtzguido** [comment]
There we go. Thanks again.

**Pull request merged**
