### PR TITLE
Added commandline option to pass options down to Z3.

### PR DESCRIPTION
**Pull request by wintersteiger**
Also cleaned up default Z3 options. The smt.random_seed option is best not written to the smt2 file because it can't easily be changed without copying/modifying files. The other options are non-negotiable anyways.

Feel free to send this back to me for revision if there's anything unusual/undesirable in my changes!

### CODE REVIEW

**Comment by msprotz** [comment]
Just took a look at this... your patch also removes passing the z3 seed. Is this intentional? I seem to recall your saying that this wasn't the greatest idea. If the intent is effectively to remove it, then we should also remove the corresponding option, right?

**Comment by wintersteiger** [comment]
Yes, that's intentional. The seed is only passed on the command line. It's not a good idea to save them in the SMT2 file because it's hard to override them later (requires us to change the files, so the benchmark dataset changes frequently), while conversely, the command line option is easy to override. It's fine for the other options, because we won't want to change them anyways. 

(Although I'm in the process of changing my mind; we may want to disable unsat cores for queries with hints...)

**Comment by msprotz** [comment]
Thanks. Just merged master into your branch to double-check this isn't breaking anything.

**Comment by msprotz** [comment]
I am bypassing the branch restrictions and merging this pull request under the optimistic assumption that this will not break anything.

**Pull request merged**
