### PR TITLE
Remove theory symbols in patterns in ulib

### PR DESCRIPTION
**Pull request by s-zanella**
This removes a few uses of `==` in patterns which are unreliable (see #1660)

### CODE REVIEW

**Comment by s-zanella** [comment]
We may want to add `eq2` to the list of illegal terms in patterns to get an appropriate warning. E.g.
```OCaml
--- a/src/smtencoding/FStar.SMTEncoding.Term.fs
+++ b/src/smtencoding/FStar.SMTEncoding.Term.fs
@@ -472,6 +472,7 @@ let check_pattern_ok (t:term) : option<term> =
         | App(head, terms) ->
             let head_ok =
                 match head with
+                | Var "Prims.eq2" -> false
```

**Comment by s-zanella** [comment]
F* now warns about `==` and other theory symbols in patterns.
Now to triage the 146 warnings in `ulib`!

**Comment by s-zanella** [comment]
All warnings in `ulib`:
```
FStar.Monotonic.Witnessed.fst(75,40-75,74): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> p
FStar.Monotonic.Witnessed.fst(75,40-75,74): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> p
FStar.Monotonic.Witnessed.fst(82,30-82,67): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> Prims.l_True
FStar.Monotonic.Witnessed.fst(82,30-82,67): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> Prims.l_True
FStar.Monotonic.Witnessed.fst(88,37-88,58): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_True
FStar.Monotonic.Witnessed.fst(88,37-88,58): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_True
FStar.Monotonic.Witnessed.fst(93,31-93,69): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> Prims.l_False
FStar.Monotonic.Witnessed.fst(93,31-93,69): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> Prims.l_False
FStar.Monotonic.Witnessed.fst(100,30-100,52): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_False
FStar.Monotonic.Witnessed.fst(100,30-100,52): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_False
FStar.Monotonic.Witnessed.fst(107,31-107,67): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w /\ q w
FStar.Monotonic.Witnessed.fst(107,31-107,67): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w /\ q w
FStar.Monotonic.Witnessed.fst(116,38-116,63): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_and
FStar.Monotonic.Witnessed.fst(116,38-116,63): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_and
FStar.Monotonic.Witnessed.fst(123,38-123,74): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w /\ q w
FStar.Monotonic.Witnessed.fst(123,38-123,74): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w /\ q w
FStar.Monotonic.Witnessed.fst(131,38-131,63): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_and
FStar.Monotonic.Witnessed.fst(131,38-131,63): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_and
FStar.Monotonic.Witnessed.fst(138,30-138,66): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w \/ q w
FStar.Monotonic.Witnessed.fst(138,30-138,66): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w \/ q w
FStar.Monotonic.Witnessed.fst(147,37-147,62): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_or
FStar.Monotonic.Witnessed.fst(147,37-147,62): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_or
FStar.Monotonic.Witnessed.fst(154,37-154,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w \/ q w
FStar.Monotonic.Witnessed.fst(154,37-154,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w \/ q w
FStar.Monotonic.Witnessed.fst(162,37-162,62): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_or
FStar.Monotonic.Witnessed.fst(162,37-162,62): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_or
FStar.Monotonic.Witnessed.fst(169,32-169,69): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w ==> q w
FStar.Monotonic.Witnessed.fst(169,32-169,69): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w ==> q w
FStar.Monotonic.Witnessed.fst(180,39-180,65): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_imp
FStar.Monotonic.Witnessed.fst(180,39-180,65): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_imp
FStar.Monotonic.Witnessed.fst(187,39-187,76): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w ==> q w
FStar.Monotonic.Witnessed.fst(187,39-187,76): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p w ==> q w
FStar.Monotonic.Witnessed.fst(195,39-195,65): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_imp
FStar.Monotonic.Witnessed.fst(195,39-195,65): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_imp
FStar.Monotonic.Witnessed.fst(203,38-203,114): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p x w fun w -> forall (x: t). p x w
FStar.Monotonic.Witnessed.fst(203,38-203,114): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p x w fun w -> forall (x: t). p x w
FStar.Monotonic.Witnessed.fst(212,34-212,79): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> forall (x: t). p x w
FStar.Monotonic.Witnessed.fst(212,34-212,79): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> forall (x: t). p x w
FStar.Monotonic.Witnessed.fst(221,41-221,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Forall fun x -> p x
FStar.Monotonic.Witnessed.fst(221,41-221,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Forall fun x -> p x
FStar.Monotonic.Witnessed.fst(228,41-228,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> forall (x: t). p x w
FStar.Monotonic.Witnessed.fst(228,41-228,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> forall (x: t). p x w
FStar.Monotonic.Witnessed.fst(236,41-236,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Forall fun x -> p x
FStar.Monotonic.Witnessed.fst(236,41-236,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Forall fun x -> p x
FStar.Monotonic.Witnessed.fst(244,38-244,110): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p x w fun w -> exists (x: t). p x w
FStar.Monotonic.Witnessed.fst(244,38-244,110): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> p x w fun w -> exists (x: t). p x w
FStar.Monotonic.Witnessed.fst(253,34-253,76): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> exists (x: t). p x w
FStar.Monotonic.Witnessed.fst(253,34-253,76): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> exists (x: t). p x w
FStar.Monotonic.Witnessed.fst(262,41-262,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Exists fun x -> p x
FStar.Monotonic.Witnessed.fst(262,41-262,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Exists fun x -> p x
FStar.Monotonic.Witnessed.fst(269,41-269,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> exists (x: t). p x w
FStar.Monotonic.Witnessed.fst(269,41-269,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun w -> exists (x: t). p x w
FStar.Monotonic.Witnessed.fst(277,41-277,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Exists fun x -> p x
FStar.Monotonic.Witnessed.fst(277,41-277,73): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.l_Exists fun x -> p x
FStar.Monotonic.Witnessed.fst(284,28-284,68): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> v == v'
FStar.Monotonic.Witnessed.fst(284,28-284,68): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun _ -> v == v'
FStar.Monotonic.Witnessed.fst(294,35-294,61): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2
FStar.Monotonic.Witnessed.fst(294,35-294,61): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2
FStar.DependentMap.fst(50,2-50,29): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun k -> value k fun k -> value k
FStar.DependentMap.fst(50,2-50,29): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun k -> value k fun k -> value k
FStar.DependentMap.fst(252,2-252,28): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun k -> value2 k fun k -> value2 k
FStar.DependentMap.fst(252,2-252,28): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun k -> value2 k fun k -> value2 k
FStar.DependentMap.fst(265,2-265,30): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun k -> value2 k
FStar.DependentMap.fst(265,2-265,30): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  fun k -> value2 k
FStar.List.Tot.Properties.fst(1010,2-1010,136): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.eq2
FStar.List.Tot.Properties.fst(1010,2-1010,136): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.eq2
FStar.Seq.Properties.fst(939,2-939,49): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition 1
FStar.Seq.Properties.fst(939,2-939,49): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition 1
FStar.Seq.Properties.fst(958,2-958,33): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
FStar.Seq.Properties.fst(958,2-958,33): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
FStar.UInt.fst(625,8-625,66): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0
FStar.UInt.fst(625,8-625,66): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0
FStar.UInt.fst(626,8-626,23): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0 (see also FStar.UInt.fst(625,8-625,66))
FStar.UInt.fst(626,8-626,23): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0 (see also FStar.UInt.fst(625,8-625,66))
FStar.UInt.fst(644,8-644,61): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan
FStar.UInt.fst(644,8-644,61): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan
FStar.UInt.fst(645,8-645,22): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan (see also FStar.UInt.fst(644,8-644,61))
FStar.UInt.fst(645,8-645,22): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan (see also FStar.UInt.fst(644,8-644,61))
FStar.UInt.fst(664,8-664,51): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1
FStar.UInt.fst(664,8-664,51): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1
FStar.UInt.fst(665,8-665,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1 (see also FStar.UInt.fst(664,8-664,51))
FStar.UInt.fst(665,8-665,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1 (see also FStar.UInt.fst(664,8-664,51))
FStar.UInt.fst(626,8-626,23): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0 (see also FStar.UInt.fst(625,8-625,66))
FStar.UInt.fst(626,8-626,23): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.op_Modulus 0 (see also FStar.UInt.fst(625,8-625,66))
FStar.UInt.fst(645,8-645,22): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan (see also FStar.UInt.fst(644,8-644,61))
FStar.UInt.fst(645,8-645,22): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_LessThan (see also FStar.UInt.fst(644,8-644,61))
FStar.UInt.fst(665,8-665,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1 (see also FStar.UInt.fst(664,8-664,51))
FStar.UInt.fst(665,8-665,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Subtraction 1 (see also FStar.UInt.fst(664,8-664,51))
LowStar.Monotonic.Buffer.fsti(1036,2-1036,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Monotonic.Buffer.fsti(1036,2-1036,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Monotonic.Buffer.fsti(1048,2-1048,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Monotonic.Buffer.fsti(1048,2-1048,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Endianness.fsti(255,2-255,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(255,2-255,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(263,2-263,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(263,2-263,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(271,2-271,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt64.n} 0
FStar.Endianness.fsti(271,2-271,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt64.n} 0
FStar.Pointer.Base.fsti(1231,2-1231,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
FStar.Pointer.Base.fsti(1231,2-1231,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
FStar.Endianness.fsti(255,2-255,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(255,2-255,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(263,2-263,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(263,2-263,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt32.n} 0
FStar.Endianness.fsti(271,2-271,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt64.n} 0
FStar.Endianness.fsti(271,2-271,48): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Equality i: Prims.int{i >= 0 \/ FStar.UInt.size i FStar.UInt64.n} 0
FStar.Buffer.fst(1006,2-1006,69): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition
FStar.Buffer.fst(1006,2-1006,69): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition
FStar.Buffer.fst(1093,4-1093,58): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0
FStar.Buffer.fst(1093,4-1093,58): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0
FStar.Buffer.fst(1108,4-1108,58): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0
FStar.Buffer.fst(1108,4-1108,58): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0
FStar.UInt128.fst(146,2-146,26): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Modulus
FStar.UInt128.fst(146,2-146,26): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Modulus
FStar.UInt128.fst(152,4-152,27): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Modulus Prims.op_Modulus
FStar.UInt128.fst(152,4-152,27): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Modulus Prims.op_Modulus
FStar.Buffer.fst(1007,4-1007,13): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition (see also FStar.Buffer.fst(1006,2-1006,69))
FStar.Buffer.fst(1007,4-1007,13): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition (see also FStar.Buffer.fst(1006,2-1006,69))
FStar.Buffer.fst(1094,4-1094,13): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0 (see also FStar.Buffer.fst(1093,4-1093,58))
FStar.Buffer.fst(1094,4-1094,13): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0 (see also FStar.Buffer.fst(1093,4-1093,58))
FStar.Buffer.fst(1109,4-1109,13): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0 (see also FStar.Buffer.fst(1108,4-1108,58))
FStar.Buffer.fst(1109,4-1109,13): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 0 (see also FStar.Buffer.fst(1108,4-1108,58))
FStar.Buffer.Quantifiers.fst(32,2-32,77): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition
FStar.Buffer.Quantifiers.fst(32,2-32,77): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition
FStar.Modifies.fsti(430,2-430,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Modifies.fsti(430,2-430,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Modifies.fsti(442,2-442,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Modifies.fsti(442,2-442,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Buffer.Quantifiers.fst(33,4-33,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition (see also FStar.Buffer.Quantifiers.fst(32,2-32,77))
FStar.Buffer.Quantifiers.fst(33,4-33,25): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.op_Addition (see also FStar.Buffer.Quantifiers.fst(32,2-32,77))
LowStar.Monotonic.Buffer.fsti(1036,2-1036,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Monotonic.Buffer.fsti(1036,2-1036,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Monotonic.Buffer.fsti(1048,2-1048,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Monotonic.Buffer.fsti(1048,2-1048,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Vector.fst(666,8-667,50): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2
LowStar.Vector.fst(666,8-667,50): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2
FStar.Modifies.fsti(430,2-430,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Modifies.fsti(430,2-430,86): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Modifies.fsti(442,2-442,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
FStar.Modifies.fsti(442,2-442,82): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  true
LowStar.Vector.fst(668,4-668,17): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 (see also LowStar.Vector.fst(666,8-667,50))
LowStar.Vector.fst(668,4-668,17): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 (see also LowStar.Vector.fst(666,8-667,50))
LowStar.RVector.fst(531,8-531,53): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
LowStar.RVector.fst(531,8-531,53): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0
LowStar.RVector.fst(532,4-532,21): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 (see also LowStar.RVector.fst(531,8-531,53))
LowStar.RVector.fst(532,4-532,21): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  0 (see also LowStar.RVector.fst(531,8-531,53))
```

**Comment by aseemr** [comment]
Hi @s-zanella, should we try to revive and merge this PR, and make sure that it doesn't break the everest code (much)?

**Comment by aseemr** [comment]
I manually checked that all the fixes to patterns in this PR are already accommodated in master, i.e. they do not mention `==`. Closing this PR, thanks Santiago!

**Pull request closed without merging**
