### PR TITLE
A unified LowStar.Endianness module

### PR DESCRIPTION
**Pull request by msprotz**
We have been talking about this for a while.
- FStar.Endianness: a single module that can collect all the reasoning that we need across Everest for endianness, talking about things like: converting a nat to a series of bytes (with or without padding); seeing a sequence of bytes as a sequence of 32-bit little-endian integers; roundtripping between representations; injectivity; etc. etc. etc.
- LowStar.Endianness: low-level stateful Low* combinators specified by the module above; this includes basic operations, like load&store, but also more sophisticated operations, like index and update, which reason over sequences of (little|big)-endian encoded integers

The goal is to ensure that:
- whenever ones needs a tedious lemma and thinks "hmm, this must have been proven somewhere already", this is the place to look for
- whenever such a lemma ends up missing, we can either find it elsewhere (revive secure_api, somewhere in HACL* or Vale) and move it to LowStar.Endianness, to be reusable by others, **or** write it once and for all in LowStar.Endianness
- in the long run, project-specific libraries for endianness end up being shallow wrappers over this library of lemmas.
- allow other LowStar libraries to use endianness functions (@aseemr for your freezable buffers)

As such, I'd like to check that:
- we have a good understanding of what we need / what's missing
- we agree on the shape of these lemmas to make sure the module is as useful as I hope it'll be.

# Features of these two modules

Stateful operations:
- functional byte-swapping: `assume val htole16: UInt16.t -> Tot UInt16.t` and others
- loads and stores, which take a buffer that has been `sub`'d to the right length, e.g.
```
assume val store16_le:
  b:B.buffer UInt8.t{B.length b == 2} -> // buffer has the right length already
  z:UInt16.t ->
  Stack unit
    (requires (fun h -> B.live h b))
    (ensures  (fun h0 _ h1 -> B.(modifies (loc_buffer b) h0 h1) /\ B.live h1 b /\
                           le_to_n (B.as_seq h1 b) == UInt16.v z)) // specification in terms of a single integer
```
- index and update, which take a buffer whose length is a multiple of the word size, and specify their operations in terms of update an element in a sequence of integers
```
inline_for_extraction
let index_32_be (b: B.buffer UInt8.t) (i: UInt32.t): // reasons over a buffer of big-endian encoded uint32s
  Stack UInt32.t
    (requires (fun h ->
      B.live h b /\ B.length b % 4 = 0 /\ // buffer length must be 4 * N
      UInt32.v i < B.length b / 4)) // 0 <= i < N
    (ensures (fun h0 r h1 ->
      B.(modifies loc_none h0 h1) /\
      r = Seq.index (seq_uint32_of_be (B.length b / 4) (B.as_seq h0 b)) (UInt32.v i))) // returns S[i] where S is the sequence of uint32s that stem from reading b in big-endian
=
  load32_be (B.sub b FStar.UInt32.(4ul *^ i) 4ul)
```

Specifications:
- definitions: le_to_n, be_to_n
- inverses: n_to_le, specified intrinsically:
```
val n_to_le : len:U32.t -> n:nat{n < pow2 (8 * U32.v len)} ->
  Tot (b:bytes{S.length b == U32.v len /\ n == le_to_n b})
  (decreases (U32.v len))
```
- injectivity:
```
let n_to_le_inj (len:U32.t) (n1 n2: (n:nat{n < pow2 (8 * U32.v len)})) :
  Lemma (requires (n_to_le len n1 == n_to_le len n2))
        (ensures (n1 == n2)) =
```
- idempotence:
```
let n_to_be_be_to_n (len: U32.t) (s: Seq.seq U8.t) : Lemma
  (requires (Seq.length s == U32.v len))
  (ensures (
    be_to_n s < pow2 (8 `Prims.op_Multiply` U32.v len) /\
    n_to_be len (be_to_n s) == s
  ))
```
- interpreting bytes as a sequence:
```
let rec seq_uint32_of_le (l: nat) (b: bytes{ S.length b = 4 * l }):
  s:S.seq UInt32.t { S.length s = l }
```
- relating bytes and sequences:
```
let rec offset_uint32_be (b: bytes) (n: nat) (i: nat):
  Lemma
    (requires (
      S.length b = 4 * n /\
      i < n))
    (ensures (
      S.index (seq_uint32_of_be n b) i == uint32_of_be (S.slice b (4 * i) (4 * i + 4))))
    (decreases (
      S.length b))
```
- appending and slicing such sequence (same style)

# Questions

@s-zanella, @tahina-pro, @fournet, @Chris-Hawblitzel, @parno, @karthikbhargavan, @polubelova have all had to deal with this at some point

- Can you tell me what's missing from this library and the kind of lemmas that you would need?
- What is a good shape for these lemmas to be maximally reusable? For instance, @tahina-pro pointed out that `n_to_le` takes a uint32, which is needlessly restrictive. Are there other places where changing the statement of the lemmas would allow, say, Vale to reuse them better (@Chris-Hawblitzel?)

I'd like to merge this in an incomplete state, to encourage incremental additions to this module, immediate conversion of existing projects, and to ensure that whatever work ends up happening in HACL*'s lib/ directory can rely on this module now (I understand that Santiago is in the process of proving many things in lib/).

As such, if someone (e.g. Santiago) could confirm that this is immediately useful, I'd be inclined to merge as soon as we fix small-ish things (uint32 -> nat for `n_to_le`, for instance).

Thanks,

Jonathan

### CODE REVIEW

**Comment by aseemr** [comment]
Thanks Jonathan, this would is quite useful. Very quickly, at a high-level, we should generalize it to monotonic buffers. If you want, I would be happy to help with that.

**Comment by msprotz** [comment]
Also pinging @R1kM

**Comment by msprotz** [comment]
Need to rename LowStar.Endianness.Spec into FStar.Endianness

**Comment by Chris-Hawblitzel** [comment]
We might be able to take advantage of this in Vale as follows.  We already use `seq nat8` frequently, where `nat8` is defined as a `nat` less than 256.  We can show the correspondence between `seq nat8` and `seq U8.t` once and for all.  Then we could make equivalents to `le_to_n` and `be_to_n` that use `seq nat8` rather than `seq U8.t`.  This would allow us to reuse the proofs from LowStar Endianness about `le_to_n` and `be_to_n`, such as round-tripping.  Since the LowStar Endianness proofs are based on recursively processing one byte at a time, I expect them to be faster and more reliable than some existing Vale proofs like `Words.Seq.nat_to_four_to_nat`, which work on 4 bytes (or more) at a time and therefore have large z3rlimits and seem fragile.

**Comment by parno** [comment]
I think it would be fantastic to have a standard library covering all of these use cases and that we could all contribute to, instead of each project separately reinventing small portions.  

Keeping them general as much as possible would go a long way.  For instance, in Vale, we frequently convert between 8-bit, 32-bit, 64-bit, and 128-bits, as well as sequences thereof.  Almost everything in Vale is ghost from F*'s perspective, so avoiding a commitment to state (at least at the spec level) would be helpful.

For a sampling of what we've developed at the Vale level, I'd point to these specs:
- [Types_s.fst](https://github.com/project-everest/hacl-star/blob/_vale/vale/specs/defs/Types_s.fst)
- [Words.*] (https://github.com/project-everest/hacl-star/tree/_vale/vale/specs/defs)
And lemmas like:
- [Arch.Types.fsti](https://github.com/project-everest/hacl-star/blob/_vale/vale/code/arch/Arch.Types.fsti)
- [Words.Seq.fsti](https://github.com/project-everest/hacl-star/blob/_vale/vale/code/lib/util/Words.Seq.fsti)
- [Words.Two.fsti](https://github.com/project-everest/hacl-star/blob/_vale/vale/code/lib/util/Words.Two.fsti)

**Comment by s-zanella** [comment]
Thanks Jonathan.
This looks like a great start to replace `FStar.Kremlin.Endianness` and `C.Endianness`. I can port Hacl* lib to use this as soon as it gets merged.

For reference, the corresponding libraries in Hacl* are [`Lib.ByteSequence`](https://github.com/project-everest/hacl-star/blob/_dev/lib/Lib.ByteSequence.fsti) and  [`Lib.ByteBuffer`](https://github.com/project-everest/hacl-star/blob/_dev/lib/Lib.ByteBuffer.fsti). I went through them gathering all definitions and matching them against the definitions in the PR. This is the result after simplification to remove secrecy levels and irrelevant parts:
```FStar
/// Specification in Lib.ByteSequence

type inttype =
  | U1 | U8 | U16 | U32 | U64 | U128

let numbytes = function
  | U1 -> 1
  | U8 -> 1
  | U16 -> 2
  | U32 -> 4
  | U64 -> 8
  | U128 -> 16

let bits = function 
  | U1 -> 1
  | t  -> 8 * numbytes t

let bytes = seq (uint U8)
let lbytes (n:nat) = b:bytes{length b == n}

/// These generalize {le,be}_to_n for sequences of any machine integer type (not just U8)
/// and internalize lemma_{le,be}_to_n_is_bounded
val nat_from_seq_le: #t:inttype -> b:seq (uint t) -> n:nat{n < pow2 (length b * bits t)}
val nat_from_seq_be: #t:inttype -> b:seq (uint t) -> n:nat{n < pow2 (length b * bits t)}

/// These generalize n_to_{le,be}, taking len:nat instead of len:U32.t
val nat_to_bytes_le: len:nat -> n:nat{n < pow2 (8 * len)}
  -> b:bytes{length b == len /\ n == nat_from_seq_le #U8 b}
val nat_to_bytes_be: len:nat -> n:nat{n < pow2 (8 * len)} 
  -> b:bytes{length b == len /\ n == nat_from_seq_be #U8 b}

/// These generalize {le,be}_of_uint{32,64}
val uint_to_bytes_le: #t:inttype -> uint t -> lbytes (numbytes t)
val uint_to_bytes_be: #t:inttype -> uint t -> lbytes (numbytes t)

/// These generalize uint{32,64}_of_{le,be}
val uint_from_bytes_le: #t:inttype -> lbytes (numbytes t) -> uint t
val uint_from_bytes_be: #t:inttype -> lbytes (numbytes t) -> uint t

/// These generalize {le,be}_of_seq_uint{32,64}
val uints_to_bytes_le: #t:inttype -> #len:nat -> lseq (uint t) len -> lbytes (len * numbytes t)
val uints_to_bytes_be: #t:inttype -> #len:nat -> lseq (uint t) len -> lbytes (len * numbytes t)

/// These generalize seq_uint{32,64}_of_{le,be} 
val uints_from_bytes_le: #t:inttype -> #len:nat -> lbytes (len * numbytes t) -> lseq (uint t) len
val uints_from_bytes_be: #t:inttype -> #len:nat -> lbytes (len * numbytes t) -> lseq (uint t) len

/// This lemma seems useful but is currently missing in FStar.Endianness
val index_uint_to_bytes_le: #t:inttype -> u:uint t
  -> Lemma (forall (i:nat{i < numbytes t}). index (uint_to_bytes_le #t u) i ==
                                    uint #U8 (uint_v u / pow2 (8 * i) % pow2 8))
```
```FStar
/// LowStar stateful operations in Lib.ByteBuffer

module BS = Lib.ByteSequence

/// These generalize hto{le,be}{16,32,64}
val uint_to_be: #t:inttype{~(U128? t)} -> uint t -> uint t
val uint_to_le: #t:inttype{~(U128? t)} -> uint t -> uint t

/// These generalize {lembe}{16,32,64}toh
val uint_from_be: #t:inttype{~(U128? t)} -> uint t -> uint t
val uint_from_le: #t:inttype{~(U128? t)} -> uint t -> uint t

/// These generalize load{16,32,64,128}_{le,be}
val uint_from_bytes_le: #t:inttype{~(U1? t)} -> i:lbuffer (uint_t U8) (size (numbytes t)) ->
  Stack (uint t)
    (requires fun h0 -> live h0 i)
    (ensures  fun h0 o h1 -> h0 == h1 /\ live h1 i /\
      o == BS.uint_from_bytes_le #t #l (as_seq h0 i))
val uint_from_bytes_be: #t:inttype{~(U1? t)} -> i:lbuffer (uint_t U8) (size (numbytes t)) ->
  Stack (uint t)
    (requires fun h0 -> live h0 i)
    (ensures  fun h0 o h1 -> h0 == h1 /\ live h1 i /\
      o == BS.uint_from_bytes_be #t (as_seq h0 i))

/// These generalize store{16,32,64,128}_{le,be}
val uint_to_bytes_le: #t:inttype -> o:lbuffer (uint_t U8) (size (numbytes t)) -> i:uint t ->
  Stack unit
    (requires fun h0 -> live h0 o)
    (ensures  fun h0 _ h1 -> live h1 o /\ modifies (loc o) h0 h1 /\
      as_seq h1 o == BS.uint_to_bytes_le #t i)
val uint_to_bytes_be: #t:inttype -> o:lbuffer (uint_t U8) (size (numbytes t)) -> i:uint t ->
  Stack unit
    (requires fun h0 -> live h0 o)
    (ensures  fun h0 _ h1 -> live h1 o /\ modifies (loc o) h0 h1 /\
      as_seq h1 o == BS.uint_to_bytes_be #t i)

/// These iterate uint_from_bytes_{le,be} and should probably be added to LowStar.Endianness
val uints_from_bytes_le: #t:inttype{~(t == U1)} 
  -> #len:size_t{v len * numbytes t <= max_size_t}
  -> o:lbuffer (uint t) len
  -> i:lbuffer (uint_t U8) (len *! size (numbytes t)) ->
  Stack unit
        (requires fun h0 -> live h0 o /\ live h0 i /\ disjoint o i)
        (ensures  fun h0 _ h1 -> modifies1 o h0 h1 /\
          as_seq h1 o == BS.uints_from_bytes_le #t #(v len) (as_seq h0 i))
val uints_from_bytes_be: #t:inttype{~(t == U1)}
  -> #len:size_t{v len * numbytes t <= max_size_t}
  -> o:lbuffer (uint t) len
  -> i:lbuffer (uint_t U8) (len *! size (numbytes t)) ->
  Stack unit
        (requires fun h0 -> live h0 o /\ live h0 i /\ disjoint o i)
        (ensures  fun h0 _ h1 -> modifies1 o h0 h1 /\
          as_seq h1 o == BS.uints_from_bytes_be #t #(v len) (as_seq h0 i))

/// These iterate uint_to_bytes_{le,be} and should probably be added to LowStar.Endianness
val uints_to_bytes_le: #t:inttype
  -> len:size_t{v len * numbytes t <= max_size_t}
  -> o:lbuffer (uint_t U8) (len *! size (numbytes t))
  -> i:lbuffer (uint t) len ->
  Stack unit
        (requires fun h0 -> live h0 o /\ live h0 i /\ disjoint o i)
        (ensures  fun h0 _ h1 -> modifies1 o h0 h1 /\
          as_seq h1 o == BS.uints_to_bytes_le #t #(v len) (as_seq h0 i))
val uints_to_bytes_be: #t:inttype
  -> len:size_t{v len * numbytes t <= max_size_t}
  -> o:lbuffer (uint_t U8) (len *! size (numbytes t))
  -> i:lbuffer (uint t) len ->
  Stack unit
        (requires fun h0 -> live h0 o /\ live h0 i /\ disjoint o i)
        (ensures  fun h0 _ h1 -> modifies1 o h0 h1 /\
          as_seq h1 o == BS.uints_to_bytes_be #t #(v len) (as_seq h0 i))
```
Essentially, I don't think there is much missing in the PR besides completing operations for all relevant machine integer sizes. E.g. we need `upd_{16,32,64,128}_{le,be}` but we have just `upd_32_be`;
`le_to_n` should be generalized for sequences of other machine widths besides `uint8`. Some are already in Hacl* library and be moved to `ulib`. 
All this can be done on demand once the PR is merged; we don't need to wait to complete everything now.

What do people think of adding interfaces, i.e. `FStar.Endianness.fsti` and `LowStar.Endianness.fsti`?

**Comment by msprotz** [comment]
How about we:
- fix stateful operations to operate on monotonic buffers, and
- fix that u32 that should be a nat
then merge immediately, to unblock work on HACL*? 

I'm not too keen on interfaces, and I think it'd be a pain because LowStar.Endianness freely mixes assume val and actual vals -- it wouldn't be as easy to express with an interface. These modules are meant to be fairly transparent anyhow, right?

This way, the libraries can be improved incrementally as the proofs progress in HACL*, and I can start working backwards-compatible modules in kremlib.

**Comment by parno** [comment]
We've been bitten in the past by letting the recursion, and the mod and div operations necessary for talking about endian-ness visible by default to Z3.  In the end, I think we ended up marking a lot of our definitions opaque and then only revealing them when proving lemmas about the properties.  Using an interface would accomplish the same goal, so it seems worth considering.

**Comment by msprotz** [comment]
Would you envision clients using `reveal` lemmas, or rather the `friend` mechanism?

@aseemr had a new style for hiding definitions from z3 that has been put in place in some spots in HACL*; see https://github.com/project-everest/hacl-star/blob/fstar-master/code/hash/Hacl.Hash.Core.MD5.fst#L126 and https://github.com/project-everest/hacl-star/blob/fstar-master/specs/Spec.MD5.fst#L142

Would you be happy with this style?

**Comment by parno** [comment]
Ideally, I would hope that most clients could use the library's lemmas to get the properties they need (e.g., injectivity) without needing to `friend` or `reveal`.  Between the two, I don't have a strong preference.  I guess `reveal` imposes fewer transitive issues than `friend`.

I think Aseem's style is fine.  My only (minor) quibble is that it requires changing the function definition site, which may not always be possible in general.  For newly minted libraries, it seems fine.

**Comment by R1kM** [comment]
I'd be in favour of `reveal` over `friend`: It's usable from .fsti files, and it avoids revealing all the definitions in the file at the same time, since we very often only need to reveal a few for a given proof.

**Comment by s-zanella** [comment]
For reference, Hacl* uses interfaces for both specification and stateful operations. It doesn't use `assume val`s because it builds on the ones in `C.Endianness`. `Lib.ByteBuffer` is a `friend` of `Lib.ByteSequece`; otherwise one would need to have a lot of lemmas in `Lib.ByteSequence.fsti`. The rest of Hacl* code never needs to befriend either library module nor reveals any internal definitions in other way.
I'm in favor of interaces for the same reasons as @parno; it reduces the SMT context. Either `reveal` or `friend` are fine by me (I've a slight preference for `friend` for simplicity and because at least in Hacl* code the things exposed in interfaces seemed enough.).

**Comment by msprotz** [comment]
Ok, so then we probably need to move the `assume val`s to a separate fsti, with no fst in the first place, then later on we can write a model for it if we want. How does that sound?

**Comment by aseemr** [comment]
I added support for monotonic buffers in the stateful API, see the branch `_aseem_lowstar_endianness` and this commit: https://github.com/FStarLang/FStar/commit/f3b4e322fa3a4e1d17ef3b7a399d5a47e72e2fbd.

The library was earlier following a style where the caller passes a sub-buffer of exact length (say length 2 when writing a `u16` into a `u8` buffer). In general taking sub-buffers of arbitrary preorder buffers is not trivial, for example you have to think about what's the preorder for the sub-buffers, it is not always the case that the same preorder as the original buffer works.

So I have changed the API instead to take an index argument, with appropriate length restrictions (in the example above that `index + 2 <= length buffer`).

The file verifies but for an `admit` in a lemma in `upd_32_be`, someone more familiar with the proof should take a look (the only change is the call to `store32_be` after which I added 3 assertions to check that it changes the buffer as expected).

Please let me know if you have any comments.

**Comment by msprotz** [comment]
Thanks, Aseem, I've merged your branch into this pull request, and I've also overhauled the lemmas to take `nat`s instead of `UInt32.t`s, as discussed above.

@tahina-pro I seem to remember you authored that proof; do you have any clue about the failure?

**Comment by msprotz** [comment]
I've added an interface for FStar.Endianness only. For LowStar.Endianness, all the functions are stateful and (unless I'm mistaken) have no consequences for context pollution. Also, it'd make things slightly more convoluted, because the `assume val` would become `val` in the fsti, which would force me to implement them, but using `admit ()` (unless we want to write a model). Maybe we can leave that for later?

**Comment by msprotz** [comment]
There was a stale FStar.Endianness in scope for the old code and the old secure_api development, which I renamed in HACL* -- it would've prevented this merge

**Comment by msprotz** [comment]
I tried to part some bits of HACL* to use this module. Two remarks.
- It's kind of a pain having to write the index for store and load operations, but not the end of the world.
- There are three lemmas that I thought were redundant and have SMTPatterns. They are of the form:
```
val be_of_seq_uint32_base (s1: S.seq U32.t) (s2: S.seq U8.t): Lemma
  (requires (
    S.length s1 = 1 /\
    S.length s2 = 4 /\
    be_to_n s2 = U32.v (S.index s1 0)))
  (ensures (S.equal s2 (be_of_seq_uint32 s1)))
  [ SMTPat (be_to_n s2 = U32.v (S.index s1 0)) ]
```
they appear to me to just be rephrasings of the `offset` functions. @tahina-pro I see that you originally added these in kremlib. Do you remember why we needed them?

**Comment by aseemr** [comment]
@msprotz, you can rename the monotonic versions of these functions as `_generic` or `_mono` or something, and add functions with previous specs defined in terms of these monotonic versions (basically for trivial preorder). That would require no change in the client code. And might be a good idea anyway to have these versions for the common cases of trivial preorder.

**Comment by msprotz** [comment]
> @msprotz, you can rename the monotonic versions of these functions as `_generic` or `_mono` or something, and add functions with previous specs defined in terms of these monotonic versions (basically for trivial preorder). That would require no change in the existing client code. And might be a good idea anyway to have these versions for the common cases of trivial preorder.
different points come to mind:
- having two different sets of combinators would require duplicating these definitions (https://github.com/FStarLang/kremlin/blob/master/include/kremlin/c_endianness.h#L159) since we'd have to keep the original ones for backwards-compatibility; it's a sensitive part of the TCB and it'd be a plus to keep it minimal
- it would also cause confusion on the API
would this work?
```
assume val store16_be
  (#rrel #rel:B.srel u8) (b:B.mbuffer u8 rrel rel){ 2 <= B.length b }
  (z:u16)
  : Stack unit
      (requires (store_pre  b (U32.v i) 2 (fun s -> be_to_n s == U16.v z)))
      (ensures  (store_post b (U32.v i) 2 (fun s -> be_to_n s == U16.v z)))
```
it would be just a specialization of the current version, with i = 0
> 
> But I am also curious, I thought the clients would be taking sub-buffers by calling `B.sub` to call these API, and taking an index would make it easier (no more `sub` calls). Is it the case that the clients have exact-length buffers so they are not calling `B.sub`?
the buffers had already been sub'd for the purposes of calling the right lemmas from the library, see https://github.com/project-everest/hacl-star/blob/fstar-master/code/hash/Hacl.Hash.PadFinish.fst#L258 for an example -- the pattern in HACL* and for work on buffers in general is to first chop it up in sub-buffers, then operate on each sub-buffer individually, then call sequence associativity lemmas to recombine the sub-sequences that correspond to the sub-buffers into the larger buffer

**Comment by aseemr** [comment]
This is what I have in mind:

```
//this is what is defined in c_endianness.h
assume val store16_le_mono
  (#rrel #rel:B.srel u8) (b:B.mbuffer u8 rrel rel)
  (i:u32{U32.v i + 2 <= B.length b})
  (z:u16)
  : Stack unit
      (requires (store_pre  b (U32.v i) 2 (fun s -> le_to_n s == U16.v z)))
      (ensures  (store_post b (U32.v i) 2 (fun s -> le_to_n s == U16.v z)))

//implemented in terms of above
inline_for_extraction
let store16_le
  (b:LowStar.Buffer.buffer UInt8.t{B.length b == 2})
  (z:UInt16.t)
  : Stack unit
      (requires (fun h -> B.live h b))
      (ensures  (fun h0 _ h1 -> B.(modifies (loc_buffer b) h0 h1) /\ B.live h1 b /\
                             le_to_n (B.as_seq h1 b) == UInt16.v z))

  = store16_le_mono b 0ul z
```

The API you have proposed would still require the clients to take the sub-buffers (though it is a sub-buffer from `i` to `length b`, where `i` is the index at which to store). For trivial preorders it is not a problem, but for more interesting preorders (such as PrefixFreezableBuffers) it is not obvious which preorder clients should use to call `B.msub`.

I don't understand the backward-compatibility issue and the need to keep both defns in `c_endianness.h` well, we can talk more about it.

**Comment by msprotz** [comment]
This was merged, with one leftover assume for that proof that regressed.

**Comment by aseemr** [comment]
Can I prove this lemma from `FStar.Endianness`:

```
val le_to_n_zeros (s:Seq.seq u8)
  : Lemma
    (requires
      Seq.length s >= 4 /\
      (forall (i:nat). i < Seq.length s ==> Seq.index s i == 0uy))
    (ensures le_to_n_endianness (Seq.slice s 0 4) == 0)
```
Or do I need to `friend` `FStar.Endianess`?

**Comment by msprotz** [comment]
That sounds useful! Add it into the module?

**Comment by aseemr** [comment]
How about reveal lemmas like this: https://github.com/FStarLang/FStar/commit/c5756ede94bedf2d45dbb5878ec67af6575152e7, and then clients can easily prove such properties: https://github.com/FStarLang/FStar/commit/cd35658b433732e772d1794b22fdc5e28a3c9087.

**Comment by msprotz** [comment]
Well, the point of adding a module in ulib was to have a comprehensive collection of lemmas that could be reusable and shared, instead of every client using reveal and proving his own lemmas on the side. Right now, HACL*, Vale, secure_api all re-prove the same things in their own directories and it's a lot of wasted time and effort.

I believe your lemma is not specific to freezable buffers and I can foresee other clients happily reusing it. Would you mind adding it into FStar.Endianness rather than locally inside of freezable buffers?

**Comment by msprotz** [comment]
Clients of LowStar.Endianness were not properly compiled by kremlin -- this is now fixed via the commit above.

**Pull request merged**
