### PR TITLE
Cleaning up FStar.String

### PR DESCRIPTION
**Pull request by nikswamy**
FStar.String had 3 unsoundnesses

1 and 2. `substring` and `get` could throw out of bounds exceptions but were giving `Tot` types

3. `sub` was given a wrong return type `char`, when it should have been `string`.

I've fixed that.

Also, some but not all Tot functions had implementations in the normalizer and NBE. I've cleaned it up a bit and given all assumed Tot functions implementations in the normalizer and NBE.

Also, `Prims.strcat` was unusual in that it was also replicated in FStar.String.strcat. I've deprecated `Prims.strcat`. 

Also, the operator `^` had primitive support, desugaring it to `Prims.strcat`. I've removed this special support.

All of this is quite a bit of churn, and this branch doesn't work yet. But, there are lot of tedious details here that could use multiple sets of eyes to make sure that I actually fixed these issues without screwing things up in some other way.

Note, the deprecation attribute on Prims.strcat and Prims.(^) does not seem to result in a warning at use sites. I'm still investigating that.

### CODE REVIEW

**Comment by nikswamy** [comment]
deprecation of Prims.strcat and Prims.(^) now correctly produces warnings

**Comment by mtzguido** [comment]
I took a look and I think this looks good. Although we can restore that normalizer test, no?

**Comment by mtzguido** [comment]
Actually, let me add a set of F* regression tests for all these operators. I'll push it to this branch if you don't mind.

**Comment by mtzguido** [comment]
Just pushed them. One funkiness that remains is that the SMT does not know about any of these, which I guess depends on #548. This is more annoying than it sounds since definitions can prevent primop reduction, so things like `assert (List.length (list_of_string "A") == 1)` work, but `assert (strlen "A" == 1)` does not (unless we use `assert_norm` or mark `strlen` as `unfold`).

**Comment by nikswamy** [comment]
Hi Guido, thanks for the tests! I disabled the one in the unit-tests since in that context we only have Prims in scope, not FStar.String. Now that you added more tests, maybe I can move the one from the unit-tests there.

**Comment by nikswamy** [comment]
This pull request snowballed into several issues. 

* I am abandoning my attempt to deprecate `Prims.strcat` and `Prims.(^)`. These are very common operations in our code base, it receives special treatment in the normalizer, and arguably should remain in prims. It is also in line with F# and OCaml, which include ^ pervasively. Deprecating them and moving them to FStar.String requires many modules to open FStar.String just for `^`, which in turn brings dependences on FStar.Char, FStar.UInt32, FStar.UInt, FStar.All. FStar.Heap, ... too much stuff for a measly `^`. After discussion with @msprotz , the conclusion is to retain `Prims.strcat` and `Prims.(^)` and to remove them from FStar.String (to avoid duplication).

With Prims.strcat back, I have also restored the unit tests for strcat that I removed earlier.

Meanwhile, in my attempts to deprecate these operators, I found and fixed a few bugs:

* Attributes were being dropped on `val` declarations in ToSyntax
* Deprecation warnings were not being reported on operators (only on lid's)
* warn_error was not being handled properly, with mutable state in FStar.Errors not being encapsulated correctly, leading to `--warn_error` in #set-options etc. not being respected.

That's part of this PR too.

**Pull request merged**
