### PR TITLE
Added __FILELINE__ and it's test file

### PR DESCRIPTION
**Pull request by briangmilnes**

### CODE REVIEW

**Comment by briangmilnes** [comment]
Guido can you put this in so I can put out Flog and Final please?

**Comment by mtzguido** [comment]
Hi Brian, can you do the changes we talked about here https://github.com/FStarLang/FStar/pull/3574#issuecomment-2427810488. It should return only the basename of the file (no leading directory components) and then the test would work without anything fancy (string_of_list, etc)

**Comment by briangmilnes** [comment]
All good, rebuild and retested just to be sure. 
But it still needs the list_of_string/string_of_list. 
Good enough?

**Comment by briangmilnes** [comment]
I tried to move the string code changes into FStarC_Parser_LexFStar with
 | "__FILELINE__"   -> STRING (
    let fl = ((L.source_file lexbuf) ^ "(" ^ (string_of_int (L.current_line lexbuf)) ^ ")") in 
    let lfl = BatList.init (BatUTF8.length fl) (fun i -> BatUChar.code (BatUTF8.get fl i)) in
    let sfl = BatUTF8.init (BatList.length lfl) (fun i -> BatUChar.chr (BatList.at lfl i)) in
      sfl)

but when I

 let fl1 = __FILELINE__ in 
  print_string("|" ^ __FILELINE__ ^ "|" ^ (strlen fl1) ^ "\n");

strlen says F* is typing fl1 as a nat. 

 Any idea how a STRING () lexeme can end up gettting typed as a nat?

**Comment by briangmilnes** [comment]
Yet print as a string directly?

**Comment by mtzguido** [comment]
Hi Brian, I updated this PR to take only the basename, and the test to not use `string_of_list`/`list_of_string`. I didn't understand your comment on why it's still needed, can you say more if I misunderstood?

If this looks good to you I can merge it.

**Comment by briangmilnes** [comment]
Looks good. Pls merge.

**Pull request merged**
