### PR TITLE
Add `push-partial-checked-file` IDE request

### PR DESCRIPTION
**Pull request by gebner**
This PR adds a `push-partial-checked-file` IDE request, which loads a partial prefix of a checked file.  The resulting environment is similar to the environment you'd get at that point in the middle of the file.  In particular, private declarations and declarations that are not listed in the interface file are still accessible.  Furthermore, declarations that come after the initial prefix cannot be referenced by name and are not exported to Z3.  This allows the proof checking harness to correctly verify proofs of existing declarations.

Protocol-wise, the `push-partial-checked-file` IDE request behaves very similarly to the existing `push` request.  On success, it pushes to the REPL stack and the effect can be reverted using a subsequent `pop` request.  On failure, it returns a list of error messages and does not modify the stack.

The intended usage is to send a `push-partial-checked-file` followed by a push of the declaration that is to be checked.
 1. `push-partial-checked-file { until-lid = "FStar.Matrix.ijth_lemma" }`
 2. `push { code = "val ijth_lemma : ...\n let ijth_lemma #c #m #n mx i j = ()" }`
 3. `pop {}` (if (2) was successful)
 4. `pop {}`

The `push-partial-checked-file` request is moderately expensive since it needs to redo the SMT encoding and send it to Z3.  (Though in my limited testing, it is usually faster than loading the other dependent modules.)  Doing multiple `push` requests after the `push-partial-checked-file` works as expected and amortizes this cost.

Notably, the checked files do not contain enough information to reconstruct the prefix environment perfectly.  While we persist which `open` and `module =` statements occur in the source file, we do not remember where they occurred in the file.  Neither do we store `#push-options` commands.  The `push-partial-checked-file` request does not open any namespaces presently, leaving it to the user code to add the appropriate open and option statements.

### CODE REVIEW

**Comment by nikswamy** [comment]
Hi @gebner, this looks great, thanks!

Can you add a test case for this new feature, please? For example, in tests/ide/emacs, you could add a `.in` file with the new push-partial-checked-file request, followed by checking some source snippet in that context

**Comment by gebner** [comment]
> Can you add a test case for this new feature, please? For example, in tests/ide/emacs [...]

I thought about that, but the following comment in the Makefile scared me a bit:
```make
# We turn off the .checked file cache so we don't get any races in CI
```
I don't know what races this refers to, do you have any idea?  The `push-partial-checked-file` request however explicitly requires checked files.

The other issue is that `fstar.exe --ide` needs to be called with the `Foo.fst` file as argument that we have a `Foo.fst.checked` file for (as opposed to the other tests, where fstar can be started on a pretty much unrelated file).  I would need to add a separate make rule for that single test.

**Comment by nikswamy** [comment]
Ah, good catch about turning off checked files in this directory.

Regarding the race:

The makefile in this directory fires all the targets in parallel, without scanning them for dependences. That's because each of these are meant to be small standalone tests. So, we turn off checked files, since running these in parallel with checked files on can cause them to stomp on each other.

So, indeed, if we were to add a test case for push-partial-checked-file, then that would require a separate make target. I think a separate make target for this purpose would still be worthwhile. Otherwise, without a test for this feature in the repo, I worry that it will eventually break and no one would notice.

**Comment by gebner** [comment]
Okay, I've added two tests.

**Pull request merged**
