### PR TITLE
Change int to bigint

### PR DESCRIPTION
**Pull request by qunyanm**

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Neat! But, out of curiosity, how do things like `if String.length str < (Prims.parse_int "2") then` even work? Doesn't `String.length` return an `int`?

**Comment by qunyanm** [comment]
String.Length returns bigint.


________________________________

**Comment by cpitclaudel** [comment]
Oh, OK :) I thought it came from the F# standard library.

**Comment by nikswamy** [comment]
Hi Qunyan, 

Thanks for this work. It's a substantial pull request and I think you have accurately implemented our original  description of the solution.

However, Jonathan and I have been discussing this PR and think that we, unfortunately, sent you down the wrong path. The change is too invasive to maintain in practice within this codebase that we all work heavily in day to day. E.g., always writing `parseInt "0"` instead of `0` is quite tedious.

Our revised understanding of the problem and solution is as follows:

The problem: We want the F# version of F\* to soundly treat operations on mathematical integers without getting into integer overflow. Other parts of the compiler that currently use integers are not susceptible to overflow anyway, e.g., de Bruijn indices are never likely to get so large.

The revised solution: There are two parts of the compiler (that we know of right now) that rely on mathematical integers.

1. FStar.TypeChecker.Normalize: When reducing primitive operators on integers, we really mean to use mathematical integers. Currently, in F# we're using platform ints (int64) which leads to overflow and unsoundness. We should change this to use .NET BigInteger.

2. FStar.Const.bounds and its use in FStar.ToSyntax.ToSyntax: both evaluate the bounds of fixed width integers, which can exceed the size of int64. We should also switch this to BigInteger.

The rest of the code can remain unchanged and we should still have soundness in F#.

Note, this approach would still mean that the F# and OCaml version are "different" in that the OCaml version (being extracted from F*) would use zarith everywhere, whereas F# would only use BigInteger in selected places.

Qunyan: We don't expect you to make this change and revise the pull request. This is quite a delicate change (though relatively small) and one of us will do it at some point, hopefully soon.

**Pull request closed without merging**
