### PR TITLE
Added foldm_snoc_split lemma to Seq.Permutation

### PR DESCRIPTION
**Pull request by hacklex**
A lemma that allows splitting a foldm_snoc over a `CommMonoid`-induced sum into two separate foldm_snoc calls, one for each summand.

Two utils, 
* `init_func_from_expr` that constructs a lambda suited for an `init` call
* `func_sum` that constructs a pointwise CommMonoid-induced sum lambda from two summand lambdas.

### CODE REVIEW

**Comment by nikswamy** [comment]
hi @hacklex 

Thanks for this contribution! It looks great overall and the proof is actually quite subtle.

I've edited your proof and made it a bit more compatible with the style of the rest of that module. My changes are in the branch `nik_2448`. Feel free to review that and merge it into your branch, and then we can merge your branch into master and close this PR.

Some comments / explanations behind my edits:

The main one is that it appears that you had to workaround some unintuitive behavior working with recursive lemmas over dependently typed functions, where the types vary at a recursive call. Hence the need for all those carefully placed `unfold`s etc. That must have been frustrating. I've restructured the proof to avoid this and added a detailed comment at the top of foldm_snoc_split' trying to explain what I did. 

Overall, my edits to the proof include:

* Ensuring that the statement of the lemma in the interface and the statement of the same lemma in the implementation file match exactly, rather than using slightly different types and relying on F* to implicitly prove those types compatible.

* Avoiding the use of `unfold` 

* Removing `private` qualifiers: They are unnecessary in .fst files that have .fstis. And we generally do not mark symbols in an .fsti private, since inevitably, someone will eventually want to write a proof that mentions these symbols and get stuck. So, as a general point of style, we use `private` only in very special cases.

* Reducing the reliance on quantifiers without patterns (introduced via Classica.forall_intro etc.), and instead using quantifiers that are explicitly annotated with patterns.

* Plus some general formatting things, indentation conventions etc.

**Comment by hacklex** [comment]
Thanks a lot! It was quite insightful read for me! I added your edits to my branch, ready to merge the PR!

Say, what is the precise difference between `Tot (squash (x))` and `Lemma (x)`? How does one decide when to use which?

**Comment by nikswamy** [comment]
`Tot (squash x)` and `Lemma x` are coercible to each other, in both directions.

I usually use `Lemma x`, unless I have some specific reason to work with the proof of `x` itself. 

This particular example was pretty unusual. It's perhaps an instance of the dependently typed indices getting more in the way of a proof rather than simplifying it. To deal with it, I had to explicitly manipulate the squashed proof a bit.

**Comment by hacklex** [comment]
But Tot(squash x) sometimes works when Lemma x fails?

**Pull request merged**
