### PR TITLE
Improve path handling for cygwin

### PR DESCRIPTION
**Pull request by andreas23**
* Introduce a Makefile variable OCAMLPATH, which then is used to set the environment variable of the same name. Make sure it's translated to a native path on Cygwin
* Introduce ULIB_ML_NATIVE, which is the native path translation of ULIB_ML

### CODE REVIEW

**Comment by msprotz** [comment]
@darrenge not getting CI for this pull request either... thanks

**Comment by darrenge** [comment]
Submitted to VSTS people to look at

**Comment by msprotz** [comment]
@andreas23 do we want to keep this, or shall we just close it, since the Everest script advises you to set your FSTAR_HOME using $(cygpath -m)?

**Comment by andreas23** [comment]
Let's close it then.

**Pull request closed without merging**
