### PR TITLE
Proves stability of Insertion Sort and Merge Sort

### PR DESCRIPTION
**Pull request by A-Manning**
There are many comments in the examples expressing intent to eventually make sorting algorithms generic; This is a step towards that.

### CODE REVIEW

**Comment by A-Manning** [comment]
@catalin-hritcu  Latest commit includes verifying stability of merge sort, as per https://github.com/FStarLang/FStar/wiki/Project-topics-on-F*

**Comment by kyoDralliam** [comment]
@catalin-hritcu asked me to do a review of this code. I think we should merge it on master after some minor tweaking.
One question though : What's the point of the added properties to ListProperties ? They does not seem to be needed anywhere and rev_cons is pretty unnatural to me. (And lib/* should not be modified anymore unless it is needed for some compiler internals). Unless there is some string reason that I missed I'd rather remove these changes.

Some more general comments : 
- Do not bind unused variables (it's useless, complexifies slightly the code and leads to shadowing errors)
- Refined types can misbehave in some cases, use an ensure clause (with Pure) when you want to assert something of the return value of a function unless there is some really specific need
- Consider generating hint files and commiting them along in your pull request
  
Here is a patch of some modifications I did when reviewing [review.zip](https://github.com/FStarLang/FStar/files/676978/review.zip) (including an update for ome breaking syntactic changes)

Another question/enhancement proposition (not needed before merging of course) : could these sorts be made tail-recursive ?

**Comment by A-Manning** [comment]
> What's the point of the added properties to ListProperties ? They does not seem to be needed anywhere and rev_cons is pretty unnatural to me. 

IIRC I used those in earlier versions of the code, but they are no longer needed. I can remove them if you'd like. 

> (And lib/* should not be modified anymore unless it is needed for some compiler internals). 

I think that would have been done in error, I'll remove it from the PR.

Regarding review.zip:
Style changes are all fine, and thanks for correcting my mistake of mixing up commutativity and transitivity.
Various lemmas that I used seem to no longer be needed, although they were with F* 0.9.3. If they can be removed, then that's great! 

> Do not bind unused variables (it's useless, complexifies slightly the code and leads to shadowing errors)

I'm not sure what you mean here, can you show me an example of what you mean?

> Refined types can misbehave in some cases, use an ensure clause (with Pure) when you want to assert something of the return value of a function unless there is some really specific need

Can you elaborate as to when refinement types misbehave? Does the Pure effect also prove termination, like Tot? If so, that doesn't seem very clear. 

> Consider generating hint files and commiting them along in your pull request

Will do.

>Another question/enhancement proposition (not needed before merging of course) : could these sorts be made tail-recursive ?

To my knowledge, merge sort cannot be made tail-recursive, see here. http://cs.stackexchange.com/a/13145/51356
Insertion sort can be done with folds, as shown here https://cseweb.ucsd.edu/classes/wi11/cse130/discussion/ocaml-fold.pdf. 
I may revisit trying to prove stability of a tail-recursive version later.

**Comment by kyoDralliam** [comment]
About unused variables, it's just that you are sometimes pattern matching on some object (e.g. a list) just to know something about its structure (it has at least 2 elements) without using the subterms (the two first elements). In that pretty specific case I prefer using `_` rather than a variable pattern. It gives more precise information about the intended meaning of your pattern.

You can somewhat think of Tot as Pure with a `True` require clause. In particular Pure is also a total effect on its domain of definition (which is the subtype of the domain refined by the require clause). And `Tot a{ phi }` should be the same thing as `Pure a (requires True) (ensures phi)`.

When I'm saying that a refinement type misbehave I just mean that if you give a term of type `a{ phi }` to a function waiting for an argument of type `a{ psi }` where the two formula `phi` and `psi` are unrelated, F* sometimes needs an explicit annotation indicating to drop the first refinement.

I'll wait for your cleanup and merge it if everything seems OK. By the way, is your other PR still needed ? It doesn't seem so even though it still has its own interest.

**Comment by A-Manning** [comment]
@kyoDralliam 

Cheers for the explanation.

I've added hints, as requested, and removed changes to /lib/. Since you merged my other commit, this no longer contains changes to /ulib/. I've applied your .diff file as well.

**Pull request merged**
