### PR TITLE
Add two lemmas in FStar.String.fsti

### PR DESCRIPTION
**Pull request by Kachoc**
This tiny PR adds two (admitted) lemmas to FStar.String.fsti

### CODE REVIEW

**Comment by Kachoc** [comment]
@protz after wrapping up the work on the string file in Noise*, I ended up with those two remaining lemmas

**Comment by aseemr** [comment]
Hi @Kachoc :

Thanks for the PR, these are useful additions to the library. A couple of comments:

* We can implement one of these lemmas using the other, e.g.:

```
let index_list_of_string (s:string) (i : nat{i < length s})
  : Lemma (List.Tot.index (list_of_string s) i == index s i)
  = index_string_of_list (list_of_string s) i;
     string_of_list_of_string s
```

* We could also define the `index` function itself as `L.index (list_of_string s)`. This is going towards giving a model to the string interface as a list of characters. But if we just added this defn., we would at least be able to implement the two lemmas you need. One catch would be to make sure that this function doesn't get reduced (as it has native support in the normalizer), for which we could do something like:

```
module L = FStar.List.Tot

irreducible  //don't reduce it in the normalizer or the smt solver
let index (s:string) (n:nat {n < length s})
  : Tot (c:char{c == L.index (list_of_string s) n})
  = L.index (list_of_string s) n
```

after which:

```
let index_list_of_string (s:string) (i : nat{i < length s})
  : Lemma (L.index (list_of_string s) i == index s i) = ()

let index_string_of_list (l:list char) (i : nat{i < L.length l}) :
  Lemma (
    (**) list_of_string_of_list l; // necessary to get equality between the lengths
    index (string_of_list l) i == L.index l i) =
  list_of_string_of_list l;
  index_list_of_string (string_of_list l) i;
  list_of_string_of_list l
```

Of course if you are interested and have cycles to provide a model for the whole interface, then these would move to the `.fst` (i.e. no need for the `irreducible` keyword).

**Comment by aseemr** [comment]
For the purposes of the PR, what do you think about just implementing one of the lemmas as per my first comment?

**Comment by Kachoc** [comment]
Thanks a lot for your detailed review @aseemr ! :)
I actually hesitated to redefine `index` as `L.index (list_of_string s) n` but was afraid by the reduction issues about which you provide a solution. Still, I also think that even if the definition of `index` ends up being `let index s n = L.index (list_of_string s) n`, it should be hidden in the .fst (once strings have a model).
But as you suggest, I think it is a good idea to only assume one lemma and use it to prove the second one and I will update the PR accordingly.

**Pull request merged**
