### PR TITLE
[LSP] Start off with a wireframe

### PR DESCRIPTION
**Pull request by artagnon**
The implementation can be tested with [vsfstar](https://github.com/artagnon/vsfstar). It currently does not advertise any capabilities, so it's a no-op. See #1736 for more.

### CODE REVIEW

**Comment by artagnon** [comment]
FStar-Linux (uregressions) seems to have a breakage (reported to me on Slack): see [this](https://everestlogstorage.blob.core.windows.net/fstar-linux/buildlogfile_FStar-Linux-20190512-4.html).

**Comment by nikswamy** [comment]
Thanks for all the work @artagnon. I want to encourage you to keep pursuing this direction.

But, I'm not sure why this work should be merged to master at the moment. It's still quite incomplete, right?

Welcoming other opinions … @mtzguido @aseemr @catalin-hritcu et al.

**Comment by artagnon** [comment]
Hi @nikswamy. If we were to wait until there's something working before merging into master, it would look like a gigantic pull request with some 100 commits, and would increase the review burden. The PR would also be a pain to merge/rebase in case of any conflicts. Another reason I prefer developing in small pull requests is so that debugging is easy: I found the bug in the other PR easily using git-bisect because of this.

**Comment by nikswamy** [comment]
On the other hand, I don't yet have a clear sense of the scope of the feature, how to complete it etc., especially with regards to how to implement incremental checking of F* files, similar to fstar-mode.el etc.

I am wary of assuming the technical debt of maintaining this chunk of work without knowing if it will come to fruition at all.

**Comment by artagnon** [comment]
Good points. At the very least, I think it should be clear how auto-completion and jump-to-definition would work in vscode from #1744: in the worst case, this work would support those two functionalities in all the editors, in a single buffer. Additionally, I think it should be easy enough to revert the work if it doesn't come to fruition.

As a middle ground, what's the least you'd like to see before merging?

**Comment by nikswamy** [comment]
I think it would be useful to have support for F* in other editors, like VSCode, Vim etc., even if they do not, in the short term, support all the features of fstar-mode.el.

If that support included the ability to:
- edit multiple F* source files
- have syntax highlighting
- launch the F* language server in a file/project-specific manner (e.g., providing appropriate include paths)
- show the type of a symbol
- jump to its definition

then this would be a very useful unit of work and I'd be delighted to merge and help maintain the feature. I might even use VS code myself to edit F* source code in a non-verified setting, e.g., when editing compiler source files.

Do you think that's a reasonable feature set as a criterion for merging?

**Comment by artagnon** [comment]
Yes, it sounds entirely reasonable. I'll report on the progress shortly.

**Comment by artagnon** [comment]
Done. Check out the screencast [here](https://github.com/artagnon/vsfstar#vsfstar).

**Comment by nikswamy** [comment]
thanks for your patience.

**Pull request merged**
