### PR TITLE
Convert Huffman project to new format

### PR DESCRIPTION
**Pull request by kant2002**
Also add README with sample how to run

### CODE REVIEW

**Comment by kant2002** [comment]
cc @aseemr can we land this cleanup PR?

**Comment by aseemr** [comment]
Thanks for the PR @kant2002.

I tried to run it on my machine, but I get the following error(s) in both BinarySearch and Huffman:

```
/home/aseem/tmp/FStar/examples/algorithms/Huffman/extracted/Huffman.fs(3,6): error FS0039: The namespace or module 'Prims' is not defined. Maybe you want one of the following:   Primitives [/home/aseem/tmp/FStar/examples/algorithms/Huffman/Huffman.fsproj]
/home/aseem/tmp/FStar/examples/algorithms/Huffman/extracted/Huffman.fs(4,6): error FS0039: The namespace or module 'FStar_Pervasives' is not defined. [/home/aseem/tmp/FStar/examples/algorithms/Huffman/Huffman.fsproj]
```

followed by more such errors.

Before these errors, there is also a warning:

```
/usr/share/dotnet/sdk/6.0.302/Microsoft.Common.CurrentVersion.targets(2302,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ulibfs". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/aseem/tmp/FStar/examples/algorithms/Huffman/Huffman.fsproj]
/home/aseem/tmp/FStar/examples/algorithms/Huffman/extracted/Huffman.fs(1,1): warning FS0062: This construct is for ML compatibility. Consider using a file with extension '.ml' or '.mli' instead. You can disable this warning by using '--mlcompatibility' or '--nowarn:62'. [/home/aseem/tmp/FStar/examples/algorithms/Huffman/Huffman.fsproj]
```

Should I build something more? If so, can we add that step to the README(s)?

**Comment by kant2002** [comment]
I think only step which is needed is to built ulib in F#. which IIRC done using following command `make -C src ulib-in-fsharp`. I do agree that documentation probably needed. What place do you want me put some notes about that?

**Comment by aseemr** [comment]
Great, yes, that works. May be just in respective READMEs (examples/Huffman/README.md` etc.)?

**Comment by kant2002** [comment]
I add short instructions for building ulib in F#.

**Comment by aseemr** [comment]
Thanks @kant2002!

**Pull request merged**
