### PR TITLE
Markulf intervals

### PR DESCRIPTION
**Pull request by markulf**
a didactic example based on 
https://www.joachim-breitner.de/blog/734-Finding_bugs_in_Haskell_code_by_proving_it

### CODE REVIEW

**Comment by nikswamy** [comment]
This is pretty nice ... would be good to merge it. Also, @markulf, would you be interested in doing an F* blog post based on this?

**Comment by catalin-hritcu** [comment]
@markulf From today's discussion with @aseemr-msr, this is ready to merge, but you need to sign the CLA before that can happen :)

**Comment by markulf** [comment]
oldest pull request ever, just signed the CLA

**Comment by nikswamy** [comment]
will resolve and try to merge ASAP

**Comment by aseemr** [comment]
Finally! : )

**Pull request merged**
