### PR TITLE
Removing support for fsdoc in favor of fstardoc

### PR DESCRIPTION
**Pull request by nikswamy**
Dear all, 

As discussed in #1877, we planned to remove support for fsdoc, instead migrating to the use of a lighter weight documentation generator fstardoc that @jaybosamiya has been building. 

In short, going forward, we will generate documentation directly from F* source files using a standalone script rather than trying to parse and then print back comments associated with specific AST elements. You can see .scripts/fstardoc for an example of how that is meant to work.

So, towards removing fsdoc, this pull request has the following features:

* Removes all special support in the parser for fsdoc comments. This should hopefully reduce brittleness in the parser when parsing comments, one of the pain points so far in using fsdoc.

* Removes the fsdoc nodes in the Parser.AST, instead treating `(** *)` comments as just normal comments. 
- This means that fsdoc comments are no longer associated with top-level definition as `Comment` attributes. 

- It also means that the interactive mode, which used to support looking up the comments associated with an identifier no longer supports this feature in any meaningful way. I did not remove the documentation query from the interactive mode's API, since I hope we can mimic the documentation lookup functionality in some other way, e.g., by relying on position information associated with identifiers and comments to look up comments that just precede the location of the identifier. We are already using this kind of position information to print comments in the pretty printer---it would be nice to do that for the interactive queries too, but I have not done this yet.

We have discussed this for a long time, but I realize that removing this feature altogether may still be quite contentious. Please do chime in with your opinion, one way or another. Thanks!

### CODE REVIEW

**Comment by jaybosamiya** [comment]
I really like that we'll now be able to use `(** *)` style comments without the interactive mode just dying out due to parser brittleness. This will definitely be a massive gain imho for people to start writing more docs as they go along with their proofs.

As far as the interactive mode goes, if I understand correctly, this would mean that `C-c C-s C-d` in the Emacs mode would be impacted. Is there anything else that I'm missing for usage?

**Comment by nikswamy** [comment]
Thanks for the comments @jaybosamiya 

Yes, only `C-c C-s C-d` would be impacted. That key combination triggers the following query to F*

```
 ... "requested-info":["type","defined-at","documentation"]
```

F* would still respond with the type and the defined location. It's just that the doc string would be empty, until we find some other way to associate comments with definitions.

**Comment by mtzguido** [comment]
> * I hope we can mimic the documentation lookup functionality in some other way, e.g., by relying on position information associated with identifiers and comments to look up comments that just precede the location of the identifier

Big +1 from me here. It would be nice to support this feature while keeping the compiler completely agnostic to it.

I took a look at the diff and it seems reasonable.

**Comment by aseemr** [comment]
The changes look fine to me as well, thanks!

**Pull request merged**
