### PR TITLE
Disabled more output with --silent.

### PR DESCRIPTION
**Pull request by wintersteiger**
A special request from @fournet .

### CODE REVIEW

**Comment by mtzguido** [comment]
Any objections to merging this? It seems good to me. I noticed `--silent` has no explanation in the option list, I'll add one.

**Comment by aseemr** [comment]
Sorry, I don't know the intent of the flag. Where else is it used? Can we instead remove it and move the print statements under some debug flag?

**Comment by mtzguido** [comment]
I think it's meant to not print any output except critical one. So no "Verified module X (XXX ms)" or "All verification conditions discharged successfully". Seems worthwhile to keep, IMO, but I don't feel strongly about it. (Cédric might :) )

**Comment by nikswamy** [comment]
Seems simple and useful enough. @wintersteiger, please merge. If you don't mind, while you're at it, you might consider improving the `--help` message for the --silent option at src/basic/FStar.Options.fs

**Pull request merged**
