### PR TITLE
Fix `smaller` predicates for reflections

### PR DESCRIPTION
**Pull request by W95Psp**
Hi,

I was using the reflection API in a total context and found some `inspect_*` primitive were lacking refinements, forcing me to add `admit`s about termination of some of my functions.

Hence, this PR adds refinements on the builtins `inspect_bv`, `inspect_lb` and `inspect_binder` to specify that inspecting a bv/lb/binder `x` results in a view that is smaller than `x`.
It also fixes and simplifies some of those `smaller` functions that sometimes missed some `<<` relations.

### CODE REVIEW

**Comment by mtzguido** [comment]
This looks good to me in general, but seeing the lemmas:
```fstar
val pack_inspect_comp_inv : (c:comp) -> Lemma (pack_comp (inspect_comp c) == c)
val inspect_pack_comp_inv : (cv:comp_view) -> Lemma (inspect_comp (pack_comp cv) == cv)
```
got me thinking on whether this is really true, and in fact it's not even true for terms, and we currently have an inconsistency:
```fstar
module Inco

open FStar.Reflection

let t0 : term       = `(1 <: int)
let t1 : term_view  = inspect_ln t0
let t2 : term       = pack_ln t1

let s0 = term_to_string t0
let s2 = term_to_string t2

let falso () : Lemma False =
  pack_inspect_inv t0;
  assert_norm (s0 <> s2);
  ()
```
Ascriptions are ignored by `inspect_ln`, causing the issue. In general I think we cannot assert that `pack . inspect` is the identity (but the other way around may be OK).

`term_to_string` should probably be a TAC function instead of Tot, but I think we will anyway have issues with other builtin functions on terms, such as `free_bvs`

Seems like I can remove the `pack_inspect_inv` axiom without fallout, will do so soon. This PR does not really make use of the analogous axiom for computations, does it?

**Comment by nikswamy** [comment]
@mtzguido : I'm wondering why you think `brs << t` is risky. Is it because it is heterogeneous? If so, the sub-term ordering on inductives that F* generates is routinely heterogeneous. Maybe I'm missing something?

**Comment by mtzguido** [comment]
I was slightly worried about being able to conclude that `term << t` from that (since the Cons/Nil constructors mention the type of the list). If that type could be made into something with more structure (a refinement?) then perhaps some mutual recursion could cause a loop, or at least that was what I was thinking about.

But 1) I think we don't get that the type precedes the list and 2) the type is just constantly `term`, so nothing bad should happen?

And actually, IIRC the original reason the `smaller` relation exists is to avoid these "sketchy" precedes. Otherwise, we could just define:
```fstar
val inspect_ln : t:term -> tv:term_view{tv << t}
```
but maybe that's fine?

**Comment by nikswamy** [comment]
Actually, this one below definitely looks problematic to me:

```
val inspect_ln : t:term -> tv:term_view{tv << t}
```

since inspect_ln is really just a view change, the returned `tv` really isn't smaller than the argument `t`.

This smaller relation is saying that the sub-terms of `tv` are smaller than `t`.

**Comment by mtzguido** [comment]
I agree that it's odd, but... you can only do "one step" of inspection, so it doesn't help in constructing a infinite descending chain. Say `inspect t == Ctor a1 a2 ... an`, the only way to keep descending is in one of `a_i`, which should(*) be (strict) subterms of `t`, or plain values, or maybe lists of strict subterms, etc.

If there's nothing weird like recursing through other types, then I think this is fine. It can also be "modelled" as:
- Take terms `t` to be `(t, 1)`.
- Take the view for `t` to be `(t, 0)`.

Then this rule is just stating the lexicographic ordering (wrt being a subterm and `<`) of this tuple type.

Not sure if I'm missing any interactions with other rules for `<<`.

(*) my main concern is whether this "should" will always hold.

**Comment by mtzguido** [comment]
As for returning ascriptions: I just passed regressions locally after fixing `inspect`, but I had to unascribe everywhere in `Steel.Effect.Common`, which is not ideal, I'll look into it more to see why exactly it fails without it.

As for pack/inspect being inverses, while I don't have a counterexample now, what about adding the following precondition to the lemma?
```diff
-val pack_inspect_inv : (t:term) -> Lemma (pack_ln (inspect_ln t) == t)
+val pack_inspect_inv : (t:term) -> Lemma (~(Tv_Unknown? (inspect_ln t)) ==> pack_ln (inspect_ln t) == t)
```
That way we could still cop out and return `Tv_Unknown` if something is not faithfully encoded?

**Comment by mtzguido** [comment]
Posted my changes in #2715, we could keep discussing here.

**Comment by W95Psp** [comment]
Concerning the issue with partial reflection and `Tv_Unknown`, if I'm not mistaken (looking at `inspect_ln` implementation after your PR #2715), the reflection API only misses the following three cases: `Tm_delayed`, `Tm_lazy`, and `Tm_quoted`. 

I think if we match `Tm_delayed`, `Tm_lazy`, this should be a hard error (this should never happen, right?).
And then, for `Tm_quoted`, I've started working on reflecting quote with PR #2673, but I have an error (I have to look at it again).

My point is: if we have a reflection for quotations, I think the last wildcard branch of `inspect_ln` (or `inspect`) should not be a `Warning_CantInspect` warning, but a hard error, and then there's no need to require `(~(Tv_Unknown? (inspect_ln t))` as a precondition of lemma `pack_inspect_inv`.

**Comment by mtzguido** [comment]
I think it's hairier than that. Any `_` in the pattern match that `inspect` does is a possible inconsistency, and requires reviewing every other primitive taking a `term` to see that they also ignore that difference. This includes the metadata of `Tm_meta` (currently ignored, but may be printed), the effect label on ascriptions (this seems OK), or the attributes in the arguments of `Tm_app` nodes (we can't write one of those.. but maybe we can get our hands on a term with such an attribute somehow?).

Also, the term_view is intentionally canonical wrt the shape of arrows, but `Syntax.Util.term_eq` currently distinguishes them, so:

```fstar
let t1 = `(int -> int -> int)
let t2 = pack_ln (inspect_ln t1)

let bad () : Lemma False =
  assert_norm (term_eq t1 t1);
  assert_norm (~(term_eq t1 t2));
  pack_inspect_inv t1;
  assert False
```
As soon as any reflection function distinguishes terms with an equal view, we're done. (Note `term_eq` has no interesting spec either.) Note also that my suggestion about `Tv_Unknown` does not help.

These are all things we can fix, but I wonder if having this strong version of the lemma will make such inconsistencies pop up more often.

**Comment by nikswamy** [comment]
Hi @mtzguido @W95Psp , this is an interesting discussion with lots of subtle points. Guido's last remark has me especially worried.

What do you think about only retaining one direction of this axiom, i.e., inspect_pack_inv. That is, if you pack a term and then inspect it, you get back what you started with. In other words, for everything that is reflected in the view syntax, inspect is faithful.  For things outside it, e.g., n-ary arrows and other stuff that may not yet be supported in the view syntax, we say nothing.

I have to check whether only having this one direction of inverse would be sufficient for some of my developments, but, meanwhile, do you think this is a worthwhile, safer option to consider?

**Comment by mtzguido** [comment]
Yes, i think that lemma is more easily maintained. Still some care is needed: for example imagine that pack were to deeply flatten arrows, and we somehow get our hands on a non-flattened `a -> (b ->c)`. In that case packing `Tv_Arrow (b, t)` and inspecting it would return a slightly different t.

Another route to fixing this is to _never_ expose reflection functions as Tot unless they behave exactly as if implemented via the view. For instance we can replace the exported `term_eq` (which is Syntax.Util.term_eq) with another variant implemented in the reflection modules that matches on terms exclusively via inspect. In that way it would just be an optimization of what we can already write in userspace.

**Comment by mtzguido** [comment]
Hi, maybe we can merge this? I would still like to investigate the SMT axioms for changing `smaller` into `<<`, but if others are all convinced we could also batch that into this one.

I'm doing several changes to reflection/tactics and will probably conflict with this PR, so getting it to master would be good.

**Comment by W95Psp** [comment]
Hi, yes, absolutely! I plan to rework this PR tomorrow morning (French time), I didn't have any time to do so today

**Comment by mtzguido** [comment]
Ah, no rush! I thought it was already mergeable :-)

**Comment by W95Psp** [comment]
Oh, you meant merging as is? 
Then yeah, I guess that's mergeable already, but then changing `smaller` into `<<` will more or less revert most of the commits from this PR. Well, actually maybe changes to `Reflection.Derived.Lemmas` will still be useful.

I'm fine with merging now personally then :) (the rework I was referring to was about eliminating `smaller` in favor or `<<`, so if you've got that somewhere on a branch, that's easier to just merge as is)

**Comment by mtzguido** [comment]
Right, I meant as-is. I would prefer to investigate a bit more before deciding to discard `smaller` for `<<`.

**Pull request merged**
