### PR TITLE
Remove --use_extracted_interfaces

### PR DESCRIPTION
**Pull request by mtzguido**
This removes the underlying code and makes the option a no-op except for warning about it, though we can also just remove it outright.

This got an everest green here:
https://everestlogstorage.blob.core.windows.net/everest-linux/buildlogfile_Everest-Linux-20200717-13.html

The option is already disabled in F*'s `ulib/` in master as of today. This PR removes it from everywhere that remains (examples mostly), and also removes the CI run for `Pkg.fst-ver` with the flag on.

### CODE REVIEW

**Comment by aseemr** [comment]
Many thanks @mtzguido for taking it up, this looks good to me.

I think we should also take this as an opportunity to remove the `abstract` keyword (without `--use_extracted_interfaces` it is unsound anyway). I branched off of your branch and removed it in the `aseem_no_abstract` branch, perhaps I can push your changes from that branch itself? Thanks!

**Comment by mtzguido** [comment]
Sounds great to me. I posted this for discussion on tomorrow's meeting but if you feel like merging before that I wouldn't mind.

**Comment by msprotz** [comment]
HACL* still relies on this flag for the Vale files. Pinging @Chris-Hawblitzel do you know why?

**Comment by Chris-Hawblitzel** [comment]
@msprotz It comes from:

https://github.com/project-everest/vale/pull/20
https://github.com/project-everest/vale/commit/16ac9623bca45da7a888d99c7bbf4397aba5c179

but otherwise I know of no reason why it has to be there

**Comment by msprotz** [comment]
Thanks, pinging @aseemr in preparation for tomorrow's meeting see if he can remember why these were needed. Otherwise it'll just have to be a big regression test.

**Comment by aseemr** [comment]
I have tried hacl CI with this flag removed and had a green.

**Pull request closed without merging**
