### PR TITLE
Low* freezable buffers

### PR DESCRIPTION
**Pull request by aseemr**
A library for freezable buffers of `u8`.

It maintains the current frozen-up-to index (a `u32`) in the first 4 bytes of the buffer (the value of first 4 bytes is a `u32` that is the first writable index in the buffer). Clients can call `freeze` to freeze up-to an input index after which the buffer cannot be mutated until that index.

The library provides two witness-able predicates: one for the contents of a slice that falls within the `[4, w)` range (where `w` is the current frozen-up-to index), and one for the value of `w` itself (since it also increases monotonically).

Also including some unit-tests for it in `examples`.

### CODE REVIEW

**Comment by msprotz** [comment]
Is this easily reusable to offer arbitrarily freezable buffers that are frozen wholesale without the index encoded in the first four bytes? (Thinking about the AEAD use-case for freezable buffers where we don't care too much about encoding the length, since it's allocate-write-then-freeze-everything.)

**Comment by aseemr** [comment]
You could use these buffers for that also, just keep writing and then freeze at the end. But it will still use the first four bytes for writing the frozen index. If you don't want to use 4 bytes, we can do it with using may be just a byte (to keep a single bit whether the buffer has been frozen or not). Not sure if we can do it without using even that.

**Comment by msprotz** [comment]
Ah, so the interface we looked at together (https://github.com/project-everest/hacl-star/blob/protz_aead/providers/evercrypt/EverCrypt.AEAD.fsti) would still need an extra bit of space inside the ekv type in order to be implementable?

**Comment by aseemr** [comment]
For the case of buffers that are writable until frozen, we could do without keeping any state in the buffer itself, provided extraction can erase `ref` of `erased bool`. Here is a rough sketch:

```
module LowStar.FreezeOnceBuffer

open FStar.HyperStack.ST

include LowStar.Monotonic.Buffer

module P = FStar.Preorder
module G = FStar.Ghost

module Seq = FStar.Seq

module HS = FStar.HyperStack
module HST = FStar.HyperStack.ST

(*
 * Rough sketch for buffers that are writable until frozen
 *
 * Using an auxiliary reference to erased bool to keep the state
 *)

let ref_preorder : P.preorder (G.erased bool) =
  fun b1 b2 ->
  b2t (G.reveal b1) ==> b2t (G.reveal b2)

type ref_t = mref (G.erased bool) ref_preorder

let ref_is_true (r:ref_t) : HST.mem_predicate =
  fun h -> G.reveal (HS.sel h r) == true

let buf_preorder (r:ref_t) (#a:Type0) : srel a =
  fun s1 s2 ->
  HST.token_p r (ref_is_true r) ==> Seq.equal s1 s2

let buf_frozen_at (r:ref_t) (#a:Type0) (snap:G.erased (Seq.seq a)) : spred a =
  fun s -> HST.token_p r (ref_is_true r) /\ Seq.equal (G.reveal snap) s

let test (r:ref_t) (a:Type0) (snap:G.erased (Seq.seq a)) =
  assert (HST.stable_on (ref_is_true r) r);
  assert (stable_on (buf_frozen_at r snap) (buf_preorder r))

type buffer (a:Type0) =
  b:(r:ref_t & mbuffer a (buf_preorder r) (buf_preorder r))
    {loc_disjoint (loc_mreference (dfst b)) (loc_buffer (dsnd b))}

let is_live (#a:Type0) (h:HS.mem) (b:buffer a) =
  HS.contains h (dfst b) /\ live h (dsnd b)

let witnessed_at (#a:Type0) (b:buffer a) (s:G.erased (Seq.seq a)) =
  witnessed (dsnd b) (buf_frozen_at (dfst b) s)

let freeze (#a:Type0) (b:buffer a) (s:G.erased (Seq.seq a))
  : ST unit
       (requires (fun h ->
         is_live h b /\
         Seq.equal (as_seq h (dsnd b)) (G.reveal s)))
       (ensures  (fun h0 _ h1 ->
         modifies (loc_mreference (dfst b)) h0 h1 /\
         b `witnessed_at` s))
  = let r = dfst b in
    r := G.hide true;
    HST.witness_p r (ref_is_true r);
    witness_p (dsnd b) (buf_frozen_at r s)    

let recall_contents (#a:Type0) (b:buffer a) (s:G.erased (Seq.seq a))
  : ST unit
       (requires (fun h ->
         is_live h b /\
	 b `witnessed_at` s))
       (ensures  (fun h0 _ h1 ->
         h0 == h1 /\
	 as_seq h1 (dsnd b) == G.reveal s))
  = recall_p (dsnd b) (buf_frozen_at (dfst b) s)
```

cc @nikswamy

**Comment by msprotz** [comment]
I just fixed kremlin, so now a dependent pair of a buffer and an erased reference should incur no code-generation overhead.

**Comment by aseemr** [comment]
Cool. Though I am still a bit suspicious if this would work, proving the preorder while writing may not work. I will try writing that API too.

**Comment by msprotz** [comment]
Thanks -- that would be useful for EverCrypt.

**Pull request merged**
