### PR TITLE
Separate data and control in the interactive protocol

### LINKED ISSUE #361: Skip comments in interactive mode
A file like
```F#
module F
(*
#endif
*)
```
fails to typecheck with the --in flag because the `#endif` inside the comment is interpreted as the interactive mode *command* #end. This kind of comments is common in miTLS, so it would be nice if the interactive mode ignored them.

### PR DESCRIPTION
**Pull request by cpitclaudel**
Apart from using JSON messages, the new protocol is essentially the same as the
old one.  Significant differences:

- Instead of crashing, invalid requests (missing fields, unsupported queries,
  etc) now cause F* to print a reasonably helpful diagnostic message.
- Each query now includes an editor-supplied query id, and each response
  contains the id of the corresponding query.
- Some of the queries were renamed (info → lookup, completions → autocomplete)
  for consistency (all query names are now verbs).
- Messages that F* used to print to stdout or stderr are now translated into
  proper JSON messages and labeled with a severity level (a review of these
  messages is needed to decide which of these should be turned into properly
  reported errors or warnings including range information).
- F* now prints the protocol's version and a list of supported interactive
  features before starting the interactive loop.  This lets the Emacs mode do
  dynamic capability detection instead of relying on version numbers. The same
  information is available through a new "describe-protocol" query.
- A failed “push” doesn't require the editor to immediately send a corresponding
  “pop” any more — instead, the pop happens automatically.

Fixes #361, #366, and #828.  This PR includes #955, so that one should be debated and merged first.  I also added a small test suite for the new interactive protocol.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Testing this should be easy: I already updated fstar-mode, and this PR includes an updated OCaml snapshot (the a commit in this PR that sets the version number to 42 is there to make it easy for fstar-mode to detect when it needs to use the new JSON-based protocol; we should of course change this number before merging)

**Comment by cpitclaudel** [comment]
Easy review link: https://github.com/FStarLang/FStar/pull/981/files/eab7ab26998780c44e7362131a7eb442cbd9d2bd..1dbe7bd57d2ec8c816aa56df32505d434bed4bd8 (excluding the snapshot and #955)

**Comment by cpitclaudel** [comment]
Rebased on latest master (there was one conflict: https://github.com/FStarLang/FStar/commit/6946f1049047c1aa03e120fdabc230a8acf79c61).

**Comment by cpitclaudel** [comment]
@nikswamy Ok, I think this is ready for merging.  It includes #955, so no need to merge that separately.  Following our discussion:

* `--in` loads the legacy interface (thus there should be no change for interfaces other than Emacs).  The new protocol is obtained with `--ide`
* I removed a leftover `FIXME`.
* I changed the version number to 0.9.4.3

I'll open a separate PR soon with new features based on this protocol.

**Comment by cpitclaudel** [comment]
Rebased and fixed conflicts.

**Comment by nikswamy** [comment]
testing it on my branch now. will merge into master soon

**Pull request merged**
