### PR TITLE
Fix error on fresh install

### PR DESCRIPTION
**Pull request by kant2002**
I did fresh install of OCaml in WSL on Ubuntu 22 and after installing dependencies using `opam install --deps-only .` and installing additionally ocaml-lsp-server (I assume this is inconsequential) I have compilation error I fix errors, but maybe FStar should adopt https://github.com/ocaml-ppx/ocaml-migrate-parsetree to not depends on the OCaml version on the developer machine.

### CODE REVIEW

**Comment by kant2002** [comment]
That' seems to be allow fix https://github.com/ocaml/opam-repository/pull/21990 and supports ppxlib >= 0.26.0

**Comment by aseemr** [comment]
Thanks @kant2002! So it fixes https://github.com/FStarLang/FStar/issues/2681, right?

**Comment by kant2002** [comment]
Yeah. That’s exact error what I was having.

**Comment by aseemr** [comment]
Thanks, much appreciated!

**Comment by R1kM** [comment]
This seems to be a breaking change, as the ppxlib AST for OCaml 5.0 was introduced in ppxlib 0.26.0.
Could we reflect that in the opam requirements?

**Pull request merged**
