### PR TITLE
SMT simplifications

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Unbox all terms
- [ ] Use native Z3 theories whenever possible
- Simplify the fuel handling
  - [ ] `fuel`
  - [ ] `ifuel`
  - [ ] `forallFuel`

### CODE REVIEW

**Comment by nbraud** [comment]
This is a first baby step towards using Z3 more efficiently.

As far as I understand, this is sound because the typechecker would have rejected earlier any term that as ill-typed (ignoring subset types); in particular, the boxing is consistent.
@nikswamy Can you confirm this makes sense?

**Comment by nbraud** [comment]
OK, I see what I broke there.  Fixing this is going to be unfun.
(Unsure why `./everest make && ./everest verify` ran through on my machine, though)

**Comment by msprotz** [comment]
if you can get to the bottom of this I'd love to understand why you didn't have any failures

**Comment by nikswamy** [comment]
Have you seen the F* options:

```
  --smtencoding.elim_box true|false  Toggle a peephole optimization that eliminates redundant uses of boxing/unboxing in the SMT encoding (default 'false')
  --smtencoding.nl_arith_repr native|wrapped|boxwrap  Control the representation of non-linear arithmetic functions in the SMT encoding:
                i.e., if 'boxwrap' use 'Prims.op_Multiply, Prims.op_Division, Prims.op_Modulus';
                if 'native' use '*, div, mod';
                if 'wrapped' use '_mul, _div, _mod : Int*Int -> Int';
                (default 'boxwrap')
  --smtencoding.l_arith_repr native|boxwrap  Toggle the representation of linear arithmetic functions in the SMT encoding:
                i.e., if 'boxwrap', use 'Prims.op_Addition, Prims.op_Subtraction, Prims.op_Minus';
                if 'native', use '+, -, -';
                (default 'boxwrap')
```

How does what you're doing here relate?

**Comment by nbraud** [comment]
@nikswamy That should produce functionally-identical SMT queries.
The goal there was more as a simplification pass of the code in `smtencoding` before I prepare several other patches (esp. w.r.t. how we handle fuel), but it kinda stalled as I was pretty ill in the last few days, and discovered that this breaks some pervasive assumptions in that module.

In any case, we will be talking on Thursday  :)

**Comment by nbraud** [comment]
Closing for now.
As Nikhil pointed out a while ago, avoiding the uninterpreted sort is much more complicated as soon as we hit polymorphic functions.

**Pull request closed without merging**
