### PR TITLE
Initial extraction support for LowStar.ConstBuffer

### PR DESCRIPTION
**Pull request by msprotz**
along with KreMLin extraction & AST changes, and a summary from a discussion related to the soundness of downcasts (removing const)

### CODE REVIEW

**Comment by msprotz** [comment]
I had a successful build of HACL* with this commit and I'm trying to get an everest green as we speak.

Thanks,

Jonathan

**Comment by msprotz** [comment]
See https://github.com/FStarLang/kremlin/blob/protz_const/test/ConstBuffer.fst for a test; note that the feature is also exercised internally by the C89 flavor of HACL*, for a which a lot of pointer-to-structs are introduced (to avoid passing structs by value); these pointers, created internally by kremlin, are marked as const too.

**Comment by aseemr** [comment]
Thanks Jonathan, this looks good to me. A couple of questions regarding the discussion in `LowStar.ConstBuffer`:

* Isn't it always safe to extract `LowStar.ImmutableBuffer t` as `const t*`? Would this be a small change in `FStar.Extraction.Kremlin.fs` now (extract `  | MLTY_Named ([arg], p)` case for `LowStar.ImmutableBuffer.ibuffer` to `TConstBuf`)? If so, can we batch it with this PR?

* Also, in the Low* code, casting away const-ness should always be safe, right? Since the precondition of `cast` requires a proof that its preorder is `MUTABLE`, which means the object could not have originated as `const`?

**Comment by msprotz** [comment]
copy-pasting from slack discussion, for posterity:

> there's a subtlety, which is that because we don't enforce a tight abstraction boundary on ibuffer, it is possible to write a function over mbuffers
> i.e. a function that is polymorphic over buffer and ibuffer
> however, that the function is polymorphic over both kinds is a semantic argument that cannot be trivially deduced via a syntactic criterion (for instance, looking at ML-like parametricity doesn't work, there might be a semantic refinement)
> meaning that any function over mbuffer can receive ibuffer and buffer, and therefore cannot mark its argument as const
> which in turns means that if you mark ibuffers as const, you'll get a C typing error (passing a const pointer to a function that takes a non-const pointer)
> that's why there's the new LowStar.ConstBuffer which enforces a tight abstraction boundary and therefore offers proper modeling of the const qualifier

as to casting the `const` pointer away: this is a very delicate thing to do because of C undefined behavior --  I hope my comments in LowStar.ConstBuffer help explain why there has to be a little bit of reasoning there

**Pull request closed without merging**
