### PR TITLE
docker build

### PR DESCRIPTION
**Pull request by joshjdevl**

### CODE REVIEW

**Comment by catalin-hritcu** [comment]
@joshjdevl  Sorry for the huge delay and thank you for your contribution. From what I can see, there doesn't seem to be much interest in a docker build, but it might be because we don't really use/understand the technology. Should we see this as a replacement for an F\* VM, for our binaries, or as something orthognoal? Or to put it more bluntly, why should we care? :)

**Comment by catalin-hritcu** [comment]
@ad-l  Hey Antoine, did you ever use Docker? :)

**Comment by beurdouche** [comment]
This was actually a great idea, thanks.
We do not need to ask people to install `opam`, `ocaml`,`z3` and `fstar` anymore for occasional uses, like F* schools. Now they can build and deploy a running VM doing `docker build .`

**Comment by beurdouche** [comment]
By commit d1a327c883ea2a1c4a87e1f4147be7a06f4de69d

**Pull request closed without merging**
