### PR TITLE
Bring FStar.Int modules up to par with FStar.UInt

### PR DESCRIPTION
**Pull request by s-zanella**
This brings the `FStar.Int` and `FStar.Int{8,16,31,32,63,64,128}` modules for signed machine integers up to par with the modules for unsigned machine integers. This will allow @kevinmkane to discharge some assumptions he had to make because `FStar.Int` lagged behind.

We clearly didn't honor the note in `FStar.UInt.fst`:
_NOTE: anything that you fix/update here should be reflected in [FStar.Int.fst], which is mostly a copy-paste of this module._

It also strengthens the pre-conditions of signed shift operations to forbid parameters that result in undefined or implementation-defined behavior.

I got a local green on `FStar`. We rarerly use signed integers, so I don't expect major regressions.

### CODE REVIEW

**Comment by s-zanella** [comment]
The build failed because of an infrastructure error. The Docker image built successfully.

**Comment by msprotz** [comment]
We chatted about it in the F* meeting. What happens is that the F* compiler depends on the UInt modules, which in turn brought FStar.Calc in the dependency graph of the compiler. Files that are used in the F* compiler are intepreted with --ml, which changes the default effect annotation to ML instead of Tot. So, the fix is to annotate everything in Calc to be marked as Tot.

This is a classic pitfall which I fell into just a few weeks ago when I tried to add something to FStar.List.

**Comment by s-zanella** [comment]
Thanks @msprotz. I figured out so far and fixed the issue with `Tot` vs `ML` when using `--MLish`: https://github.com/FStarLang/FStar/pull/1692/commits/9846c657eb01ca10e4aad261520caea493642288
It is now failing much later with an error that seems unrelated:
`[STDERR]make: *** [interactive-test] Error 2`

I'll merge `master` again and see if it goes away.

**Comment by msprotz** [comment]
You may have to do `make accept` in `src/tests/interactive` if the changes you observe are only due to renaming and changes of `uu` variable names.

**Comment by s-zanella** [comment]
Thanks for the suggestion @msprotz. Some of the interactive mode tests include positions in `FStar.UInt` in error messages and those changed.

**Comment by s-zanella** [comment]
Can we merge this now?

**Comment by msprotz** [comment]
Looks good to me. I assume there will be no regressions since we don't use signed integers in Everest. Thanks for the cleanup! Much appreciated.

**Pull request merged**
