### PR TITLE
Changed from PAT to using keys

### PR DESCRIPTION
**Pull request by darrenge**
Got the invite for everbld for the repo and that was accepted.

Updated the git clone to use git@github instead of PAT. 

Ran FStar Docs Nightly on my private build and it passed. Looking at logs, there was nothing to commit (docs weren't changed) so it didn't commit, but if there were perms issues, the git clone would not have worked.

I believe this was all that was needed.

### CODE REVIEW

**Comment by sishtiaq** [comment]
Maybe wait until an actual run (change to commit) happens. Coverage!

**Comment by darrenge** [comment]
There hasn't been an update that has caused an update to the docs in 6 days.

**Comment by sishtiaq** [comment]
I'll add a line to a ulib module tomorrow. That should fire it.

**Comment by darrenge** [comment]
Before you do that, make sure that my change was merged first.

**Comment by msprotz** [comment]
You need a colon instead of a slash after the github.com part of the URL, I believe...?

**Comment by darrenge** [comment]
All ready to be merged.

**Comment by msprotz** [comment]
Thanks! Good catch removing the comments.

**Comment by sishtiaq** [comment]
I added a comment to ulib/FStar.List.fst, forcing fsdoc.sh to commit && push. It hangs, waiting for a pswd on the push. See the build log in https://msresearch-ext.visualstudio.com/Everest/_build/index?buildId=5070&_a=summary (the reason you see "Invalid username or password" is 'cos I went to the BuildMachine's console and typed enter for the pswd.

**Comment by sishtiaq** [comment]
I think I fixed it in https://github.com/FStarLang/FStar/commit/1530f2305a3f10407c5119a2e08e434faae2d1da. We needed to push using ssh too.

**Comment by darrenge** [comment]
Great - thanks Samin!

**Pull request merged**
