### PR TITLE
Compilation with MSVS 

### LINKED ISSUE #308: F* doesn't build right on Linux with F# 4.0
F* doesn't build right on Linux [and Cygwin] with the newly released F# 4.0. The build seems to work (although with some warnings):
```
[hritcu@detained pub]$ make -C src      
make: Entering directory '/home/hritcu/Projects/fstar/pub/src'
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/basic.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll  basic/prims-fake.fs basic/profiling.fs basic/util.fsi basic/util.fs basic/bytes.fsi basic/bytes.fs basic/range.fsi basic/range.fs basic/getoptsimple.fsi basic/getoptsimple.fs basic/platform.fsi basic/platform.fs basic/options.fs basic/unionfind.fsi basic/unionfind.fs
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/format.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll  format/format.fsi format/format.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/absyn.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll absyn/syntax.fs absyn/const.fs absyn/visit.fs absyn/util.fs absyn/print.fs absyn/ssyntax.fs

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(104,32): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(105,28): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(216,57): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(216,91): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(216,125): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(217,53): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(219,78): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(219,115): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(221,36): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(221,103): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(223,63): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(380,40): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(380,106): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(382,67): warning FS0044: This construct is deprecated. please use List.item
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/tc.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll tc/tcenv.fsi tc/tcenv.fs tc/recheck.fs tc/normalize.fsi tc/normalize.fs tc/errors.fs tc/rel.fsi tc/rel.fs tc/tcutil.fsi tc/tcutil.fs tc/tc.fs

/home/hritcu/Projects/fstar/pub/src/tc/tcenv.fs(385,24): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tc/rel.fs(1546,18): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tc/rel.fs(1572,30): warning FS0044: This construct is deprecated. please use List.item
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/backend.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/format.dll -r ../bin/tc.dll backend/nameenv.fsi backend/nameenv.fs backend/ml-syntax.fs backend/ocaml-codegen.fsi backend/ocaml-codegen.fs backend/ocaml-asttrans.fsi backend/ocaml-asttrans.fs

/home/hritcu/Projects/fstar/pub/src/backend/ocaml-asttrans.fs(624,25): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[]' may indicate a case not covered by the pattern(s).
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/extraction.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/format.dll -r ../bin/tc.dll extraction/ml-syntax.fs extraction/env.fs extraction/util.fs extraction/ocaml-codegen.fsi extraction/ocaml-codegen.fs extraction/extracttyp.fs extraction/extractexp.fs extraction/extractmod.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/parser.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/tc.dll parser/ast.fs parser/parseutil.fs parser/parse.fs parser/lexhelp.fs parser/lex.fs parser/dsenv.fsi parser/dsenv.fs parser/desugar.fsi parser/desugar.fs parser/parseit.fsi parser/parseit.fs parser/driver.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/tosmt.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/tc.dll tosmt/term.fsi tosmt/term.fs tosmt/z3.fs tosmt/splitcases.fs tosmt/encode.fs

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(274,16): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(366,9): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(388,13): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[]' may indicate a case not covered by the pattern(s).

/home/hritcu/Projects/fstar/pub/src/tosmt/encode.fs(54,24): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tosmt/encode.fs(2027,17): warning FS0025: Incomplete pattern matches on this expression. For example, the value 'Caption (_)' may indicate a case not covered by the pattern(s). However, a pattern rule with a 'when' clause might successfully match this value.
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -o ../bin/fstar-mono.exe -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/format.dll -r ../bin/absyn.dll -r ../bin/backend.dll -r ../bin/extraction.dll -r ../bin/parser.dll -r ../bin/tc.dll -r ../bin/tosmt.dll fstar.fs main.fs
cp ../bin/fstar-mono.sh ../bin/fstar.exe
make: Leaving directory '/home/hritcu/Projects/fstar/pub/src'
```
The obtained `fstar.exe` binary doesn't work well though:
```
[hritcu@detained pub]$ bin/fstar.exe empty.fst 

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
An exception was thrown by the type initializer for <StartupCode$tosmt>.$Microsoft.FStar.ToSMT.Encode

[hritcu@detained pub]$ bin/fstar.exe empty.fst --trace_error              

Unexpected error
An exception was thrown by the type initializer for <StartupCode$tosmt>.$Microsoft.FStar.ToSMT.Encode
  at Microsoft.FStar.FStar.tc_prims () [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.FStar.batch_mode_tc (Microsoft.FSharp.Collections.FSharpList`1 filenames) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.FStar.go[Unit] (Microsoft.FSharp.Core.Unit _arg1) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.FStar.main[Object] () [0x00000] in <filename unknown>:0 

[hritcu@detained pub]$ z3 --version
Z3 version 4.3.2
```
Did anyone try F# 4.0 on Windows?

### PR DESCRIPTION
**Pull request by gsvgit**
Some project changes in order to fix #308 and #408 (on VS only!).
 *  ```--mlcompatibility``` flag is added to some projects to prevent "This construct is deprecated..." warnings.
 *  ```TargetFSharpCoreVersion``` tag is added in order to solve problem with f# target runtime selecting.
 *  Binding redirect for FSharp.Core is updated in app.config to prevent problems with type initializers.

Unfortunately checked only for Windows.

### CODE REVIEW

**Comment by catalin-hritcu** [comment]
Tested this and it didn't break anything on Linux. Can people try it on Windows?

**Comment by s-zanella** [comment]
Works for me. Can we avoid the large unrelated merge in the PR?

**Comment by catalin-hritcu** [comment]
> Works for me.

What system? Can you try it on Windows?

**Comment by s-zanella** [comment]
It works for me on Windows 10 using Visual Studio 2015.
It also worked on Mac OS X using Mono 3.10.0, after installing FSharp.Core 4.0.0 with NuGet:

```
$ mono src/VS/.nuget/NuGet.exe install FSharp.Core -version 4.0.0
$ xbuild src/VS/FStar.sln /target:Clean
$ xbuild src/VS/FStar.sln 
```

Without installing FSharp.Core 4.0.0, I got several warnings

`/Library/Frameworks/Mono.framework/Versions/3.10.0/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Reference 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' not resolved`

**Comment by gsvgit** [comment]
*  ```Private``` tag value is ```true```.
* User specific path removed.
* tests project configuration fixed.
* If problem with building/running on Mac OSX could not be solved by mono and F# updating (seems that F# 4.0 is not installed) then it is possible to use FSharp.Core from Nuget everywhere.

**Comment by s-zanella** [comment]
Thanks.
I did install FSharp.Core 4.0.0 using NuGet, but I had to tell xbuild where to find it.

**Comment by catalin-hritcu** [comment]
Tried to update to F* 4.0 on mono (on Linux) and then use this patch, but the binary I get is still broken (i.e. issue #308 seems still there on mono).
```
[hritcu@detained src]$ make clean
rm -rf *.exe ../bin/basic.dll ../bin/format.dll ../bin/absyn.dll ../bin/extraction.dll ../bin/parser.dll ../bin/tc.dll ../bin/tosmt.dll ../bin/fstar.exe *~ *res
rm -rf ../bin/*.pdb  ../bin/*.mdb ../bin/queries
make -s -C ocaml-output clean
[hritcu@detained src]$ make
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/basic.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll  basic/prims-fake.fs basic/profiling.fs basic/char.fsi basic/char.fs basic/string.fsi basic/string.fs basic/list.fsi basic/list.fs basic/util.fsi basic/util.fs basic/bytes.fsi basic/bytes.fs basic/range.fsi basic/range.fs basic/getoptsimple.fsi basic/getoptsimple.fs basic/platform.fsi basic/platform.fs basic/version.fsi basic/version.fs basic/options.fs basic/unionfind.fsi basic/unionfind.fs
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/format.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll  format/format.fsi format/format.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/absyn.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll absyn/syntax.fs absyn/const.fs absyn/visit.fs absyn/util.fs absyn/print.fs absyn/ssyntax.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/tc.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll tc/tcenv.fsi tc/tcenv.fs tc/recheck.fs tc/normalize.fsi tc/normalize.fs tc/errors.fs tc/rel.fsi tc/rel.fs tc/tcutil.fsi tc/tcutil.fs tc/tc.fs
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/extraction.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/format.dll -r ../bin/tc.dll extraction/ml-syntax.fs extraction/env.fs extraction/util.fs extraction/codegen.fsi extraction/codegen.fs extraction/extracttyp.fs extraction/extractexp.fs extraction/extractmod.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/parser.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/tc.dll parser/ast.fs parser/parseutil.fs parser/parse.fs parser/lexhelp.fs parser/lex.fs parser/dsenv.fsi parser/dsenv.fs parser/desugar.fsi parser/desugar.fs parser/parseit.fsi parser/parseit.fs parser/driver.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/tosmt.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/tc.dll tosmt/term.fsi tosmt/term.fs tosmt/z3.fs tosmt/splitcases.fs tosmt/encode.fs

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(394,13): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[]' may indicate a case not covered by the pattern(s).

/home/hritcu/Projects/fstar/pub/src/tosmt/encode.fs(1156,33): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[_;_]' may indicate a case not covered by the pattern(s).

/home/hritcu/Projects/fstar/pub/src/tosmt/encode.fs(2090,17): warning FS0025: Incomplete pattern matches on this expression. For example, the value 'Caption (_)' may indicate a case not covered by the pattern(s). However, a pattern rule with a 'when' clause might successfully match this value.
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -o ../bin/fstar-mono.exe -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/format.dll -r ../bin/absyn.dll -r ../bin/extraction.dll -r ../bin/parser.dll -r ../bin/tc.dll -r ../bin/tosmt.dll fstar/fstar.fs fstar/main.fs
cp ../bin/fstar-mono.sh ../bin/fstar.exe
[hritcu@detained src]$ cd ../examples 
[hritcu@detained examples]$ make
make -C bug-reports
make[1]: Entering directory '/home/hritcu/Projects/fstar/pub/examples/bug-reports'
../../bin/fstar.exe  --admit_fsi FStar.Set ../../lib/set.fsi ../../lib/heap.fst ../../lib/st.fst ../../lib/all.fst ../../lib/list.fst ../../lib/string.fst bug015.fst bug019.fst bug021.fst bug022.fst bug023.fst bug024.fst bug025.fst bug029.fst bug026.fst bug028.fst bug034.fst bug052.fst bug056.fst bug058.fst bug060.fst bug062.fst bug067.fst bug077.fst bug092.fst bug096.fst bug097b.fst bug101.fst bug103.fst bug111.fst bug116.fst bug117.fst bug122.fst bug124.fst bug139.fst bug148.fst bug155.fst bug161.fst bug162.fst bug170.fst bug175.fst bug178.fst bug179.fst bug181.fst bug184.fst bug184b.fst bug186.fst bug189.fst bug190.fst bug192.fst bug195.fst bug203.fst bug212.fst bug213.fst bug-295.fst bug316.fst bug331.fst bugWildcardTelescopes.fst

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
An exception was thrown by the type initializer for <StartupCode$tosmt>.$FStar.ToSMT.Encode
../Makefile.include:53: recipe for target '.all.ver' failed
make[1]: *** [.all.ver] Error 1
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/examples/bug-reports'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
[hritcu@detained src]$ fsharpc 
F# Compiler for F# 4.0 (Open Source Edition)
```

**Comment by s-zanella** [comment]
I haven't tried with the F# 4.0 compiler since the latest version of Mono is still using F# 3.1. With the F# 3.1 compiler and Mono 4.0.4 (and FSharp.Core 4.4.0.0) I get a functional mono binary. I guess we won't really have to deal with issues with Mono and F# 4.0 until Mono actually uses it, unless we want to be proactive and look into this.

**Comment by catalin-hritcu** [comment]
@s-zanella  F# 4.0 doesn't depend on Mono (the dependency is the other way around). In particular, F# 4.0 seems the default on VS2015 and on my flavor of Linux it's already the default and I need to block updates to keep things working. I thought that the whole point of this patch was fixing #308.

**Comment by s-zanella** [comment]
You're right, I'm confusing the Xamarin MDK/MRE bundle with Mono. Perhaps the fact that Xamarin bundles don't ship with F# 4.0 suggests that Mono and F# 4.0 don't work perfectly together yet?

The goal of this patch is to fix compilation on VS 2015, which it does. Arguably, compilation on Mono with F# 4.0 is less of a priority given that there are better ways of building native binaries for non-VS users.  Issue #308 remains open (it may be worth editing the title to append "..using Mono"), I don't have any solution for it.

**Comment by catalin-hritcu** [comment]
@s-zanella This patch seems generally useful and it's been waiting for almost 2 months. How about merging it in?

**Comment by s-zanella** [comment]
There are still some nits: e.g. unnecessary spacing/line ending changes. I can go through the files and cherry-pick the useful changes.

**Comment by nikswamy** [comment]
This breaks stuff for me. I don't have FSharp.Core 4.4.0.0 on my machine. Where can I find it?

**Comment by nikswamy** [comment]
But it breaks on VS 2013

**Comment by nikswamy** [comment]
Can you please post instructions for how to move forward? My current working state is hosed because of this.

**Comment by catalin-hritcu** [comment]
@nikswamy  you could temporarly check out the version before this change and use that ... or you could revert it for now ... or move it to a branch

**Comment by s-zanella** [comment]
I think VS 2015 should work out of the box. The easiest is probably to
rollback my changes. Should I do it?

**Comment by nikswamy** [comment]
FYI, I'm back in business. 

I installed VS 2015 from here:
https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

Then, I opened FStar.sln in the newly installed VS. It asked me to close the project and update it with FSharp. After I did this, I reopened FStar.sln, reloaded all the projects (which were marked as unavailable), and then built. It seems to work fine now.

**Comment by nikswamy** [comment]
Thanks for making me update ... it's been on my TODO list for a while.

**Comment by catalin-hritcu** [comment]
So we officially require VS 2015 now, right? If so we should document that in INSTALL.md.

I'll also need to update my VM at some point.

**Comment by s-zanella** [comment]
Just in case, I'm attaching a patch for those who can't or don't want to
switch to VS 2015 / F# 4.0.
To apply the patch run this command from the FStar root:

`git apply -R target-fsharp4.patch`

**Comment by s-zanella** [comment]
I'm afraid so. We now require F# 4.0 to compile from the VS solution with
Mono or VS.
There are ways of upgrading to F# 4.0 without switching to VS 2015.

**Comment by catalin-hritcu** [comment]
@s-zanella 
> I'm attaching a patch
Where exactly is it?

> We now require F# 4.0 to compile from the VS solution with Mono or VS.
Didn't know there was a way to use Mono with the VS solution. What do you mean exactly? (afaik xbuild is not really compatible with msbuild)

In any case, if we're globally switching to F# 4.0 fixing #308 becomes crucial. I currently cannot use F# 4.0 on Linux.

**Comment by s-zanella** [comment]
>Where exactly is it?

I attached the patch to my e-mail answer, I forgot that GitHub drops attachments silently.
The patch can be created and applied with these commands:
```
git format-patch -1 27fbd3e3c99a7219d01b0b7cbac1a4d82428c0cd --stdout > target-fsharp4.patch
git apply -R target-fsharp4.patch
```
>Didn't know there was a way to use Mono with the VS solution. What do you mean exactly? (afaik xbuild is not really compatible with msbuild)

I meant using Mono's xbuild instead of msbuild; xbuild works fine for me with the VS solution on Mac OS X. Strangely enough, using F# 3.1.

>In any case, if we're globally switching to F# 4.0 fixing #308 becomes crucial. I currently cannot use F# 4.0 on Linux.

I agree #308 needs to be fixed, but switching to F# 4.0 for the VS solution doesn't seem to make things worse for Linux users.

**Pull request closed without merging**
