### PR TITLE
Remove ||: to stop hiding failure; don't assume Makefile has SHELL=bash set.

### PR DESCRIPTION
**Pull request by sishtiaq**

### CODE REVIEW

**Comment by s-zanella** [comment]
This breaks the `fstarlib.cma` and `fstarlib.cmxa` when either target wasn't built first.
I would rather write `install-byte` and `install` targets for either case, or just inline them in the respective targets.

**Comment by msprotz** [comment]
The right fix is to:
i) not use bash-only syntax in the Makefile, but instead
ii) make install depend on the cmxa then
iii) use `cp $^` in the production

**Comment by s-zanella** [comment]
If you go for this solution, you would also need to remove `make install` from the production of `fstarlib.cmxa` and `fstarlib.cma` and change the default target to depend on `install` instead of `fstarlib.cmxa`. This assuming no other file is referring directly to `fstarlib.cmxa` as a target.

**Comment by msprotz** [comment]
Ah ok, I hadn't seen the lines above, my bad. How about:

```
fstarlib.cmxa fstarlib.cma: fstarlib.mllib # not entirely correct
  $(OCAMLBUILD) $@
  cp $(addsuffix _build/fstarlib.cm,xa a) .

# ibid. fstarlib.cma

install: fstarlib.cmxa fstarlib.cma
  cp ...cmi...
```

we can't have two separate rules for ocamlbuild because they would get called concurrently for parallel builds and as far as I know this is not supported by ocamlbuild

**Comment by kyoDralliam** [comment]
AFAIK, we don't depend on the bytecode version. I just added that at some point for testing fstarlib in the ocaml toplevel. Let's drop it if it adding complexity and there is no user for fstarlib.cma.

**Pull request merged**
