### PR TITLE
Improve OCaml extraction of machine integer constants 

### LINKED ISSUE #2302: Improve OCaml extraction of machine integer constants
Machine integer constants, like `42l`, currently are extracted as:
```ocaml
FStar.Int32.int_to_t (Prims.of_int 42)
```
where `int_to_t` is defined as:
```ocaml
let int_to_t x = M.of_string (Z.to_string x)
```
This means that for every machine integer constant, the extracted OCaml code will: 
1. Convert it to a Zarith int
2. Convert that Zarith int into a string
3. Parse that string to get the desired Stdint int

Would it be possible to extract machine integer constants to this instead?
```ocaml
Stdint.Int32.of_int 42
```
This way we could avoid the overhead of going through Zarith and converting/parsing the string.

### PR DESCRIPTION
**Pull request by antoniolocascio**
This PR closes #2302.

## Description
As explained in Issue #2302, F\*'s machine integer constants, like `42l`, are currently extracted as:
```ocaml
FStar.Int32.int_to_t (Prims.of_int 42)
```
with `int_to_t` being:
```fsharp
let int_to_t x = M.of_string (Z.to_string x)
``` 
Because of this, for every machine integer constant present in a piece of F\* code, its OCaml extraction will have to:
1. Convert it to a Zarith int
2. Convert that Zarith int into a string
3. Parse that string to get the desired Stdint int 

Thus, using machine integer constants comes with significant computational overhead.

In this PR, we change the extraction of these constants, so that the example is simply extracted as:
```
Stdint.Int32.of_int (42)
```

## Solution
The solution we implemented, which is based on a suggestion made by @nikswamy on the Everest Slack, involves:
1. We extend `FStar.Syntax.Syntax.meta_source_info` with a constructor `Machine_integer of string * signedness * width`. The string field holds the Zarith string representation of the constant.
2. In `FStar.ToSyntax.ToSyntax.desugar_machine_integer`, we tag every machine integer constant with the new tag we defined, generating a `Tm_meta` node.
3. In `FStar.Extraction.ML.Term.term_as_mlexpr'`, we convert a term tagged with `Machine_integer` to the corresponding ML constant `Const_int`.
4. In `FStar_Extraction_ML_PrintML.build_constant`, we handle the new machine integer constant case by directly calling the corresponding Stdint conversions.

### Normalization
The main issue we ran into was that somewhere along the pipeline (between steps 2 and 3), the new tag was dropped. After digging around, I found that this was happening in the normalization of the term. The change in `FStar.TypeChecker.Normalize` solves the problem, but I'm not sure if this is the correct fix (or if it should be more general). I tried restoring every `Meta_desugared` label, but that seemed to break a lot of stuff.

### CODE REVIEW

**Comment by antoniolocascio** [comment]
I had to fix `FStar.Extraction.ML.Code.string_of_mlconstant`. However, I'm not entirely sure what this module is used for. I just wrote a simple fix, using the same technique that was used before this PR. Should I also provide a more specific extraction here?

**Comment by antoniolocascio** [comment]
🤦 I had forgotten that UInt8 is realized as the built-in int type in OCaml. I've added a special case for this type.

**Comment by nikswamy** [comment]
Thanks @antoniolocascio! This is really great work and it's really pushing this bit of meta data through the entire compiler pipeline. It looks pretty close to being done, but there are a couple of problems that I can help fix.

The main issue is that the reduction of machine integers in the normalizer gets blocked by these new metadata tags. I can fix that, but I have a question about the representation of this tag. You chose it to be

```
  | Machine_integer of string * signedness * width (* the string is its Zarith repr *)
```

i.e., it keeps the string representation of the underlying int. Is there a reason why you chose to do that rather than recomputing that string representation at extraction time?

The trouble is that if we keep that string, then every time the normalizer reduces, say, `1ul + 2ul` to `3ul`, it has to do both the computation of `1 + 2` in zarith (which is fine, that's what it does now), but, then it also has to turn the result into a string to store it in the Machine_integer tag. That string conversion in the middle of the normalizer is super inefficient ... consider if you have `1ul + 2ul + .... + 100ul`, we'd be computing strings for every intermediate term.

So, can we drop the string in the Machine_integer, please? If you can do that, then I can pick up from your state and fix the problem with the normalizer getting blocked. 

Thanks again ... your work is much appreciated!

**Comment by nikswamy** [comment]
FWIW, I have added a minimal test case for machine int normalization in branch _nik_2325, which is ahead of your PR branch and master. You can merge that branch into yours to get this test---it will result in your branch failing CI, but that's a good thing. After we resolve the Machine_integer representation issue, I can fix it so that this test passes.

**Comment by antoniolocascio** [comment]
Thanks for the review! I kept the string there to avoid recomputing it, but didn’t think about normalization. It should definitely be dropped. 
> ... recomputing that string representation at extraction time

I'm not sure how I should recompute it, though. I feel like I'm missing something trivial, but do we have any guarantees about the shape of `t` when extracting `Tm_meta(t, Meta_desugared (Machine_integer (s, w)))`? (is it always an application of `[u]int_to_t`?) If it isn’t, would it be reasonable to keep the zarith representation of the integer in the tag (instead of the string), or is this unnecessary?

**Comment by nikswamy** [comment]
We should maintain and rely on an invariant that the in a `Tm_meta(t, Meta_desugared(Machine_integer (s, w)))` that `t` is a `FStar.[U]Int[W].[u]int_to_t x` or a `FStar.[U]Int[W]__[u]int_to_t x`. where the `[U], [u], [W]` are determined by the signedness and width.

**Comment by antoniolocascio** [comment]
Ok, that makes sense. So do you think we should retrieve `x` from `t` on extraction rather than adding it to the `Machine_integer` tag? I thought that perhaps having it directly in the tag might have been cleaner, but I guess it doesn’t make that much of a difference. I kind of don’t see the point of having the tag if we're going to inspect `t` given that, as you pointed out, we could also retrieve `s` and `w` from there. Am I missing something?

**Comment by nikswamy** [comment]
You could indeed retrieve s and w from there. But, I think the point of having the tag is to make the extraction code easier. Otherwise, to extract this to stdint, you will have to pattern match on every application node, checking to see if the head symbol is a uint_to_t. I think this is clumsy and inefficient. Instead, if you have this Machine_integer metadata, you can match on that and handle it separately from general application nodes, while asserting that the underlying term is actually a [u]int_to_t application. From that perspective, I don't think it's necessary to even maintain s, w and in the metadata---just a tag will do. But, I don't see any harm in maintaining it either.

**Comment by antoniolocascio** [comment]
I've removed the string as you suggested. Thanks!

**Comment by antoniolocascio** [comment]
I had a go at fixing the normalization issue. The CI seems to be happy with it, but I really don’t know if it’s a good solution.

**Comment by nikswamy** [comment]
Perfect! I took a look and that is indeed the right solution. Nice work! 

I'll run an everest regression on it and report back on the results. Hopefully we can merge it soon

**Comment by nikswamy** [comment]
So, this breaks a regression test in HACL*/Vale. In particular, 

[STDERR]make[4]: *** [Makefile:10: aesgcm-c/out.krml] Error 255
[STDOUT]/home/everest/everest/kremlin/krml -verbose -verbose -I /home/everest/everest/hacl-star/code/old/lib/kremlin -I /home/everest/everest/kremlin/kremlib/compat -I /home/everest/everest/hacl-star/specs -I /home/everest/everest/hacl-star/specs/old -I . -fparentheses -fcurly-braces -fno-shadow -ccopt -march=native -verbose -ldopt -flto \
[STDERR]make[3]: *** [Makefile.old:9: experimental/aesgcm-c] Error 2
[STDOUT]  -tmpdir aesgcm-c \
[STDOUT]  Crypto.Symmetric.AES.fst Crypto.Symmetric.AES128.fst -skip-translation

... fails with ... 

[STDOUT]Unexpected error
[STDOUT](Failure "Argument in desugared machine int not a Const_int")
[STDOUT]Raised at Stdlib__string.index_rec in file "string.ml", line 115, characters 19-34
[STDOUT]Called from Sexplib0__Sexp.Printing.index_of_newline in file "src/sexp.ml", line 113, characters 13-47

I don't know of an easy way for you to reproduce this aside from getting a full everest development setup. 

One conjecture is that you're missing a compress before checking that `x` is an instance of Tm_constant.

I'll try to add more debugging probes and kick another build.

**Comment by antoniolocascio** [comment]
@nikswamy were you able to get any more information on why it failed? Is there any documentation on how to get a full everest development setup? Thanks!

**Comment by antoniolocascio** [comment]
I've fixed a couple of bugs that might have been the cause of that error. I also had to modify the Kremlin extraction of constants, as it assumed no MLC_Int machine integer constants would reach that point. Is that ok?

**Comment by nikswamy** [comment]
Thanks @antoniolocascio . I'll kick off another everest build now. Sorry for the delay: partly due to a CI infrastructure failure (due to extreme weather conditions taking down our machines) and partly due to the POPL deadline last night.

**Comment by nikswamy** [comment]
Good news! I got back a successful build from all the everest projects.

**Comment by nikswamy** [comment]
Before merging, I have one request:

Can we please have a test file for the extraction of machine integers to OCaml in tests/micro-benchmarks. It would be good to follow the style of Erasable.fst and Erasable.ml.expected and the build target Erasable.ml-cmp so that we can check that machine integers extract to stdint in the way we expect them to.

Thanks!

**Comment by antoniolocascio** [comment]
Great, I've added the test. Thanks!

**Comment by nikswamy** [comment]
Thank you!

**Pull request merged**
