### PR TITLE
Add baseline Dockerfile for interactive development.

### PR DESCRIPTION
**Pull request by DanielFabian**
This is the baseline build according to #584. As discussed, it is only for the current Ubuntu release and could potentially supersede the current 4.

Based on this, I now have an emacs and an emacs-nox build prepared.

### CODE REVIEW

**Comment by DanielFabian** [comment]
In case you want to play with the docker. The build is actually on docker hub as [danielfabian/fstar](https://hub.docker.com/r/danielfabian/fstar/builds/)

So you should be able just `docker run --rm -ti danielfabian/fstar`.

**Comment by beurdouche** [comment]
Building it right now ;) It looks very nice thanks. Here are a few thoughts:
- I think we can remove the `OTHERFLAGS=--lax` at the end of the formula so that it runs all the regression in verification mode instead of `lax`. This is heavy but at least the user has run it once at build time and knows that he is ready to proceed.
- Please be my guest in adding you as a maintainer too if you wish ;)
- I see no objections to remove all the current content of the .docker folder and put the formula there instead of having a `base` directory depending on what you prefer.

**Comment by DanielFabian** [comment]
I'm happy to remove `lax`, but yesterday it failed. I think `FStar.Array` or something was the one that exploded. I'll adjust the maintainer and remove the old dockers, but the `lax` thing is something, we probably need to fix upstream first, before we can enable it fully.

**Comment by beurdouche** [comment]
Ok. the build went through on my mac.
Regarding the regressions, they always should go through upstream so we should not have any trouble. I'll run them tomorrow and get back ;)

**Comment by beurdouche** [comment]
(Except that our containers may have some ressources limitations... I am not entirely sure about that.)

**Comment by DanielFabian** [comment]
The build takes about an hour as it is, but it didn't time out. Without `lax` it successfully failed at the verification step last time. So for now, I think it ought to work.

I'll also add my emacs builds. They work quite well already. Even managed an X11 session on Windows.

**Comment by DanielFabian** [comment]
https://github.com/docker/hub-feedback/issues/519

2 hours seems like a fairly generous time-out. If we don't fit into that, we should probably do a nightly build without lax and then add lax back to the docker.

**Comment by beurdouche** [comment]
Ok, I can reproduce the behaviour you describe:
```
/home/FStar/FStar/bin/fstar.exe  FStar.Array.fst
./FStar.Array.fst(180,70-184,3): Unknown assertion failed
Error: 1 errors were reported (see above)
```
We can probably keep the lax flag for now and investigate why this is failing. I suspect it might be that z3 is timing out because of a lack of ressources in our VMs.

**Comment by DanielFabian** [comment]
Those are the two emacs builds. emacs-nox is without the X11 dependency and emacs is the "usual" with fonts and all set up to work with prettify and X11.

**Comment by msprotz** [comment]
I haven't tried this out myself, but seems innocuous enough ;-).

Apologies about the delay, don't hesitate to ping me in the future!

**Comment by beurdouche** [comment]
Why this was closed, it hasn't been merged right ?

**Comment by beurdouche** [comment]
@DanielFabian, looks good to me, do you want to add a README in the `.docker` folder ?

**Comment by DanielFabian** [comment]
this seems to not have been merged in yet, indeed. No idea actually why it was closed. I thought, it had been merged, must have slipped me.

**Comment by msprotz** [comment]
I guess I just hit the wrong button. Apologies!

**Comment by beurdouche** [comment]
No worries ;)

**Pull request merged**
