### PR TITLE
Remove memoization of Tm_delayed nodes

### PR DESCRIPTION
**Pull request by mtzguido**
We've found that this does not increase performance, and it facts decreases it a bit. I'm leaving some benchmarks running overnight to post here.

### CODE REVIEW

**Comment by mtzguido** [comment]
I forgot that this was not just an optimization: it's a critical fix.

Currently `Tm_delayed` nodes are memoized in `compress_slow` with the result of `push_subst`. Now that can depend on the state of the unionfind graph, and if we are within a transaction which we then roll back, *the `Tm_delayed` node will still contain the old, invalid solution*.

This actually explains some of the errors in #1586.

**Comment by mtzguido** [comment]
OK, here's the actual numbers, obtained from the benchmarking script in #1971. I ran these overnight, killing pretty much every running process, on a single core and with nice `-20`, so I'm rather confident in the lack of excessive noise.

Summary: performance increases all around.

Before, with memoization:
```
G/micro-benchmarks
N_benches       total       user     system    mem(mb)
197            123.69    117.729    6.92127      26506
G/ocaml_extract
N_benches       total       user     system    mem(mb)
86            103.157    99.8564    3.37628      17824
G/ulib
N_benches       total       user     system    mem(mb)
249           2010.56    2000.56    10.8229      82894
```

After, no memo:
```
G/micro-benchmarks
N_benches       total       user     system    mem(mb)
197           109.311     104.14    6.07651      24974
G/ocaml_extract
N_benches       total       user     system    mem(mb)
86            101.145    97.8605    3.35992      17025
G/ulib
N_benches       total       user     system    mem(mb)
249           1934.31    1925.09    10.0471      73929
```

Not only that but it seems better per file too. Here's the 10 most time consuming files in each category before:
```
==> G/micro-benchmarks.summary <==
"Test.QuickCode.fst.checked"                23.8993    23.7896   0.113164     989864
"ChrisCheck.fst.checked"                     9.8785    9.74656   0.135965     607184
"FStar.Math.Lemmas.fst.checked"             4.79132    4.74142   0.053502     243292
"LowStar.Monotonic.Buffer.fsti.checked"     4.23452    4.17504   0.059913     386744
"FStar.Seq.Properties.fst.checked"          4.10851    4.07649   0.035961     216384
"FStar.UInt.fst.checked"                    4.04492    3.99592   0.053082     344724
"FStar.Tactics.Derived.fst.checked"         2.33962    2.27934    0.06398     346560
"FStar.List.Tot.Properties.fst.checked"     2.04781    2.02672   0.025028     180104
"FStar.ModifiesGen.fsti.checked"            1.97672    1.93888   0.042908     249328
"FStar.Printf.fst.checked"                  1.92826    1.87828    0.05427     340168

==> G/ocaml_extract.summary <==
"FStar_TypeChecker_Rel.ml"                  3.17142    3.13427   0.038127     263400
"FStar_SMTEncoding_Encode.ml"                3.1084    3.06367   0.045625     278896
"FStar_TypeChecker_TcTerm.ml"               3.02244    2.96436   0.059013     268512
"FStar_TypeChecker_Normalize.ml"            2.65623    2.60497   0.052021     254824
"FStar_TypeChecker_Util.ml"                 2.32417     2.2664   0.058793     246444
"FStar_ToSyntax_ToSyntax.ml"                2.29507    2.24529   0.051011     241256
"FStar_SMTEncoding_EncodeTerm.ml"           2.16026    2.11878   0.042189     259248
"FStar_Extraction_ML_Term.ml"               2.09123    2.05178   0.040347     258256
"FStar_Tactics_Basic.ml"                    2.08716    2.05393   0.034238     271192
"FStar_Interactive_Ide.ml"                  2.00015    1.95049   0.050592     303632

==> G/ulib.summary <==
"Steel.Channel.Simplex.fst"                 69.3567    69.1754   0.182966    1822596
"Steel.Semantics.Hoare.MST.fst"             47.5548    47.3944   0.162542    1626232
"FStar.Math.Fermat.fst"                     35.4014    35.0339   0.368036    2355292
"Steel.HigherReference.fst"                 29.6476    29.5665   0.084384     934312
"Steel.Effect.Atomic.fst"                   26.6938    26.6095   0.085332     901004
"Steel.Actions.fst"                         24.6498    24.5878    0.06244     638556
"Steel.Effect.fst"                          22.7204    22.6249    0.09769     704472
"Steel.Reference.fst"                       22.1268    22.0574   0.067985     704740
"Steel.SpinLock.fst"                        21.3332    21.2433    0.09068     770224
"Steel.Memory.Tactics.fst"                  21.2717    21.2203   0.052879     704704
```

and after
```
==> G/micro-benchmarks.summary <==
"Test.QuickCode.fst.checked"                19.0359    18.9722   0.069258     500388
"ChrisCheck.fst.checked"                    9.83604    9.70653   0.132907     672600
"FStar.Math.Lemmas.fst.checked"             4.08399    4.06351   0.025454     210600
"LowStar.Monotonic.Buffer.fsti.checked"     3.93058     3.8539   0.081024     332116
"FStar.UInt.fst.checked"                    3.82226     3.7528   0.074706     344372
"FStar.Seq.Properties.fst.checked"          3.41874    3.38191   0.040996     215156
"FStar.List.Tot.Properties.fst.checked"     2.01076    1.98081   0.035764     179272
"FStar.Tactics.Derived.fst.checked"         1.96412    1.88403    0.08367     312636
"FStar.ModifiesGen.fsti.checked"            1.95134    1.92112   0.033536     229016
"FStar.Integers.fst.checked"                1.60123    1.54753   0.059545     253412

==> G/ocaml_extract.summary <==
"FStar_TypeChecker_Rel.ml"                  3.14602    3.11448    0.03247     254304
"FStar_SMTEncoding_Encode.ml"               3.00494    2.93987   0.066067     272096
"FStar_TypeChecker_TcTerm.ml"               2.87748    2.84356   0.034665     252676
"FStar_TypeChecker_Normalize.ml"            2.55064    2.49264   0.058928     239740
"FStar_TypeChecker_Util.ml"                 2.34595    2.28668   0.059973     230696
"FStar_ToSyntax_ToSyntax.ml"                2.22757    2.18807   0.040393     231048
"FStar_SMTEncoding_EncodeTerm.ml"           2.13298    2.09909   0.034654     235644
"FStar_Tactics_Basic.ml"                    2.04309    1.99788   0.046098     246344
"FStar_Extraction_ML_Term.ml"               2.03732    1.99945   0.038804     254452
"FStar_Interactive_Ide.ml"                  1.96098    1.90844   0.053661     274124

==> G/ulib.summary <==
"Steel.Channel.Simplex.fst"                 63.4378    63.2552   0.179978    1298072
"Steel.Semantics.Hoare.MST.fst"             42.3968    42.3061   0.092905     869376
"FStar.Math.Fermat.fst"                     32.7056    32.5609   0.145977    1692064
"Steel.HigherReference.fst"                 26.9995    26.9288   0.074578     665260
"Steel.Effect.Atomic.fst"                   24.9549    24.8528   0.099831     704176
"Steel.Actions.fst"                         24.1252    24.0697   0.056908     605696
"Steel.Effect.fst"                          20.7921    20.7495   0.046876     574312
"Steel.SpinLock.fst"                        20.7165    20.6544   0.060432     574032
"Steel.Reference.fst"                       20.6873    20.6158   0.073189     574184
"Steel.Primitive.ForkJoin.fst"              20.0918    20.0068   0.087567     536356
```

Most of them decrease in time. Some considerably. The ones that do increase in time do so only slightly.

Now sorted by memory usage, everything decreases and come pretty considerably too (~50 for Test.QuickCode). Before:
```
==> G/micro-benchmarks.summary <==
"Test.QuickCode.fst.checked"                23.8993    23.7896   0.113164     989864
"ChrisCheck.fst.checked"                     9.8785    9.74656   0.135965     607184
"LowStar.Monotonic.Buffer.fsti.checked"     4.23452    4.17504   0.059913     386744
"Pruning.fst.checked"                       1.04724   0.997943   0.055125     352400
"FStar.Tactics.Derived.fst.checked"         2.33962    2.27934    0.06398     346560
"FStar.UInt.fst.checked"                    4.04492    3.99592   0.053082     344724
"FStar.Printf.fst.checked"                  1.92826    1.87828    0.05427     340168
"LowStar.BufferView.fsti.checked"           1.36145    1.31287   0.053443     284420
"FStar.Integers.fst.checked"                1.65175    1.58722   0.068951     282276
"FStar.Bytes.fsti.checked"                  1.14018    1.09433    0.04917     254516

==> G/ocaml_extract.summary <==
"FStar_Tests_Unif.ml"                       1.61538     1.5541   0.062204     341116
"FStar_Tests_Test.ml"                       1.53891    1.45892   0.081068     337036
"FStar_Tests_Norm.ml"                       1.86441    1.79126   0.073606     332424
"FStar_Tests_Pars.ml"                       1.51189    1.47525   0.037581     319788
"FStar_Main.ml"                              1.5667    1.52955   0.038069     315656
"FStar_Interactive_Ide.ml"                  2.00015    1.95049   0.050592     303632
"FStar_Interactive_Lsp.ml"                  1.45564    1.40573   0.050848     287868
"FStar_Interactive_PushHelper.ml"           1.52054    1.48026   0.041174     284928
"FStar_SMTEncoding_Encode.ml"                3.1084    3.06367   0.045625     278896
"FStar_Interactive_Legacy.ml"                1.6225    1.58649   0.037086     277088

==> G/ulib.summary <==
"FStar.Math.Fermat.fst"                     35.4014    35.0339   0.368036    2355292
"Steel.Channel.Simplex.fst"                 69.3567    69.1754   0.182966    1822596
"Steel.Semantics.Hoare.MST.fst"             47.5548    47.3944   0.162542    1626232
"FStar.Tactics.PatternMatching.fst"         17.6216    17.5111   0.110626    1297236
"Steel.HigherReference.fst"                 29.6476    29.5665   0.084384     934312
"Steel.Effect.Atomic.fst"                   26.6938    26.6095   0.085332     901004
"Steel.SteelAtomic.Basics.fst"              20.7871    20.6994   0.084909     770260
"Steel.SpinLock.fst"                        21.3332    21.2433    0.09068     770224
"Steel.Semantics.Instantiate.fst"           19.8457    19.7445   0.105141     770180
"Steel.SteelT.Basics.fsti"                   20.389    20.3396   0.052606     769816
```

After:
```
==> G/micro-benchmarks.summary <==
"ChrisCheck.fst.checked"                    9.83604    9.70653   0.132907     672600
"Test.QuickCode.fst.checked"                19.0359    18.9722   0.069258     500388
"FStar.UInt.fst.checked"                    3.82226     3.7528   0.074706     344372
"LowStar.Monotonic.Buffer.fsti.checked"     3.93058     3.8539   0.081024     332116
"Pruning.fst.checked"                       0.83107   0.772338   0.063651     330940
"FStar.Tactics.Derived.fst.checked"         1.96412    1.88403    0.08367     312636
"FStar.Printf.fst.checked"                   1.5345    1.48543   0.052302     296368
"FStar.Integers.fst.checked"                1.60123    1.54753   0.059545     253412
"LowStar.BufferView.fsti.checked"           1.21609    1.18554   0.034016     251796
"StrictUnfolding.fst.checked"              0.584647    0.56262   0.026968     240436

==> G/ocaml_extract.summary <==
"FStar_Tests_Test.ml"                       1.50702    1.43991   0.067996     333868
"FStar_Tests_Norm.ml"                        1.8495    1.80685   0.043753     330544
"FStar_Tests_Unif.ml"                       1.52481    1.44214    0.08381     324016
"FStar_Main.ml"                             1.58018    1.52126   0.059802     313368
"FStar_Tests_Pars.ml"                       1.49845    1.44596    0.05353     307020
"FStar_Interactive_Lsp.ml"                  1.42599    1.37091    0.05612     283360
"FStar_Interactive_PushHelper.ml"           1.43494    1.38757   0.048363     282544
"FStar_Interactive_Legacy.ml"               1.54157     1.4797   0.062814     274680
"FStar_Interactive_Ide.ml"                  1.96098    1.90844   0.053661     274124
"FStar_SMTEncoding_Encode.ml"               3.00494    2.93987   0.066067     272096

==> G/ulib.summary <==
"FStar.Math.Fermat.fst"                     32.7056    32.5609   0.145977    1692064
"Steel.Channel.Simplex.fst"                 63.4378    63.2552   0.179978    1298072
"Steel.Semantics.Hoare.MST.fst"             42.3968    42.3061   0.092905     869376
"FStar.Tactics.PatternMatching.fst"         13.8448    13.7591   0.089399     710512
"Steel.Effect.Atomic.fst"                   24.9549    24.8528   0.099831     704176
"Steel.HigherReference.fst"                 26.9995    26.9288   0.074578     665260
"FStar.Tactics.CanonCommSemiring.fst"       18.2925    18.1977   0.098683     638964
"Steel.Channel.Simplex.fsti"                 19.793    19.7061   0.090448     606016
"Steel.HigherReference.fsti"                19.2253    19.1725   0.052361     605980
"Steel.Actions.fst"                         24.1252    24.0697   0.056908     605696
```

**Comment by mtzguido** [comment]
@nikswamy just a heads up: you mentioned you had a situation where enabling printing was changing the behaviour of a program, and that could have been very well caused by bad memoizations. It happened to me yesterday while debugging too, and does not happen with this patch.

**Comment by nikswamy** [comment]
This is awesome work! Thanks @mtzguido

**Comment by nikswamy** [comment]
This is also a really clean diff. Removing memoization makes the code simpler and easier to understand.

Thanks for the thorough performance evaluation too. 

Overall, once we have a green on Everest-CI, let's merge this ASAP.

**Comment by mtzguido** [comment]
We did some forensics with @nikswamy to find how this bug came to be, the status has flip-flopped a bit, but here's the recent story:

`compress` used to look like this:
```fstar
 let rec compress (t:term) = 
     let t = force_uvar t in 
     match t.n with
         | Tm_delayed(Inl(t, s), memo) -> 
           let t' = compress (push_subst s t) in
           Unionfind.update_in_tx memo (Some t');^M
 //          memo := Some t';^M
           t'
         | _ -> t
```
Where `update_in_tx` would make sure to undo the setting of the reference if the Unionfind transaction was aborted. [This commit](3ced122bb5546b284047e73da94e969a7e99bb2b) would then make the change to memoize only the solution of the delayed substitution, but not that of the uvar. This meant that the cached result was not affected by the unionfind, and hence needed no rollback.

```fstar
(* compress:
      This is used pervasively, throughout the codebase

      The recommended use for inspecting a term
      is to first call compress on it, which should
         1. push delayed substitutions down one level

         2. eliminate any top-level (Tm_uvar uv) node,
            when uv has been assigned a solution already

      Internally, compress should memoize the result of any
      delayed substitution (i.e., step 1 above), but not
      memoize the result of uvar solutions (since those
      could be reverted).
*)
 let rec compress (t:term) =
     let t = try_read_memo t in
     match t.n with
     | Tm_delayed((t', s), memo) ->
         memo := Some (push_subst s t');
         compress t
     | _ ->
         let t', forced = force_uvar t in
         match t'.n with
         | Tm_delayed _ -> compress t'
         | _ -> t'
```
I'ts important to note that **as of this commit**, `push_subst` did not descend into uvar solutions (it does now). [Later](d4a4eb3e686f50999827bf3749253941bbb3e546) the code got changed to call `force_uvar` unconditionally, hence memoizing the `Tm_delayed` with UF-dependent data
```diff
 let rec compress (t:term) =
     let t = try_read_memo t in
+    let t, _ = force_uvar t in
     match t.n with
     | Tm_delayed((t', s), memo) ->
         memo := Some (push_subst s t');
         compress t
     | _ ->
-        let t', forced = force_uvar t in
-        match t'.n with
-        | Tm_delayed _ -> compress t'
-        | _ -> t'
-
+        t
```
Also in that commit `push_subst` would explode on finding a uvar node which was meant to be resolved
```diff
     | Tm_constant _
     | Tm_fvar _
-    | Tm_uvar _
-    | Tm_unknown -> tag_with_range t s
+    | Tm_unknown -> tag_with_range t s //these are always closed
+
+    | Tm_uvar (uv, _) ->
+      begin
+      match (Unionfind.find uv) with
+      | None -> tag_with_range t s
+      | Some _ -> failwith "Should have been forced already; see compress below"
+      end
```
but two commits ahead of that, made to descend into them:
```diff
       begin
       match (Unionfind.find uv) with
       | None -> tag_with_range t s
-      | Some _ -> failwith "Should have been forced already; see compress below"
+      | Some t -> push_subst s t
       end
```

Which is pretty much the status before this PR. This could of course be fixed, but the benchmarks show that it's likely not worth, and it's tricky as hell, so we're removing the memoizations.

[Some commit messages](d4a4eb3e686f50999827bf3749253941bbb3e546) suggest that `Tm_delayed` nodes (which were "off" before this commit) were indeed a big performance gain. My theory is that that's due more to the "by need" aspect than to the memoization, and that since we now compress top-levels there's fewer delayed nodes hanging around in the environment.

**Pull request merged**
