### PR TITLE
Support SMTLIB solvers

### PR DESCRIPTION
**Pull request by nbraud**
This branch tries to solve #1086, but isn't complete yet.

- [x] Remove solver-specific options from SMT files (instead passed as CLI options)
- [x] Use valid SMTLIB syntax in the prelude.
- [x] Add CLI options for switching the SMT solver.
- [x] Use SMTLIB operators `=>` and `=` instead of `implies` and `iff`.
- [x] Use `get-values` instead of `eval`.
- [x] Use SMTLIB-compliant names.
- [x] Figure out how to deal with annotations like `:qid`.

### CODE REVIEW

**Comment by nbraud** [comment]
@cpitclaudel Almost there!  🎉

**Comment by nbraud** [comment]
PS: I requested the review even though the last part (fixing the naming convention) isn't in yet, but I ought to have something ready before the implementor's breakfast tomorrow.

**Comment by nbraud** [comment]
For info, here is what it currently looks like:
```
  export OTHERFLAGS="--smt_solver cvc4"
  make -C src uregressions
make: Entering directory '/mnt/c/everest/everest/FStar/src'
make -C ../examples/hello ocaml
make[1]: Entering directory '/mnt/c/everest/everest/FStar/examples/hello'
[...]
/mnt/c/everest/everest/FStar/bin/fstar.exe --smt_solver cvc4 --hint_info --use_hints --no_extract FStar.All --no_extract FStar.BaseTypes --no_extract FStar.Buffer --no_extract FStar.Char --no_extract FStar.CommonST --no_extract FStar.Constructive --no_extract FStar.Float --no_extract FStar.Ghost --no_extract FStar.Heap --no_extract FStar.HyperStack.All --no_extract FStar.HyperStack.ST --no_extract FStar.Int16 --no_extract FStar.Int32 --no_extract FStar.Int63 --no_extract FStar.Int64 --no_extract FStar.Int8 --no_extract FStar.Int_Cast --no_extract FStar.IO --no_extract FStar.List --no_extract FStar.List.Tot.Base --no_extract FStar.Mul --no_extract FStar.Option --no_extract FStar.Pervasives.Native --no_extract FStar.Set --no_extract FStar.ST --no_extract FStar.String --no_extract FStar.UInt16 --no_extract FStar.UInt32 --no_extract FStar.UInt63 --no_extract FStar.UInt64 --no_extract FStar.UInt8 --no_extract FStar.Pointer --no_extract FStar.BufferNG --no_extract prims --odir out --codegen OCaml hello.fst
(/mnt/c/everest/everest/FStar/examples/hello/hello.fst) digest is valid; using hints.
./hello.fst(5,0-5,37): (Warning) Top-level let-bindings must be total; this term may have effects
<stdin>:70.39: warning: Attribute ':qid' not supported (ignoring this and all following uses)
Makefile:12: recipe for target 'ocaml' failed
[...]
```

This is actually pretty encouraging, since it means the entire prelude goes through.

**Comment by nbraud** [comment]
@cpitclaudel Pattern matching the name of the SMT solver's binary gets quite ugly quite fast.
For instance, the current binary for CVC4's binary distribution is called `cvc4-2017-07-02-x86_64-linux-opt`.

**Comment by cpitclaudel** [comment]
Makes sense. I'll ping the CVC4 people again about the one change that required their help (making sure that CVC4 doesn't exit after a failed get-model). Or maybe there's a way around this on our side?

**Comment by nbraud** [comment]
@cpitclaudel As far as I can tell, we do not call `get-model` (at least, this doesn't appear in the code).
We did use `eval`, but I replaced that with `get-value` (which you said ought to make CVC4 happier)

**Comment by cpitclaudel** [comment]
Sorry, indeed, get-value (not get-model). The issue remains though (CVC4 exits after the first get-value following an unsat query).

**Comment by nbraud** [comment]
Ah, I see.

**Comment by cpitclaudel** [comment]
The CVC4 bug for `get-value` to error and continue is at http://cvc4.cs.stanford.edu/bugzilla3/show_bug.cgi?id=831

**Comment by nbraud** [comment]
@cpitclaudel @wintersteiger This should be OK now, modulo that I'm not done reproving `FStar.Math.Lemmas` (it is currently running, so we should have that tomorrow)

Sorry for the time that took, I was blocked for quite some time (and working on other things due to how frustrating it was...) before noticing that 20bdf44 needed to modify `src/basic/ml/` too, and by the time I found the issue, Nikhil rewrote entirely the SMT replies parser, so the rebase was pretty unpleasant.

**Comment by nbraud** [comment]
OK, `Math.Lemmas` fails to prove with `z3rlimit_factor 10`...  :(

**Comment by nikswamy** [comment]
Does Math.Lemmas fail with Z3 or with CVC4?

**Comment by nikswamy** [comment]
ping; definitely worth trying to revive and merge this. any takers?

**Comment by wintersteiger** [comment]
Thanks for the ping - I had assumed this was merged long ago. 

@nbraud: was the only remaining issue that CVC4 could not prove some things that Z3 could prove? I think we can ignore that, especially if that's in Math.Lemmas.

**Comment by aseemr** [comment]
Ping @wintersteiger, @nbraud, @nikswamy. This is s useful feature, but would require some work to make sure that the changes work with the existing code that uses Z3. Would someone like to volunteer to revive it?

**Comment by nikswamy** [comment]
I'm closing this PR. It would be great to support non-Z3 solvers. So, if someone wants to revive it, that would be great.

**Pull request closed without merging**
