### PR TITLE
Replace Vale fstar_ci branch with --MIN-TEST in HACL* fstar-master

### PR DESCRIPTION
**Pull request by Chris-Hawblitzel**
It would be good to move away from the Vale repository's old fstar_ci branch, which isn't maintained.  This pull request uses --MIN-TEST from the HACL* repository's fstar-master branch rather than --MIN-TEST from the Vale repository's fstar_ci branch.  It also switches to the binary release of Vale, rather than rebuilding Vale from source.

There is a related pull request to reduce the size of --MIN-TEST in the HACL* repository: https://github.com/project-everest/hacl-star/pull/143

### CODE REVIEW

**Comment by Chris-Hawblitzel** [comment]
The new version of build.sh uses `hacl-star/vale/Makefile`, which runs scons with --FSTAR-MY-VERSION

**Comment by parno** [comment]
Ah, okay, glad to know the right thing is happening

**Comment by msprotz** [comment]
Thanks Chris.
- Can you remind me why fetch_vale depends on fetch_hacl? Because of the version? (Maybe worth adding a comment)
- You removed a bunch of logic for the error codes. Is this because things are now working, or because we expect to solve them soon on the HACL* repository?

Cheers,

Jonathan

**Comment by Chris-Hawblitzel** [comment]
The error code logic relied on extensions to the run_scons.sh script that only existed in the fstar_ci branch of the Vale repository, and do not exist in the run_scons.sh script in the hacl-star repository.  (Moreover, given our recent discussions about these error codes, I don't think the Vale fstar_ci version was actually capturing the errors from python/scons anyway -- the underlying problem with the error codes is in a different place.)

**Comment by nikswamy** [comment]
Would be great to leave behind the min-test in the old Vale repo.

Please merge if you have an Everest green.

**Pull request merged**
