### PR TITLE
Layered effects

### PR DESCRIPTION
**Pull request by aseemr**
Layered effects implementation.

The branch is not yet ready to be merged into master. In the next couple of days, I plan to:

- Fix Everest regressions
- Write a wiki page describing how to define a new layered effect and use it
- Do some more code documentation wherever I find it lacking

Making a PR now because it's a big change so just to start the process.

Please see `examples/layered_effects` for some test cases.

### CODE REVIEW

**Comment by nikswamy** [comment]
Recording the design document here, for future reference:
https://github.com/FStarLang/FStar/wiki/Proposal:-Effect-Layering

**Comment by nikswamy** [comment]
(I'll keep updating this comment with my remarks as I read more)

FIrst off: Congrats, Aseem! This is an impressive piece of work.

Here is the list of files that I'm focusing on for the review, at least at first.

(from `git diff origin/master --name-only *fs *fsi`)

### Extraction:

```
src/extraction/FStar.Extraction.ML.Term.fs
``` 
Change looks fine; just adding inlinig steps to reify_body. 

### Parser:
```
src/parser/FStar.Parser.AST.fs
src/parser/FStar.Parser.Const.fs
src/parser/FStar.Parser.Dep.fs
src/parser/FStar.Parser.Lexhelp.fs
src/parser/parse.fsi
```

Seems to be a small change, just the addition of the `layered_effect` keyword.

However, a change in a comment suggests that the number of shift-reduce conflicts has increased from 5 to 6. But menhir still reports only 
```
Warning: 5 states have shift/reduce conflicts.
Warning: 6 shift/reduce conflicts were arbitrarily resolved.
```
Any reason for this change?



### SMTEncoding:
```
src/smtencoding/FStar.SMTEncoding.Encode.fs
src/smtencoding/FStar.SMTEncoding.EncodeTerm.fs
src/smtencoding/FStar.SMTEncoding.Util.fs
```
Looks like the main change is to restrict the SMT encoding only to reify non-layered effects, using the is_smt_reifiable guard. This sounds reasonable. However, did you consider encoding reified layered effects in case the underlying representation effect is Pure or Ghost? That would cover DM4F cases, but it would also cover any new instance where people want to layer a new effect on top of Pure/Ghost. Curious to hear your thoughts on this.
### Syntax:

```
src/syntax/FStar.Syntax.Print.fs
src/syntax/FStar.Syntax.Print.fsi
src/syntax/FStar.Syntax.Resugar.fs
src/syntax/FStar.Syntax.Syntax.fs
src/syntax/FStar.Syntax.Syntax.fsi
src/syntax/FStar.Syntax.Util.fs
```

### Tactics:

```
src/tactics/FStar.Tactics.Basic.fs
src/tactics/boot/FStar.Tactics.Interpreter.fs
```

### Desugaring:
```
src/tosyntax/FStar.ToSyntax.ToSyntax.fs
```

### Typechecker:

```
src/typechecker/FStar.TypeChecker.Common.fs
src/typechecker/FStar.TypeChecker.Common.fsi
src/typechecker/FStar.TypeChecker.DMFF.fs
src/typechecker/FStar.TypeChecker.DMFF.fsi
src/typechecker/FStar.TypeChecker.Env.fs
src/typechecker/FStar.TypeChecker.Env.fsi
src/typechecker/FStar.TypeChecker.NBE.fs
src/typechecker/FStar.TypeChecker.Normalize.fs
src/typechecker/FStar.TypeChecker.Normalize.fsi
src/typechecker/FStar.TypeChecker.Rel.fs
src/typechecker/FStar.TypeChecker.Tc.fs
src/typechecker/FStar.TypeChecker.TcEffect.fs
src/typechecker/FStar.TypeChecker.TcEffect.fsi
src/typechecker/FStar.TypeChecker.TcInductive.fs
src/typechecker/FStar.TypeChecker.TcTerm.fs
src/typechecker/FStar.TypeChecker.TcTerm.fsi
src/typechecker/FStar.TypeChecker.Util.fs
src/typechecker/FStar.TypeChecker.Util.fsi
```

**Comment by aseemr** [comment]
Hi @nikswamy, re. your comment on the parser, this is what I see (and hence the comment update):

```
ocamlyacc parse.mly 2> yac-log
cat yac-log
6 shift/reduce conflicts.
```

This is both in master as well as my branch. Am I looking at the wrong count?

**Comment by aseemr** [comment]
@nikswamy, re. the comment on the smtencoding, I think it's implicit but just to make sure that we are on the same page :), this change to smtencoding still allows reasoning about layered effects over `PURE` using their types, what this doesn't allow is to reason about them using the definitions of their reification.

It's possible (encoding reification of layered effects over `PURE` to smt) and I considered it , as the comment there says "Could revisit" but I did not see an immediate need for it. So, left it as future work. This way we would also know what's the use case rather than someone using this unknowingly.

Please let me know if you prefer to do it now, should be easy to implement.

**Comment by nikswamy** [comment]
### Syntax:

```
src/syntax/FStar.Syntax.Print.fs
src/syntax/FStar.Syntax.Print.fsi
src/syntax/FStar.Syntax.Resugar.fs
src/syntax/FStar.Syntax.Syntax.fs
src/syntax/FStar.Syntax.Syntax.fsi
src/syntax/FStar.Syntax.Util.fs
```

I see two main changes in syntax.

1. The `lcomp` type (for lazy computation type thunks) has been moved to FStar.TypeChecker.Common. The reason is that the `lcomp` type, when forced, produced both a computation type and a typechecking guard for it (a `guard_t`), which is defined only in the typechecker, not at the level of the syntax. The guard is important since it contains, e.g., unification problems that are still to be solved. With layered effects, these unification problems are an essential part of building the VC and have to be carried along. 

2. The other main change is, as expected, to support the representation of layered effect declarations. I recall two main changes here. @aseemr, it would be great if you could confirm and elaborate on this.
  - The representation of the universe binders in an effect declaration changed. 
  - Some fields of the effect declaration are optional, only present for primitive effects or layered effects etc. 
E.g, adding those descriptions as a code comment on the type of eff_decl would be great.

**Comment by aseemr** [comment]
Hi Nik, re. `syntax` changes, for the comment, I already have some: https://github.com/FStarLang/FStar/blob/_aseem_layered_effects_only/src/syntax/FStar.Syntax.Syntax.fsi#L355.

For the universe changes in there, you are right. Fields like `repr`, `signature` are `tscheme` now (as opposed to terms earlier), their universes are captured in this `tscheme` rather than in `univs`.

**Comment by nikswamy** [comment]
Comments about typechecker changes reviewed so far (my working notes )

FStar.TypeChecker.Common:

- Definitions and basic utilites on guard_t and implicits moved
  to Common from FStar.TypeChecker.Env

- lcomp moved here from Syntax

FStar.TypeChecker.DMFF

- the main `cps_and_elaborate` functions is moved to this file
  from Tc.fs. Sounds like the right home for it ... wonder why it
  got left behind in Tc in the first place. Thanks for cleaning
  this up.

FStar.TypeChecker.Env

The type of lifts changed. They used to be specific towards
effects with WPs, but they have been generalized.

I have added some comments to the code, reproduced below.

A nit: should the field `mlift_wp` be renamed, since it is no
longer wp-specific?


```
// Lifts a computation type `M a is` to `N a js`
// producing additional unification problems
// recorded in guard_t
type lift_comp_t = env -> comp -> comp * guard_t


// mlift_term is optionally present when the target effect
// is reifiable. Given `e : M<u> a _ `, `mlift_term u a e` 
// computes the corresponding term representation of the 
// lifted computation in the target effect
// Note, its arguments are only the universe `u`, the result type `a`
// and the source term
and mlift = {
  mlift_wp:lift_comp_t;
  mlift_term:option<(universe -> typ -> term -> term)>
}
```

FStar.TypeChecker.Rel.fs:

The main change is in sub-effecting for layered effects

Sub-effecting for layered effects `M a is <: N b js` is supported
when `N` is a layered effect and, either
-- M = N  (in which case this amounts to subsumption of the indices)
-- M is not itself a layered effect

Otherwise, to coerce from one layered effect `M a is` to another
`N b js`, the recommended method is to use an explicit coercion
using `N.reflect`

**Comment by nikswamy** [comment]
Playing with this on a small example:

Some points to note:

-- Indexes on the effect need to be in a fixed universe. We do not yet support universe polymorphic indexed.

-- All the arguments to the combinators (return, bind, etc.) need to be explicit; we don't allow implicit arguments there

-- The `if_then_else` combinator does not appear to be checked for soundness, so far. We had discussed requiring the user to provide a proof terms for this, e.g., 

```
let if_then_else_true 
     (a:Type) (s:Type)
     (f:repr a s)
     (g:repr a s)
     (p:Type0 { p })
  : if_then_else a s f g p
  = subcomp a s f

let if_then_else_false
     (a:Type) (s:Type)
     (f:repr a s)
     (g:repr a s)
     (p:Type0 { ~p })
  : if_then_else a s f g p
  = subcomp a s g
```
Is it possible to add that check?


Here's my example, fwiw.

```
module FreeSTMonad

noeq
type m (s:Type0) (a:Type) = //The index `s` needs to be in Type0
  | Ret : a -> m s a
  | Get : (s -> m s a) -> m s a
  | Put : x:s -> m s a -> m s a
module W = FStar.WellFounded

let rec bind_m #s #a #b (x:m s a) (y: (a -> m s b)) : m s b =
  match x with
  | Ret x -> y x
  | Get k -> Get (fun s -> W.axiom1 k s; bind_m (k s) y)
  | Put s k -> Put s (bind_m k y)


(* Just a simply typed variant *)
let repr a s =
  unit -> m s a

let return (a:Type) (s:Type) (x:a)
  : repr a s
  = fun () -> Ret x

let rec bind a b s (f:repr a s) (g : (a -> repr b s))
  : repr b s
  = let m_f = f () in
    let m_g = fun x -> g x () in
    fun () -> bind_m #s #a #b m_f m_g

//no subsumption rule
let subcomp (a:Type) (s:Type) (f:repr a s)
  : Tot (repr a s)
  = f

let if_then_else (a:Type) (s:Type)
                 (f:repr a s)
                 (g:repr a s)
                 (p:Type0)
  : Type
  = repr a s

let get s : repr s s =
    fun () -> Get Ret

let put s (x:s) : repr unit s =
    fun () -> Put x (Ret ())

reifiable reflectable
layered_effect {
  FST : a:Type -> s:Type0 -> Effect
  with repr         = repr;
       return       = return;
       bind         = bind;
       subcomp      = subcomp;
       if_then_else = if_then_else;

       get = get;
       put = put
}

let lift_pure_fst
    (a:Type)
    (s:Type)
    (wp:pure_wp a)
    (f:unit -> PURE a wp)
  : repr a s
  = assume(wp (fun x -> True)); //to suppress the WP
    return a s (f())

sub_effect PURE ~> FST = lift_pure_fst

let incr () : FST unit int =
  let x = FST?.get int in
  let y = x + 1 in
  FST?.put int y
```

**Comment by aseemr** [comment]
Thanks for the comments @nikswamy.

- I added soundness checks for the `if_then_else` combinators. It was on the TODO list (#1875) but I also thought it's better to do it before merging. The relevant commit is this and there is a comment on how it is currently implemented: https://github.com/FStarLang/FStar/commit/8dd449469a24e5259a95d1e8b2c461808545c478.

- I also moved the `tc_check_trivial_guard` to `TcTerm` and remove its inlining from `Tc.tc_type_common`. Thanks for catching this, it seems like it was a remnant of some intermediate state.

- The universes of the indices are fixed, this comes from an already existing restriction of the effect signature being polymorphic in a single universe, and similar restrictions on the effect combinators (e.g. 2 for `bind`).

- The arguments to effect combinators are explicit, I didn't think there was a need to support implicits there since the programmer does not call these combinators explicitly. But it should be easy to implement implicits there, please let me know if you have a preference for that.

- I also added your free monad example to the `examples/layered_effects` directory.

- Regarding switching steps (5) and (6) in the typechecking of branches: let's say we are working on a branch:

```
match x with
 | P y -> e
```

From steps 1-4, we have (among other things) `..., x, y |- e : M t is`, where `is` are the effect indices (wp for standard effects).

Previously, step (5) would weaken `M t is` with `x == P y` and close over `y`.
And step (6) would compute a guard for the branch that is well-typed in the caller, in this case `P? x`.

With layered effects, I am doing step (6) first, so that then I can use the branch guard to do the weakening in the step (5). So now:

Step (5) computes the branch guard (previously step (5))
Step (6): Non-layered effects, same as previous step (5), layered effects: weaken `M t is` with the branch guard computed from step (5) and close over `y` substituting it with `P? x`.

I could have kept (5) as is, weaken with `x == P y` and then substitute `y` with `P? x`, that would have made the weakening as `x == P (P? x)` ... which is somewhat convoluted, so I thought swapping (5)  and (6) and using branch guard is cleaner.

This doesn't change anything for non-layered effects.

**Comment by nikswamy** [comment]
Regarding TcUtil:

There's this bit in `bind`:

```
                (*
                  * Helper routine to close the compuation c with c1's return type
                  * When c1's return type is of the form _:t{phi}, is is useful to know
                  *   that t{phi} is inhabited, even if c1 is inlined etc.
                  *)
                 let close (x:bv) (reason:string) (c:comp) =
                   if c |> U.comp_effect_name |> Env.norm_eff_name env |> Env.is_layered_effect env
                   then Inl (c, reason)
                   else
                     let x = { x with sort = U.comp_result c1 } in
                     Inl (close_wp_comp_if_refinement_t env x.sort x c, reason) in
```

Seems like for layered effects we don't get this closing behavior with the type information of c1?
It's understandable, since this close_wp thing doesn't exist for layered effects. but it would be good to identify flavors of examples that would have worked with standard effects but would not verify with layered effects because of this limitation

There are these kinds of localized changes to environments. For example, here:
```
                      let c2, g_w = weaken_comp (Env.push_binders env [S.mk_binder x]) c2 x_eq_e in
```
where previously `x` was not in the environment. The change looks reasonable, but I wonder what prompted the change. Was there a variable escaping its scope previously that this is fixing?

**Pull request merged**
