### PR TITLE
FStar.BV: expose bvshl, bvshr and bvmod with bit vector rhs

### PR DESCRIPTION
**Pull request by amosr**
The bit-shifting and modulus operations in FStar.BV currently take natural numbers in the right-hand side. This incurs some conversion overhead, as the SMT-LIB primitives take bit vectors. This commit implements bit vector native versions called `bvshl'`, `bvshr'` and `bvmod_unsafe`.

### CODE REVIEW

**Comment by mtzguido** [comment]
> NB still testing - just wanted to check if ci worked

No problem with using PRs to check this, but `make ci` from a clean repo is pretty much exactly what CI does (and it may also be faster depending on your setup). Make `docker-ci` goes a step further and runs the check within a container, like the CI machine does, but unless you're changing external dependencies `make ci` is usually good enough.

**Comment by amosr** [comment]
Thanks Guido, `make ci` is very helpful

**Comment by amosr** [comment]
Sorry, I marked it as "ready to review", but it's not actually encoding the new bvshl' operator correctly yet.

**Comment by nikswamy** [comment]
Many thanks Amos! I just made a couple of small fixes and merged this. I also checked that this didn't cause any regressions in the related projects in the Everest repo.

As a next step, it might be worth considering a breaking change that swaps the names around to make the primed version of the operators the default ... but that's for another day.

**Comment by amosr** [comment]
Thanks Nik!

**Pull request merged**
