### PR TITLE
Remove nubuild.

### PR DESCRIPTION
**Pull request by sishtiaq**
rm nubuild commands, scripts, references, etc.

### CODE REVIEW

**Comment by msprotz** [comment]
Sorry about the delay in reviewing this... was at POPL then traveling. This looks good. Can you rebase or merge from master? I'll happily merge this tomorrow.

**Comment by sishtiaq** [comment]
@msprotz It's green!

**Comment by msprotz** [comment]
Cool! What's up with the new file examples/Makefile.include? It looks good but I'm curious why this pull request adds it.

**Comment by sishtiaq** [comment]
Sorry about examples/Makefile.include, probably got confused in rebasing.

**Comment by msprotz** [comment]
Thanks Samin.

**Comment by sishtiaq** [comment]
Fixes https://github.com/mitls/mitls-fstar/issues/69

**Pull request merged**
