### PR TITLE
Optimize is_fext_on_domain in normalizer

### PR DESCRIPTION
**Pull request by ctk21**
`is_fext_on_domain` can be called frequently in the normalizer. This function creates a constant list of lids to check against. These lids are not being optimized by the ocaml compiler into a constant list, instead it is reconstructed on each call to `is_fext_on_domain`. 

This PR moves the `on_domain_lids` calculation to the top-level which forces the constant list to be calculated once. The constant list is then used in `is_fext_on_domain`. 

Benchmarking of the change was done (with --admit_smt_queries true) for examples/micro-benchmarks, ulib (building each file again, all other ulib files present) and extraction of the FStar compiler to OCaml:
```
                  Old                               New
                  n       total   user    system    n       total   user    system
micro-benchmarks  61      71.83   67.33   4.049     61      60.61   56.35   3.824
ocaml_extract     38      172.7   167.8   4.87      38      161.4   157.1   4.235
ulib              208     521.4   498     21.78     208     401.9   380.3   20.04
```

### CODE REVIEW

**Comment by msprotz** [comment]
This drives [VERIFY] Vale.AES.X64.AESGCM.fst in HACL* from 13min to 9min, a notoriously normalizer-heavy file. CC @parno for information.

**Comment by msprotz** [comment]
For reference, I also measured this one. Before:
```
[EXTRACT-KRML] Parsers_HRRExtension, 10:12.34
```
after:
```
[EXTRACT-KRML] Parsers_HRRExtension, 4:53.15
```

**Comment by nikswamy** [comment]
Wow, this is amazing.
I'm very curious to see the profiling information that led you to find this bottleneck.

**Comment by ctk21** [comment]
So the profiling steps were:
 - re-compile with landmarks on by changing the `_tags` file: 
```
true: package(landmarks), package(landmarks.ppx)

<src/ocaml-output/FStar_{Main,TypeChecker_Normalize,Ident}.ml>: \
    ppx(`ocamlfind query landmarks.ppx`/ppx.exe --as-ppx --auto)
```
(more on using landmarks with FStar here: https://github.com/FStarLang/FStar/wiki/Profiling-FStar-with-OCaml-Landmarks)
 - run with OCAML_LANDMARKS='on,output=landmarks.out' on the `ChrisCheck` micro-benchmark which gives the following output:
```
Call graph 'bin/fstar.exe --admit_smt_queries true --warn_error -271 --z3cliopt timeout=600000 --use_hints --use_extracted_interfaces true examples/micro-benchmarks/ChrisCheck.fst':
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[  208.93G cycles in        1 calls ]     - 99.98% : Src/ocaml-output/FStar_Main.main
[  208.93G cycles in        1 calls ]     |   - 100.00% : Src/ocaml-output/FStar_Main.go
[  130.82G cycles in  1373019 calls ]     |   |   - 62.61% : Src/ocaml-output/FStar_TypeChecker_Normalize.normalize
[  130.26G cycles in  1373019 calls ]     |   |   |   - 99.58% : Src/ocaml-output/FStar_TypeChecker_Normalize.normalize_with_primitive_steps
[  123.70G cycles in  1373019 calls ]     |   |   |   |   - 94.96% : Src/ocaml-output/FStar_TypeChecker_Normalize.norm
[   96.68G cycles in  5537364 calls ]     |   |   |   |   |   - 78.16% : Src/ocaml-output/FStar_TypeChecker_Normalize.is_fext_on_domain
[   85.71G cycles in 22149456 calls ]     |   |   |   |   |   |   - 88.65% : Src/ocaml-output/FStar_Ident.lid_of_path
[   49.33G cycles in 22149456 calls ]     |   |   |   |   |   |   |   - 57.55% : Src/ocaml-output/FStar_Ident.lid_of_ids
[   39.12G cycles in 22149456 calls ]     |   |   |   |   |   |   |   |   - 79.32% : Src/ocaml-output/FStar_Ident.lid_of_ns_and_id
[    8.06G cycles in 22149456 calls ]     |   |   |   |   |   |   |   |   |   - 20.60% : Src/ocaml-output/FStar_Ident.text_of_path
[    4.92G cycles in 44298912 calls ]     |   |   |   |   |   |   |   |   |   - 12.59% : Src/ocaml-output/FStar_Ident.text_of_id
[    7.99G cycles in 66448368 calls ]     |   |   |   |   |   |   |   -  9.32% : Src/ocaml-output/FStar_Ident.mk_ident
[    1.51G cycles in   737656 calls ]     |   |   |   |   |   -  1.22% : Src/ocaml-output/FStar_TypeChecker_Normalize.decide_unfolding
[    1.16G cycles in   737656 calls ]     |   |   |   |   |   |   - 76.99% : Src/ocaml-output/FStar_TypeChecker_Normalize.should_unfold
[  108.06M cycles in   737656 calls ]     |   |   |   |   |   |   |   -  9.29% : Src/ocaml-output/FStar_Ident.text_of_lid
[    7.47G cycles in   135227 calls ]     |   |   -  3.58% : Src/ocaml-output/FStar_TypeChecker_Normalize.normalize_refinement

...

Aggregated table:
----------------
                                                                        Name;                                             Filename;    Calls;     Time
                                                                        ROOT;                                      src/landmark.ml;        0;  208.97G
                                            Src/ocaml-output/FStar_Main.main;                   src/ocaml-output/FStar_Main.ml:346;        1;  208.93G
                                              Src/ocaml-output/FStar_Main.go;                   src/ocaml-output/FStar_Main.ml:145;        1;  208.93G
                      Src/ocaml-output/FStar_TypeChecker_Normalize.normalize; src/ocaml-output/FStar_TypeChecker_Normalize.ml:7609;  1568353;  152.52G
 Src/ocaml-output/FStar_TypeChecker_Normalize.normalize_with_primitive_steps; src/ocaml-output/FStar_TypeChecker_Normalize.ml:7542;  1568353;  151.86G
                           Src/ocaml-output/FStar_TypeChecker_Normalize.norm; src/ocaml-output/FStar_TypeChecker_Normalize.ml:2518;  1589165;  144.65G
              Src/ocaml-output/FStar_TypeChecker_Normalize.is_fext_on_domain; src/ocaml-output/FStar_TypeChecker_Normalize.ml:2475;  6495709;  114.69G
                                    Src/ocaml-output/FStar_Ident.lid_of_path;                   src/ocaml-output/FStar_Ident.ml:92; 25983356;  101.62G
                                     Src/ocaml-output/FStar_Ident.lid_of_ids;                   src/ocaml-output/FStar_Ident.ml:82; 25986204;   58.53G
                               Src/ocaml-output/FStar_Ident.lid_of_ns_and_id;                   src/ocaml-output/FStar_Ident.ml:66; 25986204;   46.42G
Src/ocaml-output/FStar_TypeChecker_Normalize.reduce_or_remove_uvar_solutions; src/ocaml-output/FStar_TypeChecker_Normalize.ml:7873;       57;   12.41G
                                       Src/ocaml-output/FStar_Ident.mk_ident;                   src/ocaml-output/FStar_Ident.ml:29; 79018592;    9.67G
                                   Src/ocaml-output/FStar_Ident.text_of_path;                   src/ocaml-output/FStar_Ident.ml:54; 26005263;    9.55G
          Src/ocaml-output/FStar_TypeChecker_Normalize.remove_uvar_solutions; src/ocaml-output/FStar_TypeChecker_Normalize.ml:7895;       31;    8.08G
```
(be careful reading too much into the cycle counts; these include the profiling instrumentation overhead and the code is different from the running code as profiling instrumentation changes inlining)
- scratch head to see if there is anything obvious I could do with `normalize`, `normalize_with_primitive_steps` and `is_fext_on_domain`.
- notice that a large amount of the work in `is_fext_on_domain` is coming from `lid_of_path` but that the inputs are all constant. try out hoisting the constant out of `is_fext_on_domain`.
- rerun benchmarks with (and without) my change (the hooks for this are in #1795) across ulib and micro-benchmarks.

Admittedly I had prior information to know to try `TypeChecker_Normalize` and `Ident`. This came from conversations with you guys and also from seeing profiling outputs from perf/landmarks already.

**Pull request merged**
