### PR TITLE
Include documentation in #info requests

### PR DESCRIPTION
**Pull request by cpitclaudel**
This builds on top of my sigelt refactoring PR to provide documentation in fstar-mode:

screenshot from 2017-03-31 04-15-25

### CODE REVIEW

**Comment by darrenge** [comment]
Sorry about that merge. I tried to get it to fire off the CI build in hopes that the merge would do that. I have seen one time where the merge fired off the CI.

**Comment by msprotz** [comment]
I'm manually kicking off a build on my branch that contains, among others, this pull request. If everything is green, I'll merge everything at once.

**Comment by cpitclaudel** [comment]
(blocked by #925)

**Comment by cpitclaudel** [comment]
Closed in favor of #931

**Pull request closed without merging**
