### PR TITLE
Adding FStar.Printable.fst with test by proof in tests/printable usin…

### PR DESCRIPTION
**Pull request by briangmilnes**

### CODE REVIEW

**Comment by mtzguido** [comment]
Hi Brian, thanks! It mostly looks good, I just have one comment. There's no need to make this `tests/printable` directory, nor check F*'s output. Just putting this test file in, say, `tests/micro-benchmarks` is enough to get into the existing rules which will check that everything succeeds.

Could you make that change? Simply pushing to your branch will update the PR accordingly.

**Comment by briangmilnes** [comment]
Sure, but I've been hacking a clean FStarUnit testing framework, in which I
would add the one test that
does not run in normalization. If some of you folks look at it and like it.
Otherwise, I'll just do it the easy way.

**Comment by mtzguido** [comment]
Ah, I see. Could we anyway make that a separate PR, and not block this one on the unit testing stuff?

**Comment by briangmilnes** [comment]
No problem. Likely tomorrow.

I'll do a pull and the merge first, as per some CONTRIBUTING doc I found.

-B

**Comment by briangmilnes** [comment]
Guido, TestPrintable moved to micro-benchmarks. All tests completed.

**Comment by mtzguido** [comment]
Hi Brian, I see you've merged master, but I don't see any other changes. Did you maybe forget to push?

**Comment by briangmilnes** [comment]
Darn it, I did push. Just did it again too. I pushed to the master not my
branch it appears.

Do you know the fix?

Now a push to my branch is rejected. Give me a few unless you know the
recipe.

**Comment by mtzguido** [comment]
I see it now! Just please also remove the change to `tests/Makefile`

**Comment by briangmilnes** [comment]
Done, the printable branch looks good with makefile change done.

**Pull request merged**
