### PR TITLE
sishtiaq_pp

### PR DESCRIPTION
**Pull request by sishtiaq**
Work for https://github.com/FStarLang/FStar/issues/36.

### CODE REVIEW

**Comment by tahina-pro** [comment]
Tried to merge master` into `sishtiaq_pp` as a separate `taramana_pp` branch for testing purposes: it seems to work, I have green light.

**Comment by sishtiaq** [comment]
Hi Tahina, I don't understand the "merge master into sishtiaq_pp as a separate taramana_pp branch". Shall we keep this branch, sishtiaq_pp, as the "master" for the prettyprinting work?

**Comment by tahina-pro** [comment]
Sure, no problem using your branch. I was only using my branch in case my merge would fail, but now since it succeeds, let me fast-forward `sishtiaq_pp` to match `taramana_pp`. This will automatically update this pull request.

**Comment by tahina-pro** [comment]
Jut fast-forwarded. We can now continue working on `sishtiaq_pp`

**Pull request merged**
