### PR TITLE
--MLish and extraction

### PR DESCRIPTION
**Pull request by mtzguido**
This is meant to fix the snapshots diffs observed locally. The problem is that some files in ulib (those that the compiler depends on) are extracted twice: once by the extraction of the compiler and once for the library snapshot. Both of these write to the same file, so any discrepancy between them causes a racy build.

I may be forgetting the details of our discussion some time ago but this dual extraction is a bit problematic, first it's repeated work, and second can have these subtle problems.

This PR makes everything extract with --MLish, which works fine after a fix or two. 

What I also don't understand is if there's a reason why we extract with --MLish.. why does extraction care? FWIW I tried also *disabling* --MLish on extraction everywhere and this also works.

@nikswamy @tahina-pro any opinions?

### CODE REVIEW

**Comment by mtzguido** [comment]
> FWIW I tried also _disabling_ --MLish on extraction everywhere and this also works.

I think I would like this better. And make `--MLish` meaningless for extraction.

**Comment by nikswamy** [comment]
> What I also don't understand is if there's a reason why we extract with --MLish.. why does extraction care?

We do not normalize terms for extraction when MLish is on. I think it was intended as a performance benefit for extracting the compiler sources, but maybe it doesn't matter any more.

https://github.com/FStarLang/FStar/blob/master/src/extraction/FStar.Extraction.ML.Term.fst#L1882

**Comment by nikswamy** [comment]
>> FWIW I tried also disabling --MLish on extraction everywhere and this also works.
> I think I would like this better. And make --MLish meaningless for extraction.

Me too.

**Comment by mtzguido** [comment]
Updated with:
- No MLish special treatment on extraction
- Do not pass the flag on --extract, since it does not do anything anyway
- Separate the extraction outputs of the compiler and ulib, going into `src/ocaml-output/fstarc/*.ml` and `src/ocaml-output/fstarlib/*.ml`. These two are then copied **in that order** into `ocaml/fstar-lib/generated` when we are creating the snapshot. This eliminates the race, and I find it slightly cleaner. But we should work on improving the build instead.

Also FWIW I tried a build of the library without any compiler files, the result is very small, down to 1.7MB from 35M.
```
-r-xr-xr-x 1 guido guido 1.7M Dec  8 13:35 fstar_lib.cmxs
```

**Pull request merged**
