### PR TITLE
Fix type error in OCaml 4.05 printer

### PR DESCRIPTION
**Pull request by drvink**
This fixes building under OCaml 4.05.

### CODE REVIEW

**Comment by catalin-hritcu** [comment]
@victor-dumitrescu Any news about this one? It seems to block people on Arch: https://aur.archlinux.org/pkgbase/fstar/

**Comment by catalin-hritcu** [comment]
Marked this as high priority, since it's blocking for people on latest OCaml. The proposed fix doesn't seem good enough though. It makes the original problem
```
+ ocamlfind ocamlc -c -g -annot -bin-annot -thread -package stdint -package compiler-libs -package compiler-libs.common -package menhirLib -package dynlink -package pprint -package ulex -package yojson -package batteries -package zarith -I src/extraction/ml -I src/ocaml-output -I src/fstar/ml -I src/parser/ml -I src/tactics/ml -I src/basic/ml -I src/prettyprint/ml -I ulib/ml -o src/extraction/ml/FStar_Extraction_ML_PrintML.cmo src/extraction/ml/FStar_Extraction_ML_PrintML.ml
File "src/extraction/ml/FStar_Extraction_ML_PrintML.ml", line 217, characters 2-1681:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
MLE_TApp _
File "src/extraction/ml/FStar_Extraction_ML_PrintML.ml", line 362, characters 23-30:
Error: Unbound type constructor tyattrs
Hint: Did you mean attrs?
```
go away. But there are still problems when bootstrapping:
```
mkdir -p boot
../bin/fstar-any.sh --hint_info --eager_inference --lax --MLish --no_location_info --odir ocaml-output --codegen OCaml --include ../ulib --include boot --include basic --include extraction --include format --include fsdoc --include fstar --include parser --include prettyprint --include reflection --include smtencoding --include syntax --include tactics --include tosyntax --include typechecker tactics/FStar.Tactics.Types.fs tactics/FStar.Tactics.Basic.fs tactics/FStar.Tactics.Embedding.fs tactics/FStar.Tactics.Native.fs boot/FStar.Tactics.Interpreter.fst --extract_namespace FStar.Tactics --no_extract FStar.Tactics.Native
Extracted module Types
Extracted module Result
Extracted module Basic
Extracted module Embedding
Extracted module Interpreter
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
File "src/extraction/ml/FStar_Extraction_ML_PrintML.ml", line 217, characters 2-7: Pattern matching failed
```

**Comment by drvink** [comment]
@catalin-hritcu Sorry, looks like I missed adding a diff hunk in the original commit. Repushed; let me know if this one works for you.

**Comment by mtzguido** [comment]
Works for me, so in favor of merging.

A less important detail is that we now have these new warnings:
```
File "ulib/ml/FStar_Char.ml", line 7, characters 17-31:
Warning 3: deprecated: Char.lowercase
Use Char.lowercase_ascii instead.
File "ulib/ml/FStar_Char.ml", line 10, characters 17-31:
Warning 3: deprecated: Char.uppercase
Use Char.uppercase_ascii instead.
```
but those functions don't exist in 4.02.3, so I'd leave this as is for now.

**Comment by catalin-hritcu** [comment]
@drvink Thanks a lot for the fix!
@mtzguido Thanks for confirming. It also works for me, so I merged this.

**Comment by wintersteiger** [comment]
Same problem in the stable branch, should we cherry-pick this fix into stable?

**Comment by mtzguido** [comment]
As far as I can tell this change has already made it into the `stable` branch of F*.

**Comment by wintersteiger** [comment]
My intern just hit that problem via the `everest` script (with OCaml 4.05 installed), so whatever the version of stable that `everest` clones still has the problem.

**Comment by msprotz** [comment]
Can we get rid of the master branch of everest and just merge verify into master? It looks like the intern is on an ancient set of hashes from at least a year ago.

**Comment by wintersteiger** [comment]
He's using __stable__, of FStar, not verify or master, because that's what the everest script picked for him.

**Comment by msprotz** [comment]
I think the everest script still contains a hash that points to F* stable, but an old revision on stable that doesn't have the fix Guido mentions. If your intern used the everest script on the stable branch, he's likely running a version of F* from the stable branch *without* the fix

**Comment by wintersteiger** [comment]
Aha! Yes, I didn't check whether it uses a specific hash or just the branch name. Maybe we can just change the stable hash then.

**Pull request merged**
