### PR TITLE
Arrays with selectors and permissions

### PR DESCRIPTION
**Pull request by tahina-pro**
This pull request implements a library of arrays for Steel with permissions and selectors.

# Arrays
`Steel.Array.array t` represents an array of `t` elements, with a ghost (non-stateful) length. It supports:

* spatial split and join via a notion of mergeable adjacent subarrays and a ghost calculus with an associativity rule: if `a` and `b` are adjacent, then `merge a b` is defined, and if `merge a b` and `c` are adjacent, then `b` and `c` are adjacent, and `a` and `merge b c` are adjacent, and `merge (merge a b) c == merge a (merge b c)`.
* temporal share and gather via fractional permissions, which can be applied to subarrays.

A `Steel.Array.array t` is implemented as a record of:

* a "base array" which is a sequence of references to `t`
* a `from` index marking the beginning of the array
* a ghost `to` index marking one past the end of the array

in such a way that an array with full permission is freeable if, and only if, its indices are from 0 to the length of the base array.

# Array "pointers"

**Warning: this is EXPERIMENTAL**

`Steel.ArrayPtr` is a first attempt at representing arrays as C pointers, but in a very restricted way. 

* Spatial split and join: if `x` is an array viewed as a "pointer", then, instead of returning a pair of arrays, `split x i` will return one "pointer" `y` to represent the elements from index `i` and **at the same time** "cut" `x` to have it represent only the elements up to index `i-1`. Similarly, `merge x y` (if adjacent) will "restore" `x` by extending it to cover all elements in `y`. These are made possible by making `to` a ghost reference (rather than just a ghost value) in the implementation.

* Similarly, the temporal fractional permission also becomes a ghost reference, in such a way that `share x` returns a new "pointer" with half permission, with the permission on `x` also being cut by half at the same time.

# Dependencies 

This pull request depends on #2297 

This pull request (especially `Steel.ArrayPtr`) is a basis for https://github.com/project-everest/everparse/tree/taramana_steel currently under development.

### CODE REVIEW

**Comment by denismerigoux** [comment]
Thanks Tahina ! A few comments:

> spatial split and join via a notion of mergeable adjacent subarrays and a ghost calculus with an associativity rule: if a and b are adjacent, then merge a b is defined, and if merge a b and c are adjacent, then b and c are adjacent, and a and merge b c are adjacent, and merge (merge a b) c == merge a (merge b c).

So this amounts to re-creating a monoïdal proof structure for determining whether two things can be merged with each others. The point of making Steel was to eliminate the monoïdal proof structure of heap disjointness (thanks to separation logic). Is there a reason why not to expose the `merge` predicate as an arithmetic proposition on the start indexes and lengths of all the buffer involved?

> A Steel.Array.array t is implemented as a record of:
> *    a "base array" which is a sequence of references to t

As stated in our exchanges, using a sequence of references instead of a reference to a single sequence will prevent you from defining PCM that govern the entire array. It does not seem to be a short-term problem but might prove a limitation if we want to exercise more advanced features of Steel with this array proposition.

> Spatial split and join: if x is an array viewed as a "pointer", then, instead of returning a pair of arrays, split x i will return one "pointer" y to represent the elements from index i and at the same time "cut" x to have it represent only the elements up to index i-1. Similarly, merge x y (if adjacent) will "restore" x by extending it to cover all elements in y. These are made possible by making to a ghost reference (rather than just a ghost value) in the implementation.

This makes sense to me.

> Similarly, the temporal fractional permission also becomes a ghost reference, in such a way that share x returns a new "pointer" with half permission, with the permission on x also being cut by half at the same time.

Also makes sense to me. I know that @nikswamy was very attached to having permissions as a index to the type of arrays rather than something stored ghostly in the heap, so you might want to check for that.

**Comment by tahina-pro** [comment]
Thank you Denis for your feedback so far!

> So this amounts to re-creating a monoïdal proof structure for determining whether two things can be merged with each others. The point of making Steel was to eliminate the monoïdal proof structure of heap disjointness (thanks to separation logic). Is there a reason why not to expose the `merge` predicate as an arithmetic proposition on the start indexes and lengths of all the buffer involved?

For the EverParse application, my paramount goal is to hide as much of offset reasoning as possible. This is why, at least at this point, I am investigating what is the "smallest" - or least user-invasive - way to formalize two arrays being adjacent. The "monoïdal proof structure" I am proposing will definitely not replace separation logic, since its only goal is to prove that two arrays are adjacent; disjointness will still rely on separation logic. However, I understand that making the definitions of `merge`, `adjacent` etc. transparent over base and offset boundaries of an array may make SMT reasoning faster. So there is a tension here between proof efficiency and user abstraction.

A possible compromise could be to expose base and boundaries but as *abstract* types, and define `merge` and `adjacent` transparently on top of them.

**Comment by tahina-pro** [comment]
Argh. My `ArrayPtr` partial model for C pointers for arrays still allows some undefined behavior. Consider the following code:
```
let arrayptr_ub () : SteelT (AP.t bool) emp (λ res → AP.varrayptr res)
= let a = AP.alloc false 1ul in
  let x : Ghost.erased (AP.v bool) = gget (AP.varrayptr a) in
  assert (A.length x.AP.array == 1);
  let res = AP.split a 1ul in
  let xa : Ghost.erased (AP.v bool) = gget (AP.varrayptr a) in
  let xres : Ghost.erased (AP.v bool) = gget (AP.varrayptr res) in
  A.merge_zero_right xa.AP.array xres.AP.array;
  AP.free a;
  let foo = AP.split res 0ul in // UB: res+0 on a deallocated pointer
  AP.join res foo;
  return res
```
I expect `AP.split a i` to be extracted as `a+i`, which is undefined behavior after `a` is deallocated, as @msprotz reminded us today. So, basically, **`varrayptr` MUST NOT be defined as `emp` for zero-length subarrays**. The problem is that we cannot, either, say that a vprop recording the liveness of the base array can be indefinitely duplicated. So, what should we do?

**Comment by R1kM** [comment]
I'd like to understand a bit more the usecases for zero-length arrays.
So far, it seems it's needed/useful when looping over an array: a common Low* pattern is to have a loop taking as argument an array with the invariant that it remains live. Inside the loop, we iterate by taking the tail of the array, exiting the loop when the length is 0.

Even if a 0-length array is live in Low*, the only valid operation is sub since preconditions on the indices will always prevent access/updates. As you mentioned, this operation should actually be prevented since it's an undefined behaviour.

Going for a new design in Steel, what would you think of split returning a "0-length or live" array predicate, called for instance `carray`? This would give a simple invariant for loops, while forcing all Steel operations to operate on a `varray` instead. Going from `carray` to `varray` would require to know that the length is not 0. You could imagine having a wrapper that directly gives you a `varray` when you know this statically, simplifying most usecases of split.

**Comment by msprotz** [comment]
> As you mentioned, this operation should actually be prevented since it's an undefined behaviour.

pointer addition is only UB if the pointer is past its lifetime, right?

I guess this has been discussed before but what would be the cons of having a `live` slprop that comes in addition to the spatial assertion?

**Comment by tahina-pro** [comment]
> Even if a 0-length array is live in Low*, the only valid operation is sub since preconditions on the indices will always prevent access/updates. As you mentioned, this operation should actually be prevented since it's an undefined behaviour.

There is also comparison to NULL (and maybe also other comparisons between subarray pointers of the same array, but I haven't modelled them yet, since we are not sure whether we really want to support them.)

> Going for a new design in Steel, what would you think of split returning a "0-length or live" array predicate, called for instance carray? This would give a simple invariant for loops, while forcing all Steel operations to operate on a varray instead. Going from carray to varray would require to know that the length is not 0. You could imagine having a wrapper that directly gives you a varray when you know this statically, simplifying most usecases of split.

I think your proposal is equivalent to forbidding users to take subarrays of a zero-sized array, in which case we might not need a distinguished `carray` vprop.

Alas, for EverParse, I'm not sure we can afford that limitation: if we were to give special treatment to zero-sized arrays as you are proposing, then every time we would like to access a field of a struct, or an element of a list, we would need to know that the input buffer that contains the struct, or the list, is nonempty, which is not guaranteed since the parser specification against which the struct or the list has been validated may very well not have consumed anything (i.e. the byte representation may very well be an empty byte array.)

**Comment by tahina-pro** [comment]
> pointer addition is only UB if the pointer is past its lifetime, right?

Yes, as illustrated in my example: `let foo = AP.split res 0ul` is undefined behavior since it is performed after freeing `a`, of which `foo` is a zero-length subarray.

> I guess this has been discussed before but what would be the cons of having a live slprop that comes in addition to the spatial assertion?

If this "live slprop" is separate from spatial assertions, then I guess it would only talk about the base allocation unit where the pointers live. Then, if you have a function `f` that takes two disjoint pointers, you still want to allow those two pointers to be part of the same allocation unit, so I'm not sure how many liveness slprops `f` would require.

As I mentioned earlier, we cannot indefinitely duplicate the liveness slprop of the base allocation unit. Unless we use a fractional permission to track such duplications. This permission would be distinct from the read/write permission.

**Comment by msprotz** [comment]
> As I mentioned earlier, we cannot indefinitely duplicate the liveness slprop of the base allocation unit. Unless we use a fractional permission to track such duplications. This permission would be distinct from the read/write permission.

Can we write index and update operations that require only a non-null fraction of the liveness predicate? `free` would simply require the full liveness permission, meaning that you have to recombine everything to get the base pointer, which in turns allows you to `free` it

**Comment by tahina-pro** [comment]
For `index`, it should be fine, but I guess `update` needs some form of write permission, which is why I propose to keep those two permissions separate; I expect an empty array not to have both permissions set to 1.

**Comment by R1kM** [comment]
> There is also comparison to NULL (and maybe also other comparisons between subarray pointers of the same array, but I haven't modelled them yet, since we are not sure whether we really want to support them.)

Could you remind me what are the cases where a comparison to NULL is a UB? I remember we discussed it in the past, but can't remember the details

> Alas, for EverParse, I'm not sure we can afford that limitation: if we were to give special treatment to zero-sized arrays as you are proposing, then every time we would like to access a field of a struct, or an element of a list, we would need to know that the input buffer that contains the struct, or the list, is nonempty, which is not guaranteed since the parser specification against which the struct or the list has been validated may very well not have consumed anything (i.e. the byte representation may very well be an empty byte array.)

I'm trying to understand this better. Do you have a small code snippet that exhibits this behaviour? Are you saying that we might have a case where the bytearray to parse is entirely empty? If so, what would the access look like?

**Comment by R1kM** [comment]
> For `index`, it should be fine, but I guess `update` needs some form of write permission, which is why I propose to keep those two permissions separate; I expect an empty array not to have both permissions set to 1.

I agree with Tahina. You need to differentiate between "I have the permission to free this array because I have permission on the full allocation unit" and "I have permission to write this subarray because I'm not sharing this slice with anybody else".

I'm slowly warming up to the additional fractional permission, although it seems heavy to handle, as it requires more bookkeeping with real arithmetic. But I'd like to keep brainstorming to see if we could do something simpler.
It seems we only need this dichotomy to model the liveness of zero-length arrays, can we start by making a complete list of operations we need on such arrays?

**Comment by tahina-pro** [comment]
@R1kM re. zero-sized arrays: my main application is the [EverParse+Steel](https://github.com/project-everest/everparse/pull/54/files#diff-9ad3e591a01f42bb733c8168885a167ae37e98bbb24236149367f1321f3ff12c ) integration. Assume I have a byte array, with `varrayptr a`, Then, I want to run a validator on `a` (with respect to some parser specification `p`), so that, if it succeeds, I obtain `star (vparse p a) (varrayptr y)` where `y` is the remaining unparsed part of `a`. When specifying and implementing such a validator, I should do it generically, regardless of whether `a` is zero-sized or whether `p` consumes some bytes or not.

**Comment by tahina-pro** [comment]
This PR should be superseded by #2319

**Comment by R1kM** [comment]
@tahina-pro but how are the validators themselves implemented? i.e. couldn't they take a `carrayptr` which would be the disjunction between a valid array or a zero-length array?

**Comment by tahina-pro** [comment]
They could (since validators know the size of the input array at runtime), but then they would need to frequently test whether the size is zero or not before doing a `split` (or, alternatively, `split` itself would do that test, as proposed in https://github.com/FStarLang/FStar/pull/2319#issuecomment-862896700 )

**Pull request closed without merging**
