### PR TITLE
Incremental Z3 queries even in the presence of unsat cores (aka hints)

### PR DESCRIPTION
**Pull request by nikswamy**
Incremental Z3 queries (i.e., queries fed to a running Z3 process which accumulates a context) are much faster than queries to a fresh instance of Z3.

Yet, when we run with --use_hints, nearly every query is sent to a fresh Z3 instance, since we reset the solver before and after using a hint (we must, since a hint has to prune the context)

This PR aims to retain incremental queries even in the presence of hints by always maintaining a background Z3 process that incrementally accumulates a context.

When using a hint, we fire up a new Z3 instance for it without disturbing the background Z3 process.

### CODE REVIEW

**Comment by nikswamy** [comment]
Would be great to get another set of eyes on this. @aseemr @mtzguido ?

**Comment by aseemr** [comment]
Sorry missed this one. Will review today.

**Comment by wintersteiger** [comment]
Looks good to me too! Good observation - I'm curious, did you run any performance experiments yet?

@arpg-rebola you may want to rebase your code onto these changes

**Comment by nikswamy** [comment]
Please see this commit: https://github.com/FStarLang/FStar/pull/1635/commits/89ba5d3a0b5d137cd97cb2f45effb0431497b978

I am now only allowing cache hits in case we are running a fresh query (i.e., when we are using a hint)
Previously, we would allow cache hits even after a hint failed.

This is dubious: I think it worked only because we were generally always using `--use_hints --use_hint_hashes` together. But, used independently, --use_hint_hashes may have been unsound, since it would only hash the *delta* of the new query, not the entire context + query.

This revealed itself with the other changes here since we now have an increment background Z3 process.

So, now I am forbidding the use of hint hashes except for fresh queries (which really contain the entire context + query).

**Pull request merged**
