### PR TITLE
Add an example of binary tree enumeration

### PR DESCRIPTION
**Pull request by cpitclaudel**
(This is not intended to be merged as-is; I'm posting it here as suggested by @catalin-hritcu on Slack, for discussion)

Hi all,

Here's the example that I mentioned to @nikswamy at SNAPL.  The idea is to define and prove the soundness and completeness of a function that enumerates binary trees of a given size, in a modular way (not as one giant function). It's interesting to compare this implementation to the corresponding Coq code: F* makes defining the dependently typed functions and proving termination really nice (whereas it's a real pain in Coq), but I found the F* proofs much more difficult to write than the corresponding Coq ones.  I expect this is in part due to my lack of F* experience :)

I took notes while writing the file, and collected these notes as comments and questions in the source.  I'd love to get feedback on these; I expect I took the wrong approach or misunderstood things in some places, and on the other hand I hope some of these can lead to improvements in F*.

Cheers,
Clément.

(I gave the file a `.fs` extension to get syntax highlighting)

### CODE REVIEW

**Comment by jroesch** [comment]
I posted this in the Lean in slack to see what it would like now that we support well-founded recursion, thought it might be fun to share here.

The implementation is from @digama0:
```
namespace bin_tree_enumeration

def pairs_with_sum' : Π (m n d), m + n = d → list {p : ℕ × ℕ // p.1 + p.2 = d}
| 0     n d h := [⟨(0, n), h⟩]
| (m+1) n d h := ⟨(m+1, n), h⟩ :: pairs_with_sum' m (n+1) d ((nat.succ_add m n).symm.trans h)

def pairs_with_sum (n) : list {p : ℕ × ℕ // p.1 + p.2 = n} :=
pairs_with_sum' n 0 n rfl

inductive bin_tree
| leaf : bin_tree
| branch : bin_tree → bin_tree → bin_tree
open bin_tree

def size : bin_tree → ℕ
| leaf := 0
| (branch l r) := size l + size r + 1

def trees_of_size : Π s, list {bt : bin_tree // size bt = s}
| 0     := [⟨leaf, rfl⟩]
| (n+1) := let IH := λ s (h : s < n + 1), trees_of_size s in
  do ⟨(s1, s2), (h : s1 + s2 = n)⟩ ← pairs_with_sum n,
     ⟨t1, sz1⟩ ← IH s1 $ by apply nat.lt_succ_of_le; rw -h; apply nat.le_add_right,
     ⟨t2, sz2⟩ ← IH s2 $ by apply nat.lt_succ_of_le; rw -h; apply nat.le_add_left,
     return ⟨branch t1 t2, by rw [-h, -sz1, -sz2]; refl⟩

def pws'_complete : ∀ k m n d {h e} {h' : m + e = d}, n + k = e →
  (⟨(m, e), h'⟩ : {p : ℕ × ℕ // p.1 + p.2 = d}) ∈ pairs_with_sum' (m + k) n d h
| 0     0     n d h ._ h' rfl := or.inl rfl
| 0     (m+1) n d h ._ h' rfl := or.inl rfl
| (k+1) m     n d h e  h' he  := or.inr $ pws'_complete k m (n+1) d ((nat.succ_add n k).trans he)

def pws_complete (m n) : (⟨(m, n), rfl⟩ : {p : ℕ × ℕ // p.1 + p.2 = m + n}) ∈ pairs_with_sum (m + n) :=
pws'_complete n m 0 (m + n) (zero_add _)

def tos_complete_inner : ∀ s (t : bin_tree) (h : size t = s),
  (⟨t, h⟩ : {bt : bin_tree // size bt = s}) ∈ trees_of_size s
| 0     leaf          h := by simp [trees_of_size]; refl
| 0     (branch t t') h := absurd h (nat.succ_ne_zero _)
| (n+1) leaf          h := absurd h (nat.succ_ne_zero _).symm
| (n+1) (branch t t') h :=
  match n, h, λ s (h : s < n + 1), tos_complete_inner s,
    (nat.no_confusion h id : size t + size t' = n) with ._, h, IH, rfl :=
    begin
      simp [trees_of_size],
      apply list.mem_bind (pws_complete _ _),
      simp [trees_of_size._match_3],
      apply list.mem_bind (IH _ (nat.lt_succ_of_le (nat.le_add_right _ _)) _ rfl),
      simp [trees_of_size._match_2],
      apply list.mem_bind (IH _ (nat.lt_succ_of_le (nat.le_add_left _ _)) _ rfl),
      simp [trees_of_size._match_1],
      apply list.mem_cons_self,
    end
  end

def tos_complete (t : bin_tree) :
  (⟨t, rfl⟩ : {bt : bin_tree // size bt = size t}) ∈ trees_of_size (size t) :=
tos_complete_inner _ t rfl

end bin_tree_enumeration
```

**Comment by nikswamy** [comment]
@mtzguido could it be time to attempt this kind of example with tactics? Several of @cpitclaudel's concerns about having to be very explicit about lemma applications etc. should be reduced with things like apply_lemma. WDYT?

**Comment by cpitclaudel** [comment]
@jroesch Interesting, thanks! Lean seems to be roughly halfway between F* and Coq — the proofs in Coq are cleaner than the ones in Lean AFAICT, but the function definitions are nicer in Lean. I really like F* for the function definitions (although the monadic style for trees_of_size in Lean is nice! — and conversely the explicit type applications are a bit annoying in F*), but the proofs were a bit painful.
(Of course, you need to take into account the fact that I've written Coq code full time for roughly three years, vs. 3 hours for F*). Maybe an F* expert could give a better implementation than mine :)

**Comment by digama0** [comment]
I should mention that there are a number of proof styles in Lean, with a range of explicitness and clarity possibilities. The proof I wrote above is on the "terse" side of things, in case it wasn't obvious. The tactic proofs are of course difficult to follow without the computer to guide you as well.

**Comment by cpitclaudel** [comment]
@nikswamy Oh, I didn't expect this to be merged (though it's fine that it was, of course :) — I'm pretty sure there are plenty of things that could be better in that file.  Hopefully someone with more F* chops than me can have a look and see what could be improved (@catalin-hritcu suggested the PR format to make it easier to leave comments).

**Comment by nikswamy** [comment]
It's a non-trivial example and I prefer to add it to master to keep it under CI. I hope some of us can find some time to try out some alternative styles of proof there.

**Comment by cpitclaudel** [comment]
> It's a non-trivial example and I prefer to add it to master to keep it under CI. 

Makes sense; thanks! 

> I hope some of us can find some time to try out some alternative styles of proof there.

There's no hurry — I won't actually be working on F* until mid-july.

**Pull request merged**
