### PR TITLE
Refactor sigelt -> sigelt' (inductive) + sigelt (record w/ range and docs)

### PR DESCRIPTION
**Pull request by cpitclaudel**
Part of #911.  This adds a `doc` field on sigelts (that's the easy part), which requires refactoring to change sigelt into a record (that's the painful part).

Assuming this is the right way to go, can we expose that docstring in the interactive protocol?

### CODE REVIEW

**Comment by msprotz** [comment]
I'm manually kicking off a build on my branch that contains, among others, this pull request. If everything is green, I'll merge everything at once.

**Comment by cpitclaudel** [comment]
Thanks! This might need a bit of review.  I went by what the comment in the source said, but it's a pretty large change (though most of it is mundane).  And I haven't run an OCaml build yet.

**Comment by msprotz** [comment]
Ok, this doesn't compile with OCaml...

**Comment by cpitclaudel** [comment]
Yup, I used "as" in a pattern match, and apparently F* doesn't like that :/

**Comment by cpitclaudel** [comment]
@msprotz Let me update things and compile them in OCaml; I'll ping you as soon as its done :)

**Comment by cpitclaudel** [comment]
Question: what's the right place to put the definition of fsdoc in? It used to live in `Parser.AST`, but now I need to access it from `Syntax.Syntax`.  I moved it there initially, but that causes the OCaml build to fail (fsdoc is unbound in `Parser.Parse.fsti`)

**Comment by cpitclaudel** [comment]
Or maybe it's ok to add an extra `Open` to parse.fsi?

**Comment by cpitclaudel** [comment]
Ok, with the latest commit it builds in OCaml too.

**Comment by cpitclaudel** [comment]
Closing this in favor of the #925 :)

**Pull request closed without merging**
