### PR TITLE
Extraction: Fixing #1072 and other things

### LINKED ISSUE #1072: Extraction: caveat about polymorphic mutual recursion
OCaml is tricky. When two functions are mutually recursive, and there's a type variable `'a` in one of the two, the "liveness" of that variable is shared across both definitions. This means, in particular, that when `g` calls `f`, `f`'s type variable might be unified preventing it from being polymorphic.

Here's a source F* example:
```
module A

let rec f (x : 'a) : Dv 'a =
    x
and g (x : int) : Dv int =
    f x

let x : unit = f ()
```
(`f` is not even recursive in this example, but that's besides the point)

F* accepts this, since `f` was typed at `'a -> Dv 'a`. When extracting to OCaml, we get roughly:
```
let rec f x = x
and g: int -> int = fun x  -> f x

let x: unit = f ()
```
And this fails with
```
File "A.ml", line 3, characters 16-18:
Error: This expression has type unit but an expression was expected of type
         int
```
This is because `f` was inferred to have type `int -> int` because of the call in `g`'s body. Adding type annotations for arguments and results doesn't fix the problem, and the real fix seems to be using an explicit polymorphic annotation (the `'a. ...` part):
```
let rec f : 'a. 'a -> 'a = fun x -> x
and g: int -> int = fun x  -> f x
let x: unit = f ()
```

Reference: http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec227

Thanks a lot to @Armael for helping with this.

### PR DESCRIPTION
**Pull request by mtzguido**
Please don't merge this as-is.

In an attempt to fix #1072, which requires adding explicit polymorphism annotations (c.f. [here](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec227)), I discovered some other problems in extraction. This pull request fixes most of them, with two open problems still (hoping to get suggestions on them).

The solution I had in mind for #1072 is adding type annotations on **every** top-level, and annotating **every** polymorphic type variable.

Simply turning on type annotations for top levels (7959d37) would cause failures in many places. Mainly caused by 1) prims.ml was bad (easily fixed) 2) the value restriction in OCaml and coertions (needed to eta-expand some coertions) 3) when thunking a definition, we were not reflecting that on the type.

1) and 3) are easily fixed. The fix for 2) (eta-expanding) works fine, but will give rise to many many warning about unused arguments. Take for example this assumption:
```
assume val f : unit -> int
```
This used to generate something similar to
```
let f = Obj.magic (fun uu___5 -> failwith "Not yet implemented:f")
```
While now it will generate
```
let f : unit -> int = fun a0 -> (Obj.magic (fun uu___5 -> failwith "Not yet implemented:f")) a0
```
Which complains with
```
File "A.ml", line 3, characters 67-70:
Warning 20: this argument will not be used by the function.
```
Curiously, the parenthesis around `Obj.magic (fun ... )` make a difference: taking them out removes the warning. Should we just ignore this warning altogether? Is there some better solution to this? The eta-expansion is needed for cases such as this one:
```
let f: 'a. 'a -> 'a =
    Obj.magic (fun uu____5  -> failwith "Not yet implemented:f")
```
Which gives a *hard error*
```
Error: This definition has type 'a -> 'a which is less general than
         'a0. 'a0 -> 'a0
```

As a separate issue, abstract types seem to be badly handled *somewhere* in extraction, since 
```
module Abs

abstract let set a = a -> Type0

val empty : (#a:Type) -> set a
let empty = fun #a x -> False
```
will generate,  for `empty`, 
```
let empty: 'Aa . 'Aa set = Obj.magic (fun x  -> ())
```
whereas without the `abstract` qualifier we get
```
type 'Aa empty = Prims.unit
```
which I think is the correct one? I couldn't for the life of me find out where this qualifier is interfering, maybe someone more savvy with compiler internals has a clue. In any case, anyone confirming that the second one (`type ...`) is the correct one would be great.

There's a (crap) commit which takes the abstract qualifier of `ulib/FStar.TSet.fst`, the only problematic file. With this change, the compiler bootstraps and runs, as well as pass regressions. Admittedly, I haven't tried miTLS or HACL yet. (Also, the change to the OCaml pretty printer is only for 4.02.3! I'll port it to all of them when we know this is sane)

I'd like to finish this relatively soon as it would prevent an awful hack in the tactics branch, which also only works with an OCaml-obtained snapshot, and has bitten some of us (including me after forgetting about it, Nik, Nick and Bryan).

So, main 3 questions:
- Does the approach sound sane?
- Should I turn off the warning about unused arguments, or is there some better solution?
- What's up with the abstract qualifier?

Thanks a lot!
Guido

### CODE REVIEW

**Comment by mtzguido** [comment]
(regressions failed just now because of an unrelated change. Will fix, sorry)

**Comment by mtzguido** [comment]
A related question: why are the pretty printers ignoring the freshness integer for `mlident`s? Currently, different `fresh` calls might give variables that turn out identified after printing. Is this just a bug? It's surprising that it didn't show up somewhere already.

**Comment by mtzguido** [comment]
I figured why abstract is messing with extraction here. It's not about the qualifier, because we're using `Inlining` on every normalizer call in `src/extraction`. The thing is we're running extraction after checking which declarations should be exported (passing them through `for_export`). Since `abstract` should not be exported, it's replaced by an assumption `assume val set : Type -> Type0`, which has no definition the normalizer can use.

Should this be refactored so as to allow extraction to make use of these definitions?

**Comment by nikswamy** [comment]
I'm looking at the problem with extracting 

```
module Abs

abstract let set a = a -> Type0

val empty : (#a:Type) -> set a
let empty = fun #a x -> bool //<--- CHANGED THIS TO bool
```

Both versions (with and without the `abstract`) look suspicious to me.

This version, e.g., seems especially bad because it breaks an invariant of the extraction about preserving the arity of symbols. 

`type 'Aa empty = Prims.unit`

Indeed, if I try to then define
```
val foo : empty #int 0
let foo = true
```

then extraction crashes with "Substitution must be fully applied (see GitHub issue #490)"
(although it doesn't seem related to #490)

Here's the trace: 

```
 at FStar.Extraction.ML.Util.subst(FSharpList`1 _arg1_0, mlty _arg1_1, FSharpList`1 args) in D:\workspace\everest\FStar\src\extraction\FStar.Extraction.ML.Util.fs:line 74
   at FStar.Extraction.ML.Util.udelta_unfold(env g, mlty _arg1) in D:\workspace\everest\FStar\src\extraction\FStar.Extraction.ML.Util.fs:line 79
   at FStar.Extraction.ML.Term.is_top_ty@396(env g, mlty t) in D:\workspace\everest\FStar\src\extraction\FStar.Extraction.ML.Term.fs:line 399
```

I'm continuing to look into this

**Comment by victor-dumitrescu** [comment]
@mtzguido About the freshness integers for `mlident`s, I wasn't sure what they were when I wrote the prettyprinter and it seems to me that they're basically always 0. I guess they might have been meant to stand for the counter in `gensym` but that doesn't seem to be the case. As an experiment, I tried removing them entirely (re-defining `mlident = mlsymbol`). I pushed it on branch `vdum_tactics`. Some tests fail but this might be because the were already failing on the branch.

**Comment by mtzguido** [comment]
Thanks Victor. Yes, Jonathan told me a bit about this, and it seems that this `fresh` is really just confusingly named. We should probably wire it through the environment and gensym, right?

Also thanks a lot Nik. What do you think we should do next? Fix this first, or work around it (take `abstract` out of `FStar.TSet`) and merge this for the time being?

**Comment by nikswamy** [comment]
I'm working on the fix today. I hope to complete it soon.

**Comment by nikswamy** [comment]
I have a fix in nik_private; it should merge easily into guido_tactics (at least I expect so).

It's not yet in master because of the usual suspects:

```
$ grep "(Error)" 1_Build.txt | grep STDERR
2017-07-19T05:34:47.8990738Z STDERR: .\FStar.Math.Lib.fst(15,0-17,41): (Error) Unknown assertion failed
2017-07-19T05:35:24.1116661Z STDERR: .\QuickSort.Seq.fst(31,0-48,15): (Error) Unknown assertion failed
2017-07-19T05:36:34.0977598Z STDERR: .\FStar.UInt128.fst(574,0-587,18): (Error) Unknown assertion failed
2017-07-19T05:36:42.6166767Z STDERR: .\FStar.Math.Lemmas.fst(215,8-218,31): (Error) Unknown assertion failed
2017-07-19T05:36:42.6186558Z STDERR: .\FStar.Math.Lemmas.fst(339,0-348,36): (Error) Unknown assertion failed
2017-07-19T05:36:42.6206862Z STDERR: .\FStar.Math.Lemmas.fst(561,0-568,41): (Error) Unknown assertion failed

````

**Comment by mtzguido** [comment]
Great, thanks a lot! I'll take care of the merge and make a new consistent PR.

**Comment by mtzguido** [comment]
I rebased over `guido_tactics` and Github's display of the PR turned to hell... moving discussion back to #1072.

**Pull request closed without merging**
