### PR TITLE
Add #ifdef to set a custom stack size for managed F*

### PR DESCRIPTION
**Pull request by wintersteiger**
Here's a simple way of getting around the small stack size in F#/.NET/Windows. Not necessarily meant to be merged into master, I just wanted to save it somewhere.

### CODE REVIEW

**Comment by msprotz** [comment]
Is there a drawback to activating this by default?

**Comment by wintersteiger** [comment]
I don't think so, except increased memory usage perhaps. I didn't check what mono thinks about it yet, but I'll do that right away.

**Comment by BarryBo** [comment]
There is a tool for modifying EXE files, that can write a different default stack size (reserve+commit) in.  Could you use that tool to munge the F* binary?  That might be an tidier solution if you rarely need the larger stack size.  We used this tool to munge Dafny for a while, to work around deep stacks in Boogie.

**Comment by wintersteiger** [comment]
Yes, I think [editbin](https://msdn.microsoft.com/en-us/library/8e77sz74.aspx) would do that job. Not sure it works on managed binaries though, there may be a separate tool for that. Personally, I prefer it to be compiled right in, but it could just as well be done in a post-build step.

**Comment by wintersteiger** [comment]
I ran uregressions through the mono binary and I don't get any weird exceptions thrown, so I suppose it's "safe enough" to merge.

**Comment by BarryBo** [comment]
Editbin does work on managed EXEs too.  I'm comfortable with both editbin and the code change. :-)

**Comment by msprotz** [comment]
I'm happy to merge this if we make it the default -- I'm weary of having one build configuration that will have little coverage.

**Comment by wintersteiger** [comment]
That's a good point! I think there won't be any complications, but I can give it a few more tests. It's possible that some debuggers (mono?) may behave slightly differently because now there's a different "main" thread.

**Comment by msprotz** [comment]
As long as it doesn't break the Visual Studio debugger experience, it's good -- I'm not aware of anyone debugging using Mono.

**Comment by wintersteiger** [comment]
Done and rebased. Just waiting for the green light from the CI.

**Pull request merged**
