### PR TITLE
Fix pow2 implementation

### PR DESCRIPTION
**Pull request by msprotz**
This speeds up some of my benchmarks by 10%. Super low hanging fruit.

Note that this implementation will throw `Z.overflow` in the event that you are trying to compute `2^x` when `x` does not fit in an `int`, e.g. on a 64-bit machine, when you are trying to compute `2^(2^62)`. My assumption is that no one is really trying to do this, because on a 64-bit machine it would amount to allocating petabytes merely to represent that number (if I got my back of the envelope calculations right).

### CODE REVIEW

**Comment by msprotz** [comment]
Also probably the reason why the `Z` API takes an `int` for the amount of places the shift by, rather than a `Z.tù`

**Comment by nikswamy** [comment]
Everest green?

Some hesitations about this one:

* If we are doing some maintenance on prims.pow2, then we should probably move it out of prims.
* Most of prims.ml looks to be extracted by F*. Whereas this PR patches the .ml directly.

**Comment by msprotz** [comment]
My understanding is that `prims.ml` was once extracted many years ago, but was eventually moved to version control and is now entirely maintained by hand, just like other files in `ulib/ml`:

```
commit 4bae80e9999944ea191bdff0ed7bd5e49bfe8cf6
Author: Nikhil Swamy <nikswamy@users.noreply.github.com>
Date:   Sat Apr 14 12:08:08 2018 -0700

    ml/prims.ml hand edited after auto-gen from prims.fst
```

For instance, `ulib/ml/FStar_Constructive.ml` is in the same situation, and contains code that was originally extracted (`uu_...`) but is now maintained by hand. So, I believe is it's ok to hand-edit stuff in `ulib/ml`, and we've been doing it for a long time, for instance with `ulib/ml/FStar_UInt32.ml`.

Conversely, stuff in `ulib/ml/extracted` is regenerated upon every build and cannot be hand-patched.

I'll run an everest green. Please let me know if, based on my comment, you still would like to see `pow2` moved elsewhere, and if so, what file would be appropriate? Thanks!

**Comment by msprotz** [comment]
Screen Shot 2021-11-22 at 10 10 07 AM

**Comment by nikswamy** [comment]
Why not expose in prims more of the primitive operator from Zarith. 

Z3 supports the power operator "^" in the integer sort. 

We could define:

```
[@@smt_theory_symbol]
assume
val power : int -> int -> int
```
and encode it to SMT as we do the other primitive operators on integers, (greater than etc.).

We could also expose other Zarith operators, like Z.shift_left here too, even if they don't have primitive analogs in SMT, and give them specs in a style similar to FStar.Math.Lib.shift_left

**Comment by msprotz** [comment]
That all sounds reasonable, but orthogonal to this PR, unless you want to change the definition of `pow2` to begin with? 

- If you're suggesting to change the definition of `Prims.pow2` to use a shifting lemma: that would be risky and might break a large number of proofs, but I may be wrong and haven't actually tried that.
- If you're suggesting to have the client code adopt a different definition of `pow2` based on efficient shifting lemmas: there are currently 6,550 references to `pow2` in HACL* alone. So it would be a lot of work to change these references to a saner definition of `pow2`.

I think adding more operators onto `nat` is good and will be useful in the future, but can be done in a followup to this patch.

**Comment by nikswamy** [comment]
My suggestion is to define `pow2 x` as `power x 2`, where `power` is implemented in OCaml as Zarith power_big and encoded to SMT as the `^` primitive. It would save us from needing to use lemmas that describe common powers of two, only to find periodically that it is missing the particularly power of two that some proof needs.

Do you expect your shift_left implementation to be significantly more efficient than `power_big x 2`?

Of course, your patch is much more localized.

But, my point is that if we are going to change the definition/implementation of pow2, it would be good to change it properly to a definition that we can all agree is a good one.

**Comment by msprotz** [comment]
> Do you expect your shift_left implementation to be significantly more efficient than power_big 2 x?

Regarding `Z.shift_left 1 x` vs. `Z.pow 2 x`: `Z.pow` doesn't seem to have a fast-path in case the base is `2`. But a micro-benchmark seems to indicate the difference is insignificant. (The micro-benchmarks for `pow` vs `shift_left` both took 0.25s; but after several minutes, benchmarking `Prims.pow2` was still not done.)

> But, my point is that if we are going to change the definition/implementation of pow2, it would be good to change it properly to a definition that we can all agree is a good one.

Your proposal makes sense and would be ideal. However, I am concerned about:
- delays: your proposed fix requires more work to implement, and I will not have the resources to undertake such a change
- proof breakage: with so much relying on the existing definition of `pow2`, I am afraid changing the F* definition is going to disrupt many proofs

There are already many precedents for implementations that are unrelated to their definition in F* (FStar.List, FStar.String, FStar.UInt*, FStar.Bytes, and many more), so this seems no different to me.

Your proposed overhaul of the definition of `pow2` is of course nice to have, and I am supportive of any subsequent PR that would fix the definition of `pow2` to use `pow_nat`, and its corresponding hand-written implementation to use `Z.pow`.

**Comment by msprotz** [comment]
After discussing with @nikswamy, the patch is unfortunate (discrepancy between F* code and its implementation once extracted) but this unblocks further performance optimization and there are plans in the works (per the comments above) to overhaul pow2 using shift_left, so this should be ok for the time being.

**Pull request merged**
